bluerobotics/BlueOS

- install/install.sh
- install/udev/100.autopilot.rules
Configures a fresh image with companion-docker.
After it reboots, companion-docker will star automatically. 
`Curl` is necessary to run this script.
The following lines need to run as **root**.
How to test (if the repository is public):
```sh
export VERSION=install
export REMOTE=https://raw.githubusercontent.com/patrickelectric/companion-docker
curl -fsSL https://raw.githubusercontent.com/patrickelectric/companion-docker/install/install/install.sh | sh
```
Changes are necessary for non public repositories. 
> install: Add initial version

- install/install.sh
VERSION is already appended to REMOTE, but "install" was missing
> install.sh: remove duplicated branch name, add missing '/install'

- bootstrap/Dockerfile
- bootstrap/README.md
- bootstrap/main.py
- bootstrap/setup.py
- bootstrap/startup.json.default
Bootstrap would be the guy responsible for setting up things for the first run and handling updates (configuration changes where the docker image changes).
Every time it launches, it will load the startup.json file and launch the docker described there. After launching it quits (but I would consider keeping it running indefinitely, too).
The update process for core this way consists of:
- pulling new image
- updating startup.json
- launching bootstrap (if it was not running indefinitely)
- stopping itself.
As the bootstrap is a docker itself, it can be updated by a docker pull
This would be used to restart and update the supervisor, but the implementation will begin within companion-core
> Create bootstrap docker

- bootstrap/Dockerfile
> Bootstrap: change base image to debian:buster-slim (same as core)

- .coveragerc
- bootstrap/bootstrap/bootstrap.py
- bootstrap/test_bootstrap.py
For testing:
Delete the local copy of the bluerobotics/companion-core:master image 
```
docker image rm bluerobotics/companion-core:master```
```
Launch bootstrap:
```
docker run --name companion_bootstrap -it -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/.config/companion:/root/.config/companion -e COMPANION_CONFIG_PATH=$HOME/.config/companion  williangalvani/bootstrap:master
```
> Bootstrap: add a curses interface to low-level-api pull

- core/start-companion-core
Add missing h264parser, decrease the cpu usage in 50%
> core: start-companion-core: Add h264parse

- .github/workflows/python-test.yml
- bootstrap/bootstrap/bootstrap.py
- bootstrap/test_bootstrap.py
It was erroneously trying to mount the startup.json file as a volume instead of the parent directory it is in. You cannot mount a file as a volume.
This makes docker mount the correct volume in line 57
for testing, use williangalvani/bootstrap:master in install.sh
> Bootstrap: Fix config file path

- install/boards/bcm_27xx.sh
- install/boards/bcm_28xx.sh
- install/boards/configure_board.sh
- install/install.sh
How to test:
```sh
export VERSION="break_install";export REMOTE="https://raw.githubusercontent.com/patrickelectric/companion-docker";
curl -fsSL $REMOTE/$VERSION/install/boards/configure_board.sh | bash
```
> install: Break installation method in bcm27 and bcm28 scripts

- core/services/ardupilot_manager/flight_controller_detector/Detector.py
Fixes a new mypy issue caused by the comparison of objects which do not implement the "less than" operator:
`
core/services/ardupilot_manager/main.py:101: error: Returning Any from function declared to return "_SupportsLessThan"
Found 1 error in 1 file (checked 1 source file)
`
> ardupilot_manager: Detector: use IntEnum instead of Enum

- bootstrap/bootstrap/bootstrap.py
Fix #69 
to test, change the image name in startup.json and then run:
```
docker run \                                                                                             
-it \
--rm  \
--name companion_bootstrap \
-v $HOME/.config/companion:/root/.config/companion \
-v /var/run/docker.sock:/var/run/docker.sock \
-e COMPANION_CONFIG_PATH=$HOME/.config/companion \
williangalvani/bootstrap:missingimage
```
> Bootstrap: handle invalid image names

- .github/workflows/python-test.yml
- .hooks/pre-push
This uploads the coverage html as an action artifact:
I need it as I'm facing different results in my machine and in Github Actions.
close #76
> Upload code coverage as artifacts

- install/README.md
We can't set the call to be sudo bash, since docker will be unable to access tty output
> install: Add note to run command as root user

- install/install.sh
With that bootstrap will need to download everything again,
and we need that to do tests and avoid any possible problem.
> install: Force a real clean install with docker prune

- core/services/ardupilot_manager/firmware_download/FirmwareDownload.py
- core/services/ardupilot_manager/mavlink_proxy/Endpoint.py
All of those can be IntEnums, like FlightControllerType is already.
> ArduPilotManager: Use same type for the enums

- install/udev/100.autopilot.rules
This will capture any PX4 device, that is a flight controller unit.
It also fixes any problem related to 'PX4 FMU' (controller software)
and 'PX4 BL FMU' (bootloader).
> install: udev: Change autopilot manufacturer to match any PX4 prefix

- install/README.md
It's easy to just put a `sudo` before the entire command and forget to also run bash as root.
Suggesting `sudo su` prevents people from doing that.
> install/README: update install instructions to prevent user mistake

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/Singleton.py
With the current code structure, it only makes sense to have one instance of the manager running.
> ArduPilotManager: turn class into Singleton

- bootstrap/bootstrap/bootstrap.py
- install/install.sh
This allows us to store and load companion-core settings
> bootstrap: Fix bind to .config

- .github/workflows/deploy.yml
Allow the creation of images based on the branch name
> github: workflows: deploy: Use branch name over fixed master

- install/install.sh
Docker uses VERSION environment variable and it conflicts with companion version
Fix #130
> install: Unset VERSION variable for docker

- core/services/ardupilot_manager/flight_controller_detector/Detector.py
i2c0 is not workable on latest raspberry pi os image, this is preventing ardusub from starting up
will have to dig around more to figure out what's wrong with i2c0 on latest raspberry pi os image (it's working fine on previous buster images)
> core: remove i2c0 from navigator autopilot board detection

- .gitignore
env/ folder is traditionally used to store virtualenvs in python projects
> gitingore: Add env folder

- core/start-companion-core
- core/tools/mavlink_camera_manager/bootstrap.sh
- It'll generate a stream per camera that provides H264 stream, each stream will be a udp://192.168.2.1:(5600 + stream_index)
> core: start-companion-core: Use BlueROV default settings for  mavlink-camera-manager

- core/services/ardupilot_manager/ArduPilotManager.py
When there was no "endpoints" key in settings file, ```UnboundLocalError``` was raised.
> Fix endpoints loading

- install/boards/bcm_27xx.sh
Enable pull-up by default to turn off the user LEDs,
this also helps to avoid questions like:
- The user LEDs are not as bright as the others
> install: boards: bcm_27xx: Turn off user LEDs at boot

- core/services/ardupilot_manager/mavlink_proxy/Endpoint.py
Will allow easier validating and duplication verification in the future.
> core: ardupilot-manager: Make Endpoints hashable

- .github/workflows/tests.yml
- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/mavlink_proxy/Endpoint.py
- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
- core/services/ardupilot_manager/mavlink_proxy/MAVProxy.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
- core/services/ardupilot_manager/settings.py
- Allow for TCP client endpoints 
- Fix creation of serial endpoints on MAVProxy
- Fix validation for both MAVProxy and MavlinkRouter
- Simplify some syntax
> Fix and extend endpoint types

- core/services/ardupilot_manager/ArduPilotManager.py
os fails to move files between different mounts 'invalid cross-device link'
fix #135
> core: ardupilot_manager: use shutil instead of os to move file

- .github/workflows/deploy.yml
I'm always asking myself why a "deploy" action is running on a Pull Request.
(Yes, I used the github web interface to open this PR and I'm not ashamed)
> Rename deploy action to "Build and Depĺoy Images"

- core/services/ardupilot_manager/mavlink_proxy/test_all.py
Checks five times if it has stopped, with one second intervals.
Fix #162
> Add test for router exiting

- bootstrap/startup.json.default
- core/Dockerfile
- core/start-companion-core
- core/tools/linux2rest/bootstrap.sh
Available under port 6030
To test: it's necessary to add the following bind in the bootstrap config:
```
"/sys/": {
"bind": "/sys/",
"mode": "r"
},
```
And use the following image:
`patrickelectric/companion-core:linux2rest`
> Add linux2rest, a rest API + interface for system information 

- .github/workflows/tests.yml
- core/Dockerfile
- core/tools/mavlink_router/bootstrap.py
Use williangalvani/companion-core:trespontonove to test.
startup.json for convenience:
```
{
"core": {
"tag": "trespontonove",
"image": "williangalvani/companion-core",
"enabled": true,
"webui": false,
"network": "host",
"binds": {
"/dev/": {
"mode": "rw"
},
"/var/run/wpa_supplicant/wlan0": {
"bind": "/var/run/wpa_supplicant/wlan0",
"mode": "rw"
},
"/tmp/wpa_playground": {
"bind": "/tmp/wpa_playground",
"mode": "rw"
}
},
"privileged": true
}
}
```
> Core: migrate to Python 3.9

- core/services/cable_guy/html/index.html
- core/services/helper/main.py
- core/services/helper/setup.py
- core/services/wifi/main.py
This extends the helper a little, trying to fetch the title of the service page and checking if swagger is available at /v1.0/ui:
should I go ahead and format it with a table? :thinking: 
convenience startup.json:
```
{
"core": {
"tag": "morehelp",
"image": "williangalvani/companion-core",
"enabled": true,
"webui": false,
"network": "host",
"binds": {
"/dev/": {
"mode": "rw"
},
"/var/run/wpa_supplicant/wlan0": {
"bind": "/var/run/wpa_supplicant/wlan0",
"mode": "rw"
},
"/tmp/wpa_playground": {
"bind": "/tmp/wpa_playground",
"mode": "rw"
}
},
"privileged": true
}
}
```
> Helper: help more

- core/services/cable_guy/.gitignore
The necessity to run eslint as part of the tests turned the npm install mandatory, and so what comes with it :sweat_smile: 
I'm also adding ignore for the static files generated by other services.
> gitignore: Update to include npm and cable-guy stuff

- bootstrap/startup.json.default
> Bootstrap: use 'ro' for read-only bind on /sys

- .github/workflows/tests.yml
- bootstrap/startup.json.default
- core/services/install-services.sh
- core/services/versionchooser/main.py
- core/services/versionchooser/openapi/versionchooser.yaml
- core/services/versionchooser/setup.py
- core/services/versionchooser/static/index.html
- core/services/versionchooser/static/style.css
- core/services/versionchooser/test_versionchooser.py
- core/services/versionchooser/utils/chooser.py
- core/services/versionchooser/utils/dockerhub.py
- core/start-companion-core
This PR adds a Version Chooser service.
It lists all available Companion images, online and locally.
Pulls new images from dockerhub if necessary.
Updates `startup.json` to use another available image.
KIlls companion-core.
After companion-core dies. Bootstrap takes over and attempts to launch it from the edited startup.json. If the launch fails, it reverts to a default startup.json (contained in bootstrap itself).
Convenience startup.json:
```
{
"core": {
"tag": "versionchooser",
"image": "williangalvani/companion-core",
"enabled": true,
"webui": false,
"network": "host",
"binds": {
"/dev/": {
"mode": "rw"
},
"/var/run/wpa_supplicant/wlan0": {
"bind": "/var/run/wpa_supplicant/wlan0",
"mode": "rw"
},
"/tmp/wpa_playground": {
"bind": "/tmp/wpa_playground",
"mode": "rw"
}, …
```
> Create Version Chooser

- .eslintrc.js
This would have caught one error in the versionchooser pr
Check https://eslint.org/docs/rules/no-extra-parens
> CI: Eslint: enable 'no-extra-parens' rule

- core/services/versionchooser/utils/dockerhub.py
This is what the API returns:
```
{'count': 1,
'next': None,
'previous': None,
'results': [{'creator': 6451594,
'full_size': 342651994,
'id': 114550538,
'image_id': None,
'images': [{'architecture': 'arm',
'digest': 'sha256:8a9295ea8ecfa747ffd1ff79af552c5826275d2bf88124eb7071e75a3cdbab82',
'features': '',
'last_pulled': '2021-04-30T13:20:46.674809Z',
'last_pushed': '2021-04-28T21:38:30.628226Z',
'os': 'linux',
'os_features': '',
'os_version': None,
'size': 314955078,
'status': 'active',
'variant': 'v7'},
{'architecture': 'amd64',
'digest': 'sha256:c877a4d62e8146041992228dfa5f6b0a1892eb441794f34c445ff4ce1ba78a9c',
'features': '',
'last_pulled': '2021-04-30T13:25:57.299851Z',
'last_pushed': '2021-04-28T20:10:38.254056Z',
'os': 'linux',
'os_features': '',
'os_version': None,
'size': …
```
> core: services: versionchooser: map both aarch64 and armv7l architectures to 'arm'

- .github/workflows/deploy.yml
If we use a different key each time we run, we can't get any cache hits:
we should just cache based on the image name  and let buildx decide if it is a hit or a miss.
> CI: use the dockerfile hash instead of commit sha to cache dockers

- .eslintrc.js
Even when using `{ properties: 'never' }`, camelcase check will blame on function arguments not using camelcase, so we need to completely remove this check.
> eslint: Remove camelcase check

- bootstrap/bootstrap/setup.py
These are all packages in the working container I have here:
```
certifi==2020.12.5
chardet==4.0.0
companion-bootstrap==0.0.1
docker==5.0.0
idna==2.10
requests==2.25.1
six==1.15.0
urllib3==1.26.4
websocket-client==0.58.0
```
locking "docker" and adding "six"(why was it missing?) seems to fix the issue.
I'll leave the list here in case we need to fix more stuff in the future.
Fix #241
> Bootstrap: fix docker dependency to 5.0.0

- install/boards/bcm_27xx.sh
Fix #245
```
onfiguring BCM27XX board (Raspberry Pi 4)..
- compile spi0 device tree overlay.
- Enable I2C, SPI and UART.
enable_uart=1
dtoverlay=uart1
dtoverlay=uart3
dtoverlay=uart4
dtoverlay=uart5
dtparam=i2c_vc=on
dtoverlay=i2c1
dtoverlay=i2c4,pins_6_7
dtoverlay=i2c6,pins_22_23
dtparam=spi=on
dtoverlay=spi0-led
dtoverlay=spi1-3cs
gpio=11,24,25=op,pu,dh
gpio=37=op,pd,dl
- Set up kernel modules.
bcm2835-v4l2
i2c-bcm2835
i2c-dev
- Configure serial.
- Firmware is up to date.
pi@companion:~ $ echo "$?"
0
```
It fixes the problem and add an extra test to make sure that the firmware needs an update.
> Fix rpi-update 

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
> core: ardupilot-manager: Support UDP Server on MavlinkRouter and fix GCS Link default endpoint

- core/services/versionchooser/utils/dockerhub.py
Previously, the arm builds were showing the remote sha of the x86
images. This fixes that issue by first using the "fat manifest" to get the digest of the correct architecture, and then 
More information at https://docs.docker.com/registry/spec/manifest-v2-2/
helps #267 
(crap. wrong remote)
> core: versionchooser: use 'fat manifest' to fetch the correct image digest on all architectures

- core/tools/bridges/bootstrap.sh
wget is one of the basic tools [installed in companion-base](https://github.com/bluerobotics/companion-docker-base/blob/master/Dockerfile#L11).
it shouldn't be uninstalled or reinstalled in core.
> core: tools: bridges: don't (un)install wget

- core/services/versionchooser/static/index.html
Previously there was a race condition that made the webpage refresh before the
backend came back online (showing "server offline"). This fixes that.
> Core: versionchooser: only start polling the backend once we change the running image

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/firmware_download/FirmwareDownload.py
- core/services/ardupilot_manager/firmware_download/test_FirmwareDownload.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
- core/services/ardupilot_manager/mavlink_proxy/MAVProxy.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
Fix #98 
Use `--sitl` to activate it.
When [this PR](https://github.com/ArduPilot/ardupilot/pull/17573) gets approved we should reintroduce validation of the SITL binary.
~~Missing tests with Rasp/Navigator.~~
Tested with x86 and ARMv7 platforms.
> Add SITL to ArduPilot Manager

- core/services/ardupilot_manager/ArduPilotManager.py
> core: ardupilot_manager: Fix spaces before argument

- core/services/ardupilot_manager/firmware_download/FirmwareDownload.py
- core/services/ardupilot_manager/firmware_download/test_FirmwareDownload.py
Fix #303
Alternative to #304 
Adds a function to find the correct URL to download, this allow us to have magic urls for specific products if a desired combination is valid. Also unifies the validation and permission between such options.
> Add get_download_url to abstract urls for firmware download

- core/services/ardupilot_manager/firmware_download/FirmwareDownload.py
- core/services/ardupilot_manager/firmware_download/test_FirmwareDownload.py
Fix ELF permission, allow the executable permission to all expand to group and owner 
Fix #310
> core: ardupilot_manager: Fix ELF permission

- core/services/ardupilot_manager/ArduPilotManager.py
Tested with an ublox GPS.
Ardusub didn't like the gps on ports other than SERIAL1, so I made all of them serial1 individually to test.
This should allow us to use serial... stuff.
the mapping comes from correlating our the navigtor mapping:
With these docs:
https://ardupilot.org/dev/docs/sitl-serial-mapping.html
> core: ardupilot_manager: map serial ports to ardusub's ports

- core/services/ping/pingdriver.py
Re-starting the connection every time makes the process a lot slower.
image coming soon.
> core: services: ping: reuse the connection when testing a baudrate

- core/services/ping/pingdriver.py
Alternative to #317 
It appears that the true problem is how 4M baudrate works, in the end the sensor can operate with it, but it may fail with high frequency requests. This PR decrease the timeout to allow baud rates that can answer as faster as 100ms.
> core: ping: Fix driver

- core/services/install-services.sh
This passed by on PR #330.
[Did not interfere with installation itself](https://github.com/bluerobotics/companion-docker/runs/2811096298?check_suite_focus=true#step:7:3364), though.
> core: Remove commonwealth from services installation

- core/services/versionchooser/utils/chooser.py
image : williangalvani/companion-core:prune
This adds a cleanup step after pulling images. The dangling ones (not used by a container and not tagged) are removed from the disk:
> core: versionchooser: cleanup dangling images after a pull

- core/tools/mavlink_router/bootstrap.py
As a general rule we should add apt update before calling apt install, this avoid problems related to mirror updates.
I got the same problem every single time in this package because, since we don't know where docker is going to cache, we should do when necessary.
> core: mavlink_router: Add apt update before install commands

- core/services/install-services.sh
We already have python 3.9 available.
This also removes 80MB from our image.
> core: services: install-services: Remove python3 installation

- .eslintrc.js
We are currently using Vue2 on the repo, instead of Vue3.
We thought before Vue3 rules was a superset of Vue2 rules, and they seem to be, but using Vue3 rules raise some warnings regarding new features introduced by Vue3, like [the emits declaration](https://v3.vuejs.org/guide/migration/emits-option.html#_3-x-behavior), that we don't have available (there are more, for sure, but this was the one I've faced already).
> eslint: Use Vue2 rules

- core/libs/commonwealth/setup.py
docker: patrickelectric/companion-core:fix-common
> core: libs: commonwealth: Fix calling setup.py from different path

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/mavlink_proxy/Manager.py
- core/services/ardupilot_manager/settings.py
This PR fixes #353 by allowing mavlink-manager to set the logs directory and changing it to the `logs` folder, created under the app folder.
To allow for better execution and catching behaviors correctly, I separated the methods to create the folders and to create the settings file. This way we always make sure the app folders are there, independently of having or not a settings file (e.g. there could be the case where the logs folder is not there but the settings file is, thus the logs folder not being created).
This fixes the problem of lost logs for now and makes the path for the future decision of where to better put the files, raised by @Williangalvani on #354.
> Move tlogs to `.config` folder making them persistent

- core/services/install-services.sh
- core/services/versionchooser/setup.py
This should speed up arm builds.
This also uses PIP to install the services as vannila setup-tools is unable to handle [PEP 508](https://www.python.org/dev/peps/pep-0508/)
> use wheel for aiohttp in armv7

- core/services/wifi/WifiManager.py
- core/services/wifi/exceptions.py
- core/services/wifi/main.py
- core/services/wifi/typedefs.py
- core/services/wifi/wpa_supplicant.py
Definitely a big refactor, but a much needed one.
Among the changes:
- Introduces timeouts for WPA operations (they could be slow or busy sometimes, making requests fail)
- Everything is async now (YES!) (scan operations, which can take from 5 to 15 seconds do not block other requests anymore)
- Scan logic is refactored so in-progress scan results are used on new fetchs (e.g: 10 requests will not necessarily create 10 scan operations. If there's one scan happening when you make a request, its result will be used)
- Network-registering is now separated from network-connecting, so new connections to known/saved networks don't create infinite new entries
- We can now connect to unprotected networks
- We can now forget saved networks
- Connections are now forced by default (currently if there …
> Refactor wifi service

- core/start-companion-core
- core/tools/mavlink2rest/bootstrap.sh
- Fix problems related to the failsafe mechanism where mavlink2rest was using 255 system id
> Update mavlink2rest to the latest version 

- core/tools/linux2rest/bootstrap.sh
- Fix github actions tag check for Cargo.toml
- Fix usage of CLI to set server port
- Fix html tags
- Set default server port to previous default port (6030)
- Use sysinfo release over master branch
- Add error message on the webpage for platform
- Update to the latest version of sysinfo
- Sort UDP by local address, TCP by local address and process by cpu on webpage
> tools: linux2rest: Update to the last version 0.1.6

- core/frontend/src/App.vue
- core/frontend/src/components/common/PasswordInput.vue
- core/frontend/src/components/common/SpinningLogo.vue
- core/frontend/src/components/wifi/ConnectionDialog.vue
- core/frontend/src/components/wifi/DisconnectionDialog.vue
- core/frontend/src/components/wifi/NetworkCard.vue
- core/frontend/src/components/wifi/WifiManager.vue
- core/frontend/src/components/wifi/WifiTrayMenu.vue
- core/frontend/src/components/wifi/WifiUpdater.vue
- core/frontend/src/store/wifi.ts
- core/frontend/src/types/frontend_services.ts
- core/frontend/src/types/wifi.d.ts
- core/frontend/src/utils/helper_functions.ts
The wifi manager allows among other things:
- showing available networks (hidden or not) and it's properties;
- connecting to new networks (hidden or not);
- connect to existing networks (without pass);
- forgetting knows networks;
- forcing password change;
- disconnecting from current network;
- showing wifi adapter properties (including local IP, security type, signal level and others).
It is mobile-friendly, asynchronous and tries to follow interface patterns already familiar to most users.
Docker image available at `rafaellehmkuhl/companion-core:wifi-frontend`
Preview:
> Add Wifi manager to main frontend

- core/frontend/src/views/MainView.vue
- core/services/ardupilot_manager/ArduPilotManager.py
First step to solve #418 
Image available at `rafaellehmkuhl/companion-core:gcs-endpoint`
> core: ardupilot-manager: Make default GCS endpoint an UDP server

- bootstrap/bootstrap/bootstrap.py
- core/libs/commonwealth/setup.py
- core/services/ardupilot_manager/firmware_download/FirmwareDownload.py
- core/services/ardupilot_manager/settings.py
- core/services/ardupilot_manager/setup.py
- core/services/cable_guy/api/settings.py
- core/services/cable_guy/setup.py
- core/services/ping/serialhelper.py
- core/services/versionchooser/utils/chooser.py
Last update on Pylint rules enforce explicity set of encoding type on context management blocks.
> core: Add encoding argument to `with open` blocks

- core/start-companion-core
`baseurl` argument is needed to make file-browser work properly with reverse-proxys (such as nginx).
> core: file-browser: Add baseurl argument on start

- core/Dockerfile
- core/tools/logviewer/bootstrap.sh
- core/tools/nginx/nginx.conf
image is up at williangalvani/companion-core:logviewer
it is served by nginx at /logviewer, and isn't picked up by the helper as it isn't an independent server.
> Add Logviewer

- .eslintrc.js
We believe ForOf statements are more readable, and readability comes first. Let the developer decide which one to use at its own discretion.
> .eslint: remove ForOFStatement restriction

- core/tools/logviewer/bootstrap.sh
nginx is not set up to serve .gz files, so we delete them to save
some space (whooping 5MB)
> core: tools: logviewer: remove .gz files

- core/tools/mavlink2rest/bootstrap.sh
Changes from the last version:
- Fix serial communication
- Add mavlink2 extensions back
> core: tools: mavlink2rest: Update mavlink2rest to t0.11.4

- core/tools/nginx/nginx.conf
this will make refreshing the page when at http://companion.local/logs work as expected.
> core: frontend: nginx: add 'try_files' to work with vue in history mode

- core/frontend/package.json
- core/tools/nginx/nginx.conf
This allows running the frontend in the local machine while still talking to the actual API running in the companion.
> core: frontend: add proxy for APIs in dev mode

- core/frontend/src/App.vue
- core/frontend/src/components/logs/LogManager.vue
- core/frontend/src/libs/filebrowser.ts
- core/frontend/src/router/index.ts
- core/frontend/src/types/filebrowser.ts
- core/frontend/src/types/frontend_services.ts
- core/frontend/src/views/LogView.vue
Log browser allow to download, delete and play autopilot logs (both `.tlog` and `.bin`).
Log browser uses `filebrowser` API to deal with the files and `UAV Logviewer` to play them.
Docker image available at `rafaellehmkuhl/companion-core/add-log-browser`
> Add log browser

- core/frontend/src/components/autopilot/FirmwareManager.vue
Use the same message as the alert component.
Fix #467
> core: frontend: Refactor LiveNotification error message on firmware install fail

- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
The support has some problems, we are going to disable until tlog works for multiple endpoints
Fix #475
> core: ardupilot-manager: Remove tlog support for mavlink-router for now

- core/frontend/src/App.vue
- core/frontend/src/components/autopilot/AutopilotManagerUpdater.vue
- core/frontend/src/components/autopilot/EndpointCard.vue
- core/frontend/src/components/autopilot/EndpointCreationDialog.vue
- core/frontend/src/components/autopilot/EndpointManager.vue
- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/frontend/src/router/index.ts
- core/frontend/src/store/autopilot_manager.ts
- core/frontend/src/types/autopilot.ts
- core/frontend/src/types/frontend_services.ts
- core/frontend/src/types/vuetify.ts
- core/frontend/src/utils/pattern_validators.ts
- core/frontend/src/views/EndpointView.vue
Add page for listing, creating and deleting autopilot endpoints.
Creation forms include IP/Path and Port/Baudrate validation.
Image soon on `rafaellehmkuhl/companion-core:endpoints-frontend`.
Partially solves #445
> Endpoints frontend

- core/services/ardupilot_manager/main.py
Contributes to #445 by allowing fetch of current running platform and system restart.
Also allows toggling between SITL and auto-detected board.
> Add extras on autopilot API

- core/frontend/src/App.vue
- core/frontend/src/router/index.ts
This is a "gambiarra", a "chuncho" to make the version-chooser service call the correct URL on API requests.
> core: frontend: Use /version-chooser as view route

- .github/workflows/tests.yml
these dependencies should be available before setup call
> CI: Install appdirs and loguru before setup.py

- core/services/wifi/WifiManager.py
- core/services/wifi/main.py
- core/services/wifi/typedefs.py
Auto-enable and try reconnection to known networks if disconnected for more than specified time.
By removing the reenable of all saved networks on new connections, those changes also ensure connections are guaranteed (preventing impossibility of connecting to another network if there's a known one with bether signal nearby).
Solves #394
> core: wifi-manager: Add connection watchdog

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/mavlink_proxy/Manager.py
Solves #523 for `mavlink-router`, our currently default (and only available) router.
`mavlink-router` process dies when the serial connection is lost, so we add a watchdog monitoring it's process.
To fix `mavproxy`'s behavior (we want?) I would change the package itself, or letting it die on serial lost (replicating `mavlink-router`'s behavior) or trying to retake connection (need to see if serial path is kept after recconection).
Image available soon.
> Fix pixhawk retake

- core/frontend/src/App.vue
- core/frontend/src/router/index.ts
Views under the autopilot menu received `/autopilot` as a prefix. Same happened for tools menu.
Image already available.
> core: frontend: Add menu prefix to view's URLs

- core/tools/nginx/nginx.conf
Fix #632 
Available on: patrickelectric/companion-core:redirect_nginx
> core: tools: nginx: Add 2770 redirect to companion.local

- core/tools/mavlink_camera_manager/bootstrap.sh
- Provide correct video type over mavlink, RTPUDP over RTSP
- Add stats in V4L control to inform if it's disabled or inactive
Fix #649
Fix #494 
Available on: patrickelectric/companion-core:update_camera_manager
> core: tools: mavlink_camera_manager: Update to version t3.0.11

- core/Dockerfile
This makes the install step to be cached and when used it takes only
10s to run, before this change it could take up almost 2min.
Helps with #437
> core: dockerfile: Use cache for node_modules

- core/libs/install-libs.sh
- core/services/install-services.sh
- core/tools/ardupilot_tools/bootstrap.sh
- core/tools/filebrowser/bootstrap.sh
- core/tools/logviewer/bootstrap.sh
- core/tools/mavlink2rest/bootstrap.sh
- core/tools/ttyd/bootstrap.sh
I got a situation where ttyd fails to download but the ttyd file is there and empty
> core: tools: bootstraps: Add missing 'set -e' to raise if any command fails

- core/frontend/src/components/app/BackendStatusChecker.vue
- core/frontend/src/components/autopilot/AutopilotManagerUpdater.vue
- core/frontend/src/components/bridges/BridgetUpdater.vue
- core/frontend/src/components/ethernet/EthernetUpdater.vue
- core/frontend/src/components/nmea-injector/NMEAInjectorUpdater.vue
- core/frontend/src/components/video-manager/VideoUpdater.vue
- core/frontend/src/components/wifi/WifiUpdater.vue
With previous approach, each request would wait for the previous one to be fullfiled before starting.
This was the cause of, among other things, wifi scans and video-stream fetchs taking about 5-10 seconds to start on page refresh.
Fix #582
> core: frontend: Start all periodicall resquests together

- core/frontend/src/components/wifi/ConnectionDialog.vue
- core/frontend/src/components/wifi/DisconnectionDialog.vue
This PR aims to improve (a lot) user's experience with wifi connection. Between the changes are:
- Add loading status while connecting
- Add connection result messages
- Raise wifi connection timeout, preventing cancelled requests
- Fix disconnection dialog appearing unexpectedly
- Reset password input box after connection
- Use backend's detailed error messages on connection
Needs #674
Fix #513
Fix #533 
Image available already.
> Improve wifi-manager frontend

- core/frontend/src/components/autopilot/FirmwareManager.vue
Unfortunately we can't catch the exact error, as it is thrown by Chrome itself, but if the backend is not offline and we catch a `Network Error` there's a big chance it was it, and we let the user be aware of it.
Fix #633
> core: frontend: Catch Chrome's `ERR_UPLOAD_FILE_CHANGED` and proper explain it to the user

- core/frontend/src/components/wifi/WifiManager.vue
Like most wifi managers this PR makes ours only show the access-point with the strongest signal-level. Connecting to one AP or another becomes a responsability `wpa` itself.
If we see the necessity in the future we can add a logic to store both the ssid and the bssid and try enforcing the connection to the desired AP (the one with the desired bssid). As this would make everything less intuitive to the user, we should discuss that with care.
Fix #664
> core: frontend: Only show strongest access point when multiple with the same SSID

- .github/workflows/deploy.yml
let's just get this in so we don't need a similar commit in every pull request...
> CI: deploy: bump size limit to 700MB

- install/boards/bcm_27xx.sh
- install/install.sh
Fix #697 
Also sets the baudrates for the i2c buses for navigator. 1MHz for the internal buses and 400kHz for external peripherals.
> Minor updates to install scripts

- core/frontend/src/components/autopilot/EndpointCard.vue
- core/frontend/src/components/autopilot/EndpointCreationDialog.vue
- core/frontend/src/types/autopilot.ts
- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/exceptions.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/Endpoint.py
- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
- core/services/ardupilot_manager/mavlink_proxy/MAVProxy.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
- Add 'enabled' property to mavlink endpoints, so they can be disabled (not used by the mavlink router) without being deleted
- Allow users to enable/disable endpoints on the fly with the endpoint frontend
With this change, the default GCS Link was duplicated, so we have a server one and a client one (with the former pointing to 192.168.2.1). The client endpoint is disabled by default. This change will make the life of our clients experiencing connection problems easier.
Fix #657
> core: Support disabling mavlink endpoints

- core/services/ping/portwatcher.py
Fix #692
We can also print other information, or just remove this line completely.
I think it is useful for debugging, as we know exactly what ports the serial lib is finding (so that we can easily detect a broken serial adapter).
portwatcher:start_watching:59 - Currently detected ports: ['usb-serial:ttyUSB1', 'usb-serial:ttyUSB0', 'amba:ttyAMA3', 'amba:ttyAMA2', 'amba:ttyAMA1', 'amba:ttyAMA0']
> Core: Ping: fix logging of random SysFS objects

- core/services/ardupilot_manager/ArduPilotManager.py
- core/start-companion-core
so far, that means Mavlink2Rest and mavlink-camera-manager.
I'm not sure of how ArdupilotManager would handle changing an existing endpoint, so I made a new one...
williangalvani/companion-core:shared-link
> Use a shared mavlink-router endpoint for internal services

- core/frontend/src/types/video.ts
> core: frontend: Make UsbBusType consistent with `camera-manager` 3.1.0

- core/tools/logviewer/bootstrap.sh
allows using hidden field 'time_boot_ms' in expressions
Also improves plotting of messages with very low frequency,
which previously where not viewable
image ~building~ at williangalvani/companion-core:bumplogviewer
> Core: Tools: bump loviewer version to 0.9.8

- core/frontend/src/App.vue
- core/frontend/src/components/app/SettingsMenu.vue
- core/frontend/src/libs/settings.ts
- core/frontend/src/store/settings.ts
- core/frontend/src/views/GeneralAutopilot.vue
- core/services/ardupilot_manager/main.py
- Add Pirate Mode (advanced/unsecure options available)
- Allows start and stop of the autopilot from the frontend, only when in Pirate Mode ‍ 
Fix #714
> Add pirate mode and allow starting/stopping autopilot

- core/services/versionchooser/setup.py
As stated [here](https://github.com/p1c2u/openapi-schema-validator/issues/31) version 0.2.0 of openapi-schema-validator introduces a dependency conflict with jsonschema.
As our dependency is connexion, we should follow [this](https://github.com/zalando/connexion/issues/1430) issue to be on track with changes.
> core: version-chooser: Constrain dependency version

- core/frontend/src/App.vue
- core/frontend/src/store/settings.ts
- core/frontend/src/utils/helper_functions.ts
- core/frontend/src/views/GeneralAutopilot.vue
As stated on #730, frontend settings were not working properly.
Basically what was happening was that the variables on the localStorage are always stored as a string or a null type. When loaded onto the vuex store, we were not casting those to proper types. With that, strange things were happening, like switches starting on true state even when a false state was comming from to localStorage. Problem was that the state was the string "false", which is true-ish on Javascript.
Added a `castString` helper function to help with that.
Some auto-fixes from the linter were also performed.
Fix #730
> Fix frontend settings

- core/frontend/src/components/wifi/WifiManager.vue
- Custom color was impossible to read on dark mode, as seem on #734. Removing custom color and using default light theme is enough to fix the issue.
- Use a color that gets pretty both on light and dark mode for hovering available networks
Fix #734
> Fix wifi unreadable

- bootstrap/bootstrap/bootstrap.py
- bootstrap/bootstrap/setup.py
- bootstrap/test_bootstrap.py
- install/install.sh
This add a new test in bootstrap to check if version-chooser is running properly in core.
after 60s of it being unresponsive, the startup.json file is restored and core is restarted from that.
> Bootstrap: check version-chooser in core and restart it if unresponsive

- core/services/versionchooser/utils/chooser.py
Fix #384
image being built: williangalvani/companion-core:fix_tag_check
> core: version-chooser: fix checking for remote tags with 'companion-core'

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/exceptions.py
- core/services/ardupilot_manager/firmware/FirmwareDownload.py
- core/services/ardupilot_manager/firmware/FirmwareInstall.py
- core/services/ardupilot_manager/firmware/FirmwareUpload.py
- core/services/ardupilot_manager/firmware/test_FirmwareDownload.py
- core/services/ardupilot_manager/firmware/test_FirmwareInstall.py
- core/services/ardupilot_manager/flight_controller_detector/Detector.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
- core/services/ardupilot_manager/mavlink_proxy/Manager.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
- core/services/ardupilot_manager/setup.py
- core/services/ardupilot_manager/typedefs.py
- pyproject.toml
Folllwing #635 this is a put-order-in-the-house PR.
Main changes are:
- Moving the router watchdog method to the Mavlink Manager, since it's the correct responsible for making the router work
- Raise on Mavlink Router start fail, making sure we know when it happens and correctly deal with it
- Create the FlightController type, which is used in favor of the generic tuples to retain information about available flight-controllers. This deprecates FlightControllerType in favor of Platform, since they share basically the same info, and any additional one (e.g. board name) is available on FlightController itself
Image available already.
Fix #556
> Ardupilot-manager refactor #2

- core/services/versionchooser/utils/chooser.py
the fullname is something like "bluerobotics/companion-core:tagname", so startswith was always failing
> core: version-chooser: fix filtering local docker images

- install/install.sh
This addresses #736 by adding a `--skip-board-config` argument to the installation script. It also adds some rudimentary usage hints with the `--help` argument. The `get_options` function can easily be extended to accommodate future options (overriding git or docker image repos, for example).
This was tested on a Raspberry Pi 4 1GB running a clean install of `bullseye-lite` with the command:
```
sudo su -c 'curl -fsSL https://raw.githubusercontent.com/matt-bathyscope/companion-docker/master/install/install.sh | bash -s -- --skip-board-config'
```
> Add option to skip board config during install

- core/services/ardupilot_manager/flight_controller_detector/Detector.py
If you require access to the class's properties/methods it's better to use `classmethod`, instead of `staticmethod` with global calls to the class name.
> core: services: ardupilot_manager: `Detector.py` improvement

- core/tools/ardupilot_tools/bootstrap.sh
- Move from Patrick's fork to ArduPilot's upstream
- Update to latest commit
> core: tools: Use upstream updated version of fw decoder

- core/frontend/src/components/notifications/ConfigMenu.vue
- core/frontend/src/components/notifications/NotificationManager.vue
- Limit number of recent notifications to 100
- Fix button to show/hide old notifications
- Don't show old notifications by default (prevent performance issues)
Fix #756
> frontend: Limit number of notifications

- core/services/ardupilot_manager/ArduPilotManager.py
- core/start-companion-core
This reverts commit fd9c3c4e2e04744b1f6e123b28236bac5630fe5c.
It turns out that mavlink-router also doesn't support multiple clients in server mode. Why the hell do they call it a server at all?
anyway. the symptom is that mavlink2rest and the cameramanager fight for the endpoint, which causes camera packages not to arrive to qgc, and messages not to arrive to mavlink2rest (not even heartbeats).
image up at williangalvani/companion-core:mavlink2restendpoint
> Revert "Core: Mavlink2Rest: use internal endpoint for communications"

- core/libs/commonwealth/commonwealth/utils/logs.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/settings.py
- core/services/bridget/main.py
- core/services/cable_guy/main.py
- core/services/commander/main.py
- core/services/nmea_injector/main.py
- core/services/ping/main.py
- core/services/wifi/main.py
- core/tools/ardupilot_tools/bootstrap.sh
This patch introduces storage of the service logs.
All logs are stored under the root user log folder (/root/.cache/log), with each service having its own folder.
The files use the following name pattern: `logfile_MM_DD_YY_HH_mm_SS.log`
> Store service logs

- install/udev/100.autopilot.rules
Add some  more  rules on udev:
make  modemmanager ignore autopilot boards :  really  usefull when you are using some 4/5G modems
make  the same for USB-UART converter, make them write enable by default for all user (maybe  do  the same for autopilot?)
> More udev rules

- core/frontend/src/components/ethernet/AddressCreationDialog.vue
- core/frontend/src/components/ethernet/EthernetManager.vue
- core/frontend/src/components/ethernet/InterfaceCard.vue
- core/frontend/src/types/ethernet.ts
- core/services/cable_guy/api/manager.py
- core/services/cable_guy/api/settings.py
- core/services/cable_guy/main.py
Before this patch, cable-guy was only able to handle one address per ethernet interface. This was leading to issues like the user only being able to see one IP address on the frontend (even when the interface had multiple), which could cause some misunderstood.
With this patch, the user is now able to:
- See multiple IP addresses associated with each ethernet interface
- Add new IP addresses to a given interface
- Remove specific IP addresses from a given interface
Also, some error messages were made more clear, raises were added where necessary and logs from settings are now done with loguru.
Fix #428
> core: cable-guy: More than one IP address

- bootstrap/Dockerfile
Best practice on Docker : clean up after apt install. 
This purge 30Mb from the image. Any subsequent use of apt would need apt update anyway
> Bootstrap: Clean up apt cache after install

- core/frontend/src/components/health/HealthTrayMenu.vue
- core/frontend/src/components/mavlink-inspector/MavlinkInspector.vue
- core/frontend/src/types/common.ts
- core/frontend/src/types/mavlink.ts
- core/tools/mavlink2rest/bootstrap.sh
- The latest version has header information of the mavlink message
- Changelog: https://github.com/patrickelectric/mavlink2rest/releases/tag/t0.11.7
- docker: patrickelectric/companion-core:m2r_ws
> core: Add support to mavlink2rest 0.11.7

- core/frontend/src/components/scanner/availableServicesTable.vue
- core/frontend/src/types/helper.ts
- core/services/helper/main.py
Available on: docker.io/patrickelectric/companion-core:versions
Fix #581
> core: Add path for all versions available from documentation 

- core/services/ardupilot_manager/firmware/FirmwareDownload.py
as weird as it may seem, we have more control over betas than dev versions.
> core: ardupilot manager: use BETA firmware for Navigator and SITL

- core/services/versionchooser/utils/chooser.py
it is started every boot and no longer exits.
This fixes an issue in the new images where version chooser tried to start companion-bootstrap but it doesn't exist (we use blueos-bootstrap instead)
> core: version-chooser: do not attempt to start bootstrap anymore

- core/services/ardupilot_manager/setup.py
Beta3 includes default streamrates and default settings for lights and camera tilt mount pins
> core: ardupilotmanager: bump default navigator firmware to 4.1.0-beta3

- core/frontend/src/components/autopilot/AutopilotManagerUpdater.vue
- core/frontend/src/components/autopilot/BoardChangeDialog.vue
- core/frontend/src/store/autopilot_manager.ts
- core/frontend/src/types/autopilot.ts
- core/frontend/src/views/GeneralAutopilot.vue
- core/libs/commonwealth/commonwealth/utils/general.py
- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/exceptions.py
- core/services/ardupilot_manager/firmware/FirmwareDownload.py
- core/services/ardupilot_manager/firmware/FirmwareInstall.py
- core/services/ardupilot_manager/firmware/FirmwareManagement.py
- core/services/ardupilot_manager/firmware/FirmwareUpload.py
- core/services/ardupilot_manager/firmware/test_FirmwareDownload.py
- core/services/ardupilot_manager/firmware/test_FirmwareInstall.py
- core/services/ardupilot_manager/flight_controller_detector/Detector.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
- core/services/ardupilot_manager/mavlink_proxy/MAVProxy.py
- core/services/ardupilot_manager/mavlink_proxy/Manager.py
- core/services/ardupilot_manager/mavlink_proxy/main.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
- core/services/ardupilot_manager/setup.py
- core/services/ardupilot_manager/typedefs.py
- install/udev/100.autopilot.rules
- Fully support Pixhawk4 (add support for firmware management and correct board detection);
- Allow toggling between different connected boards (specially useful for development and testing);
- Disallow firmware management for unsupported board (not Pixhawk1 nor Pixhawk4), preventing bad firmware uploads;
- Improve board detection, preventing bootloader from being as a fully booted board;
- Prevent ardupilot binaries being left running by pruning them all (and not only the one running);
- Make mavlink-router behavior more predictable by always asking for master-endpoint on start, preventing, for example, bad restarts from the watchdog;
- Make FlightController the central logic piece for ArdupilotManager, in place of Platform;
...and some other small code/logic improvements.
Fix #810
Fix …
> core: ardupilot-manager: Support Pixhawk4 (+ other improvements)

- bootstrap/startup.json.default
- core/libs/commonwealth/commonwealth/utils/logs.py
> core: move service logs to `/var/logs/blueos`

- core/frontend/src/components/version-chooser/VersionChooser.vue
now the modal is hidden after the image finished downloading, and a spinner shows up while we load the new image
> tweak version chooser

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
Extra configuration is a feature that is intended to be used by advanced users for now.
> core: frontend: componenets: video-manager: Only show extra configuration under pirate mode

- core/services/beacon/default-settings.json
- core/services/beacon/main.py
- core/services/beacon/settings.py
- core/services/beacon/setup.py
- core/services/install-services.sh
- core/start-blueos-core
- install/network/avahi.sh
This is a very configurable mDNS alternative to avahi.
fix #472 
fix #360 
fix #849 
lays the groundwork for #680 
image is live at williangalvani/blueos-core:beacon
I'll go through this one more time to tidy up and add comments/logging/better exception handling
> Core: create Beacon

- core/frontend/src/views/MainView.vue
It will still show up everytime for now, but so would the previous one
> Core: frontend: turn welcome card into a dismissible alert

- core/frontend/src/components/autopilot/FirmwareManager.vue
> frontend: Make firmware buttons don't go one over another

- core/frontend/src/App.vue
- Make text suitable for mobile screens
- Make text more clear when on disconnected state
Before: <img width="856" alt="image" src="https://user-images.githubusercontent.com/6551040/159998601-59cc4af4-f76b-4682-8e65-057913101ff8.png">
After: <img width="861" alt="image" src="https://user-images.githubusercontent.com/6551040/159998738-1f55c91b-0784-49b6-b4be-057e86356149.png">
Before and after: 
Yup, pirate-mode + disconnected on mobiles is also fine 😄 
Fix #769
> frontend: Improve pirate-mode warn text

- core/frontend/src/components/version-chooser/VersionChooser.vue
It will now properly wait for the backend to first go offline, and then wait for it to come back online
> core: frontend: improve logic for checking if backend is online in versionchooser

- core/services/commander/main.py
fixes an issue where the pi is shutting down instead of rebooting.
image will be up at williangalvani/blueos-core:reboot when CI finishes.
> core: commander: use 'reboot' instead of 'shutdown -r' to reboot

- core/frontend/src/App.vue
- core/frontend/src/components/autopilot/EndpointCard.vue
- core/frontend/src/views/GeneralAutopilot.vue
- core/frontend/src/views/MainView.vue
This PR will group some small frontend fixes:
Avatars on home tiles:
Buttons on autopilot/general:
Endpoint name on autopilot/endpoints:
Fix pirate "ahoy" message showing on medium screens but not on large ones:
> frontend: home: Small frontend fixes

- core/services/beacon/main.py
The goal here is that the dns entry "drops" soon after a connection changes.
Say you disconnect from wifi, this will make the devices in your wifi network to drop blues.local from their dns tables after 25s
this is low priority, and it would be nice to have more testing done.
> core: beacon: set ttl to 25 seconds

- core/services/beacon/main.py
Beacon was not outputting its logging to a file. Fix that.
> core: beacon: Log loguru output on file

- core/frontend/src/components/app/PowerMenu.vue
- core/frontend/src/components/app/SettingsMenu.vue
- core/frontend/src/components/autopilot/AutopilotManagerUpdater.vue
- core/frontend/src/components/autopilot/EndpointCard.vue
- core/frontend/src/components/autopilot/EndpointCreationDialog.vue
- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/frontend/src/components/bridges/BridgeCard.vue
- core/frontend/src/components/bridges/BridgeCreationDialog.vue
- core/frontend/src/components/ethernet/AddressCreationDialog.vue
- core/frontend/src/components/ethernet/EthernetUpdater.vue
- core/frontend/src/components/ethernet/InterfaceCard.vue
- core/frontend/src/components/nmea-injector/NMEAInjectorUpdater.vue
- core/frontend/src/components/nmea-injector/NMEASocketCard.vue
- core/frontend/src/components/nmea-injector/NMEASocketCreationDialog.vue
- core/frontend/src/components/wifi/ConnectionDialog.vue
- core/frontend/src/store/bridget.ts
- core/frontend/src/utils/update_time.ts
- core/frontend/src/views/GeneralAutopilot.vue
- core/libs/commonwealth/commonwealth/utils/apis.py
- core/services/ardupilot_manager/main.py
- core/services/bridget/main.py
- core/services/cable_guy/main.py
- core/services/commander/main.py
- core/services/helper/main.py
- core/services/nmea_injector/main.py
- core/services/ping/main.py
- core/services/wifi/main.py
- Use a global exception handler, so exceptions not caught are all logged and return a default HTTP status-code of 500 with the exception message appended;
- Adapt the frontend of the services to consider this new standard.
With this new approach, we guarantee every not-handled exception to be in the logs, making debug easier, both for frontend and local. Error messages more specific than "returned status code of 500" will start to come.
Image available at `rafaellehmkuhl/blueos-core`
> core: Add global exception handler

- core/frontend/src/components/system-information/Kernel.vue
- core/frontend/src/store/system-information.ts
- core/frontend/src/views/SystemInformationView.vue
> Add kernel output in system-information

- core/frontend/src/components/system-information/AboutThisSystem.vue
- core/frontend/src/components/system-information/Kernel.vue
- core/frontend/src/components/system-information/Network.vue
- core/frontend/src/components/system-information/NetworkCard.vue
- core/frontend/src/components/system-information/Processes.vue
- core/frontend/src/components/system-information/SystemCondition.vue
- core/frontend/src/components/system-information/SystemConditionCard.vue
- core/frontend/src/views/SystemInformationView.vue
Before/after
All the available system-info pages had similar improvements.
Fix #955 
Fix #956
> Improve system-information design

- core/frontend/src/components/app/PowerMenu.vue
- core/frontend/src/components/app/SettingsMenu.vue
- core/frontend/src/components/autopilot/AutopilotManagerUpdater.vue
- core/frontend/src/components/autopilot/EndpointCard.vue
- core/frontend/src/components/autopilot/EndpointCreationDialog.vue
- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/frontend/src/components/bridges/BridgeCard.vue
- core/frontend/src/components/bridges/BridgeCreationDialog.vue
- core/frontend/src/components/ethernet/AddressCreationDialog.vue
- core/frontend/src/components/ethernet/DHCPServerDialog.vue
- core/frontend/src/components/ethernet/EthernetUpdater.vue
- core/frontend/src/components/ethernet/InterfaceCard.vue
- core/frontend/src/components/nmea-injector/NMEAInjectorUpdater.vue
- core/frontend/src/components/nmea-injector/NMEASocketCard.vue
- core/frontend/src/components/nmea-injector/NMEASocketCreationDialog.vue
- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/components/wifi/ConnectionDialog.vue
- core/frontend/src/store/bridget.ts
- core/frontend/src/store/video.ts
- core/frontend/src/utils/update_time.ts
- core/frontend/src/views/GeneralAutopilot.vue
Use `error.response?.data ?? error.message` instead
With this, we catch two situations:
1. Error is not of HTTP type and does not have a response property
2. Error is of HTTP type but does not have a payload (data)
In both situations javascript would throw and, if such expression was on an auto-updater, for example, the auto-updater would die.
This happened when, for example, a timeout occurs.
> frontend: Use chaining operator on all `error.response.data` calls

- core/frontend/src/components/utils/iframe.vue
Fixes the issue of opening iframes from some domains. not sure why.
proper test image will be up at williangalvani/blueos-core:no-lazyness after CI is done
> core: frontend: remove lazi-loading from iframes

- core/services/beacon/main.py
- core/services/beacon/settings.py
This removes blueos.local from both default domain and wlan0.
This means random ethernet adapters plugged into usb will not get any broadcasts by default.
We should discuss this in tomorrow's call.
> core: beacon: change settings to V2

- .github/workflows/test-and-deploy.yml
- core/frontend/src/components/autopilot/AutopilotManagerUpdater.vue
- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/frontend/src/store/autopilot_manager.ts
- core/frontend/src/types/autopilot.ts
- core/frontend/src/utils/api.ts
- core/frontend/src/views/GeneralAutopilot.vue
- core/libs/commonwealth/commonwealth/mavlink_comm/MavlinkComm.py
- core/libs/commonwealth/commonwealth/mavlink_comm/VehicleManager.py
- core/libs/commonwealth/commonwealth/mavlink_comm/typedefs.py
- core/libs/commonwealth/setup.py
- core/libs/install-libs.sh
- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/main.py
- core/services/nmea_injector/TrafficController.py
- Make MavlinkComm/VehicleManager async
- Add following info about autopilot:
- Mavlink platform
- Board manufacturer
- Firmware version
- Vehicle type
- Path (for serial boards)
- Pre-build/install dependencies before libs and services
I'm thinking about parsing the vehicle-type to be more human-readable and will merge the General and Firmware pages (on this or a following PR).
Fix #458 
Fix #777 
Fix #949 
Image available under `rafaellehmkuhl/blueos-core`
> Improve available info about autopilot

- core/tools/nginx/nginx.conf
this redirects 192.168.2.2:2770 to 192.168.2.2.
ideally we should redirect it to "blueos.local" or whatever the current name is, but I don't think we can fetch that name from nginx yet...
We could use beacon in the frontend to choose a domain and redirect to it
fix #632
> core: nginx: fix 2770 -> 80 redirect

- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/views/MainView.vue
Just something that was bugging me. 
I guess `"rel=noopener"` [is not necessary anymore.](https://stackoverflow.com/questions/50709625/link-with-target-blank-and-rel-noopener-noreferrer-still-vulnerable)
> open links in new tabs

- core/frontend/src/libs/notifier.ts
Adds possibility of emitting an alert when pushing error notifications.
This is mostly useful for giving feedback on user actions (e.g.: someone trying to add an endpoint, but the backend rejects for duplicity).
Image available.
> Integrate error-alert with Notifier

- core/frontend/src/components/bridges/Bridget.vue
- core/frontend/src/components/nmea-injector/NMEAInjector.vue
- core/services/bridget/bridget.py
- core/services/nmea_injector/TrafficController.py
- core/services/nmea_injector/main.py
- core/services/nmea_injector/settings.py
> core: nmea-injector: Make settings persistent between sessions

- core/frontend/src/App.vue
- core/frontend/src/types/helper.ts
- core/services/helper/main.py
This follows our documentation described in the wiki page
To test:
create the following file in a path: `register_service`
content:
```js
{
"name":"Extension name",
"description":"A small description about the service",
"icon":"mdi-alpha-p-box",
"company":"Blue Robotics",
"version":"1.2.0",
"webpage":"https://github.com/bluerobotics/BlueOS-docker",
"api":""
}
```
start simple python http server:
`python3 -m http.server 9992`
docker: patrickelectric/blueos-core:add_3rd_party_integration
> core: Add initial 3rd party integration

- core/frontend/src/components/notifications/NotificationManager.vue
- core/frontend/src/components/notifications/TrayButton.vue
As before, we were showing on the tray notification icon the number of active notifications.
On the other hand, the notification's manager was showing just recent notifications (from the last minute and limited to 100).
With this change, the manager emits the updated number of notifications it is showing, and the tray icon uses it, so they are in sync.
Tip here: the `eager` property on the `v-menu` component is what makes it instantiate the manager on mount and allow the emit updates to start without the need for the user to click the menu icon.
Fix #953
> frontend: notifications: Use on tray icon number of notifications being displayed

- core/libs/commonwealth/commonwealth/utils/decorators.py
Cache was global for all inputs and not for each input.
Patch tracks the time per entry now.
> core: libs: commonwealth: decorators: Fix temporary_cache

- core/services/nmea_injector/TrafficController.py
This ensures the forward-message tasks are added to the current running loop.
Fix #993
> core: nmea-injector: Add forward-message task to running loop

- core/services/wifi/wpa_supplicant.py
The main function was not updated when this module was converted to async.
Mypy correctly catch this on it's last update.
> core: wifi: Make `wpa_supplicant` main function async

- core/services/versionchooser/setup.py
- core/services/versionchooser/utils/chooser.py
we should have a way of cleaning up until https://github.com/aio-libs/aiodocker/issues/696 is closed.
> core: versionchooser: cleanup dangling docker images when starting up

- core/tools/ardupilot_tools/bootstrap.sh
- [new `uploader.py` version](https://github.com/ArduPilot/ardupilot/commit/f6544ca25ab232407ec102b7a5adf0adca0f2062), which actually has a non-zero exit status when it fails
- relevant to https://github.com/bluerobotics/BlueOS-docker/issues/840#issuecomment-1136210399
> tools: ardupilot: bootstrap: update uploader hash

- core/frontend/src/components/autopilot/AutopilotManagerUpdater.vue
- core/frontend/src/components/autopilot/BoardChangeDialog.vue
- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/frontend/src/store/autopilot_manager.ts
- core/frontend/src/types/autopilot.ts
- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/flight_controller_detector/Detector.py
- core/services/ardupilot_manager/flight_controller_detector/board_identification.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/typedefs.py
This update has two main points:
- Allowing users in Pirate Mode to flash any connected board (and not just the running board)
- Allowing users in Pirate Mode to flash serial boards that are stuck in bootloader mode
The former is the one we were aiming, letting users that had problems updating their boards and are stuck in bootloader mode to get them back running.
This helps with #865 and #840 
@ES-Alexander please let me know if this fulfills what we were aiming (lettings users get their boards back running without using terminal or other tools).
PS: I left this as a draft as I'm rethinking a better way to handle the differentiation between real boards and bootloaders, both on backend and frontend.
> Improve firmware management

- core/Dockerfile
- core/frontend/src/components/video-manager/VideoManager.vue
- core/frontend/src/components/video-manager/VideoStream.vue
- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
- core/frontend/src/types/video.ts
- core/tools/install-static-binaries.sh
- core/tools/install-system-tools.sh
- core/tools/mavlink_camera_manager/bootstrap.sh
- [changelog](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.4.0)
- Does not enable the webrtc feature
- Allow use of others encoders such as YUYV and MJPEG in pirate mode
docker: patrickelectric/update_mavlink_camera_manager_3_4_0
> Update mavlink camera manager 3.4.0

- core/tools/scripts/bootstrap.sh
Using relative path actually is relying on having "/" as the current working directory, which ~will~ might not be the case in future blueos-base docker images (eg. we may choose to use /home/pi as the default login path).
> core: tools: scripts: bootstrap: Use absolute path for red-pill location.

- core/frontend/package.json
- core/frontend/src/components/wifi/WifiManager.vue
- core/frontend/src/components/wifi/WifiSettingsDialog.vue
- core/frontend/src/components/wifi/WifiUpdater.vue
- core/frontend/src/store/wifi.ts
- core/frontend/yarn.lock
- core/libs/commonwealth/commonwealth/utils/DHCPServerManager.py
- core/libs/commonwealth/commonwealth/utils/general.py
- core/services/beacon/default-settings.json
- core/services/wifi/Hotspot.py
- core/services/wifi/WifiManager.py
- core/services/wifi/main.py
- core/services/wifi/settings.py
- core/tools/blueos_startup_update/blueos_startup_update
- core/tools/hotspot/bootstrap.sh
- core/tools/install-system-tools.sh
~This branch had it development stalled for some months to focus on other priorities. I'm pushing it as it was.
Last time I've checked, it was already working, but had several code improvements to be made. Once the CI builds the image, I'm going to test it to confirm.
I will put some work to finish it in the next weeks.~
Hotspot is now working, in parallel with wifi-client-behavior.
The main use-case for this feature is for the user to be able to connect to the Raspberry board if cabled-ethernet is not working or no known network is nearby, and from the frontend to debug its board and/or connect to a known wifi network.
By default, the hotspot is enabled, and it also auto-starts itself whenever there's no connection to any known wifi network for more than the watchdog timeout. We call the …
> Add hotspot functionality

- core/frontend/src/views/NetworkTestView.vue
Make it clear that local tests are local (and unrelated to BlueOS's connection to the internet).
> core: frontend: NetworkTestView: explicitly local

- core/services/wifi/WifiManager.py
When a raspbian image is flashed, the wlan interface is not configured until it receives an initial request. If the interface is not configured, the hotspot does not work correctly. To force the initial configuration, we perform an initial scan.
Tested with a freshy-flashed image. Now working flawlessly.
Fix #1097
> wifi-manager: Perform initial scan by default

- core/services/versionchooser/setup.py
This is needed to fullfill the [installation requirements](https://github.com/bluerobotics/BlueOS-docker/runs/7622218531?check_suite_focus=true#step:7:6879). We (@Williangalvani) need to make sure this doesn't break anything (from semver, it should not).
> version-chooser: Allow for newer versions of `werkzeug`

- core/services/beacon/default-settings.json
Uses `blueos-hotspot.local` to prevent conflicts with wifi-client network.
> beacon: Change mdns for hotspot interface

- core/services/cable_guy/setup.py
- core/services/helper/setup.py
We are already using cloudflare for metro in ardupilot manager, version chooser and wifi
> core: services: cable_guy/helper: Use cloudflare over metroui cdn for consistency and stability

- core/frontend/src/components/beacon/BeaconTrayMenu.vue
- core/frontend/src/types/beacon.ts
- core/services/beacon/typedefs.py
Make sure they know this should not be their main connection, the same way we advertise it for client-wifi connections.
Fix #1106 
~(didn't test yet)~
> beacon: Warn users about usage of hotspot connection

- core/frontend/src/views/NetworkTestView.vue
`window.performance.now()` returns `ms` and not `us`
Fix #1114 
> core: frontend: NetworkTestView: Fix latency from us to ms

- core/services/helper/main.py
Fix #1115
- There is no reason to not cache it without timeout.
- There is no way for us to check where is the swagger website without probing the valid paths.
> core: services: helper: Cache detect_service output

- .github/workflows/test-and-deploy.yml
Just to have it showing as a number and not under a droplist in GitHub
Now:
Before:
> CI: test-and-deploy: Move python version from list to value

- core/tools/logviewer/bootstrap.sh
This updates the cesium Ion token, and it's required for the maps to work.
full changelog:
https://github.com/ArduPilot/UAVLogViewer/releases/tag/v0.9.9
~image coming soon to a docker hub near you.~
image (including #1136) is available at williangalvani/blueos-core:fixlogviewer2
> core: tools: logviewer: bump version to 0.9.9

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
- core/services/ardupilot_manager/mavlink_proxy/Endpoint.py
- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
- core/start-blueos-core
- core/tools/mavlink_camera_manager/bootstrap.sh
docker image: `joaoantoniocardoso/blueos-core:update-mavlink-camera-manager`
Summary:
- RTSP is working again
- WebRTC is working again
- Improved QGC integration: multiple streams are working with QGC
- Logging to daily-rotating files (`/var/logs/mavlink-camera-manager/.`)
> Update mavlink camera manager

- core/tools/hotspot/bootstrap.sh
- core/tools/linux2rest/bootstrap.sh
- core/tools/mavlink_camera_manager/bootstrap.sh
This PR Updates mavlink-camera-manager to [t3.9.0](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.9.0)
> Update mavlink camera manager to t3.9.0

- core/frontend/src/store/video.ts
From our tests it can take up to 2.5s.
Going to use 5s for worst case scenario.
Fix #1171
> core: frotnend: video: Increase timeout of reset settings

- core/Dockerfile
This should improve performance when the frontend is the only thing changed.
It makes the fronted stage use the current architecture, which doesn't change the final result, which is a bunch of html/js/css files
> core: use BUILDPLATFORM for building the frontend

- core/services/ardupilot_manager/firmware/FirmwareDownload.py
Current behavior was to raise, but that prevent firmware to be downloaded.
Core team agreed it's better to have one than to have nothing, so we go on with the first candidate and log a warning message about the problem.
This is experienced for ArduCopter firmware, since it has both "regular" and "heli" firmware available in the same repo.
Image building and testing is in progress.
Fix #1153
> ardupilot-manager: Send first found firmware candidate when multiple exist

- core/services/beacon/main.py
- core/services/beacon/settings.py
This makes sure that if something goes wrong while loading the settings, we still have beacon operating.
> core: beacon: revert to default settings if settings file fails to load

- core/services/helper/main.py
The goal here is to improve detection of Extensions, which sometimes get cached as an invalid service before they get up properly.
Not quite sure about this one. I Think the best thing to do would be to have a timeout. Say keep probing it for 1 minute, and then give up. but what if something takes longer than a minute to respond?
Also, what if something REALLY dislikes being probed?
> core: helper: only cache successful probes

- .github/workflows/test-and-deploy.yml
Can't use `uses` with run in the same `step`
Reference: https://github.com/bluerobotics/BlueOS-docker/actions/runs/3496835878
> github: test-and-deploy: Fix yaml

- core/frontend/src/types/autopilot/parameter-fetcher.ts
- core/frontend/src/views/ExtensionManagerView.vue
This helps Vue DevTools to cope with the parameters functionality, as the high number of mutations was making it freeze.
If we still don't have all the parameters download, this rate-limits store updates to at most one update every 300ms. after they are all loaded, the reate limiter is disabled.
The issue didn't seem to affect the production build, but made debugging anything in blueos frontend very painful
docker at williangalvani/blueos-core:ratelimit
> Add rate-limiting to parameter store

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> core: frontend: components: parameter-editor: Show 'None' over '0' when nothing is selected

- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
needs testing.
needs LOG_BACKEND to be set to enable MAVLINK backend
it seemed to create some 0 bytes files in my tests, but the correct ones are generated as well. we could do a routing to erase these empty files..
> core: ArdupilotManager: support streaming dataflash logs with mavlink-router

- core/frontend/vue.config.js
This allows us to see progress of docker pull operations in the dev server. previously, they were being held and outputted all at once at the end of the response.
based on https://github.com/webpack/webpack-dev-server/issues/1742#issuecomment-483970770
> core: frontend: dev-server: allow proxying chunked responses

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
A parameter such as `EK2_ENABLE` can have a value of `0`, and that's `DISABLE` option
> core: components: parameter-editor: Fix options with value 0

- .eslintrc.js
If that's not included, `yarn serve` just fails to find the json files.
> eslintrc: Add import/resolver to include json files

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
- core/frontend/src/store/autopilot.ts
- core/frontend/src/types/autopilot/parameter-fetcher.ts
- core/frontend/src/types/autopilot/parameter-table.ts
Should be merged after #1252 
- Tracks both parameter metadata and vehicle parameter.
- Use v-data-table loading object over our own.
https://user-images.githubusercontent.com/1215497/205342234-82695cf9-27ab-40fe-a4bb-7ad2f69f25b1.mov
> parameter-editor: Improve loading information

- install/README.md
- install/boards/bcm_27xx.sh
- install/boards/bcm_28xx.sh
- install/install.sh
Truncate can remove characters of files that does not have a line break.
Sed can add the text on the first line without problems.
Fix #1260 
> install: boards: Use sed over truncate to add cgroups

- core/frontend/src/components/system-information/SystemCondition.vue
- core/frontend/src/utils/helper_functions.ts
- core/frontend/src/views/ExtensionManagerView.vue
example user permissions:
```
{
"NetworkMode":"host",
"HostConfig":{
"CpuPeriod":100000,
"CpuQuota":20000,
"Memory":209715200,
"Privileged":true,
"NetworkMode":"host",
"CapAdd":[
"SYS_ADMIN",
"NET_ADMIN"
],
"Binds":[
"/var/lib/zerotier-one:/var/lib/zerotier-one"
],
"Devices":[
{
"PathOnHost":"/dev/net/tun",
"PathInContainer":"/dev/net/tun",
"CgroupPermissions":"rwm"
}
]
}
}
```
Example result:
> Show allowed CPU and Memory budget for extensions

- core/services/ardupilot_manager/setup.py
this could fix this issue where the aarch64 binary is indetified as "ARM" only:
> core: bump pyelftools to 0.28

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
- core/frontend/src/types/autopilot/parameter-table.ts
- core/frontend/src/types/autopilot/parameter.ts
- Display in scientific units when necessary
- Add units in main viewer and in editor
- Select custom when value does not exist in options once editor is open
- Select force when value is outside range once editor is open
- Deselect custom when value is a know open
- Deselect force when value goes back to range
- Fix reset of force and custom when editor closes
https://user-images.githubusercontent.com/1215497/206581777-d032feb3-d5a7-4bde-9785-33d5b8863ccf.mp4
> parameter editor: Move improvements

- core/frontend/src/components/logs/LogManager.vue
LogManager shows the wrong size and size only in MB, making it less friendly for the user.
Old LogManager:
Size information on file-browser:
New LogManager:
> core: frontend: components: LogManager: Fix size visualization

- core/frontend/src/components/mavlink-inspector/MavlinkInspector.vue
> core: frontend: components: MAVLinkInspector: Improve visualization of selected mavlink messages

- core/frontend/src/components/kraken/ExtensionModal.vue
- core/frontend/src/views/ExtensionManagerView.vue
Just trying to make things look a bit better:
before:
after:
> core: frontend: tweak extensions readme css

- core/tools/mavlink2rest/bootstrap.sh
New:
https://github.com/patrickelectric/mavlink2rest/releases/tag/t0.11.8
https://github.com/patrickelectric/mavlink2rest/releases/tag/t0.11.9
https://github.com/patrickelectric/mavlink2rest/releases/tag/t0.11.10
> core: tools: mavlink2rest: Update mavlink2rest to 0.11.10

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/setup.py
This means a gdb server will be opened on port 5555 for debugging. ardupilot doesn't start until a debugger is attached.
While I would like to have something in the GUI signalling that we are in debug mode, there is 0% chance that someone will randomly stumble upon a debug build of ardupilot and upload it not knowing what they are doing...
Depends on https://github.com/bluerobotics/companion-docker-base/pull/14
Fix #717
> ArdupilotManager: launch ardusub with gdbserver if debug symbols are present

- core/frontend/src/components/nmea-injector/NMEASocketCreationDialog.vue
`updating_serial_ports` doesn't even exist there.
> core: frontend: remove serial port stuff from nmea_injector

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
There is no need to allow different sorts, and the work to do it do not worth
> core: frontend: ParameterEditor: Sort only by name

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/setup.py
It is broken in master. It turned out that both debug and non-debug builds have debug symbols, but a VERY different amount of them.
> Fix debug symbols detection

- core/frontend/src/views/SystemInformationView.vue
> core: frontend: SystemInformationView: Move 'System Monitor' to second page

- core/frontend/src/components/nmea-injector/NMEASocketCreationDialog.vue
> core: frontend: NMEASocketCreationDialog: Add information about mavlink component

- core/frontend/src/types/autopilot/parameter-table.ts
This is required for loading the correct metadata for the parameter table
> core: frontend: ask for vehicletype in parameter-table.ts

- core/services/versionchooser/utils/dockerhub.py
We were getting `OCI manifest found, but accept header does not support OCI (Open Container Initiative) manifest` errors when trying to fetch latest master manifests. My guess is that we somehow are shipping the image (or at least the manifest) in a different container format now:
The error message doesn't look particularly good. but I'm happy to have the additional data in there
fix #1368 
fix #1379
potentially replaces #1384 
tested both in an older master with local changes, and current master with local changes. it seems to work fine:
solution was grabbed from https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/31127
> Add suport for OCI manifests

- core/frontend/src/store/autopilot.ts
A replace for #1395
As discussed on the dentist
> core: frontend: store: autopilot: Add getters for parameters

- core/tools/mavlink_camera_manager/bootstrap.sh
This minor version update fixes both the freezing streams when starting WebRTC streams, and the freezing WebRTC stream when we add more clients to the same stream. 
[Change log here](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.10.1)
> core: tools: mavlink-camera-manager: Update to t3.10.1.

- core/frontend/src/components/health/HealthTrayMenu.vue
Now its possible to click in individual icons to have specific information
> core: frontend: health: HealthTrayMenu: Break out icons to allow custom menus

- core/start-blueos-core
Logs should be under service folder
> core: start-companion-core: Fix log path for camera manager

- core/frontend/src/App.vue
- core/frontend/src/components/app/SettingsMenu.vue
- core/frontend/src/components/app/ThemeTrayMenu.vue
https://user-images.githubusercontent.com/1215497/217019788-864f8352-b723-450d-b73d-e931f7a753bc.mp4
> Add theme on top

- bootstrap/startup.json.default
- core/frontend/public/index.html
- core/frontend/vue.config.js
- core/tools/blueos_startup_update/blueos_startup_update
- core/tools/nginx/nginx.conf
Currently works with custom css files located in the host's [/home/pi/userdata/](http://blueos.local:7777/file-browser/files/home/pi/userdata/)user_style.css`
The screenshot uses these updated variables:
```
:root {
--v-primary-base: #dd8603 !important;
--v-info-base: #dd8603 !important;
}
```
The full list  (courtesy of somewhere in chrome's dev tools) is here:  (upload when chrome is happier)
I intend to use the same or a similar mechanism to allow overriding images/models.
> create "userdata" folder for allowing customizations

- core/frontend/src/router/index.ts
- core/frontend/src/views/PageNotFound.vue
> Add 404 on router

- .github/workflows/test-and-deploy.yml
The current version uses Node 12 that's deprecated. Ref: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> Move away from node 12

- .github/workflows/test-and-deploy.yml
set-output is deprecated.
Ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> github: ci: test-and-deploy: Use GITHUB_OUTPUT over set-output

- core/Dockerfile
- core/tools/filebrowser/bootstrap.sh
Have you ever had to tell users where to find some specific data in the filesystem?
Worry no more! With the new, revamped "shortcuts 2000", your path-finding days are over!
We now offer a revolutionary way of directing users to the correct folders:
And that is not all.  If you review it in the next 2 hours, you get it for absolutely FREE! that's right, "free" as in "free beer" AND "free" as in "freedom" !!!!11!!eleven!!
image at williangalvani/blueos-core:shortcutes
> core: create filesystem shortcutes/symlinks

- bootstrap/bootstrap/bootstrap.py
We don't really care what went wrong. if ANYTHING does go wrong, we need to revert to a safe config
> bootstrap: use broad exception when reading startup.json

- core/frontend/package.json
- core/frontend/src/components/kraken/InstalledExtensionCard.vue
- core/frontend/yarn.lock
Prevents the "Upgrade to xxx " button from showing to a lower version, in the case of the current one being pulled from the repo. (should we though?)
> Never go back

- core/frontend/src/App.vue
- core/frontend/src/components/app/VehicleRebootMenu.vue
- core/frontend/src/components/app/VehicleRebootRequiredTrayMenu.vue
- core/frontend/src/components/parameter-editor/ParameterEditor.vue
- core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
- core/frontend/src/store/autopilot.ts
- core/frontend/src/types/autopilot/parameter.ts
Move parameter dialog to its own component to be used in different places.
Also turns the `autopilot reboot` button to be global, to follow the user between the pages until it's rebooted. 
Fix #1471
> Dialog parameter

- core/frontend/src/App.vue
This is useful for extensions as cockpit that are a standalone application
> core: frontend: App: Force extensions that use new_page to open without BlueOS iframe

- core/frontend/src/components/system-information/NetworkCard.vue
IPv6 address should not be publicly available as mac
> core: frontend: components: NetworkCard: Blur IPv6 adress

- core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
Use autocomplete if the list of options is bigger than 10
Fix #1495
> core: frontend: components: ParameterEditorDialog: Use v-autocomplete for big list of options

- core/frontend/src/components/system-information/SystemCondition.vue
There is no easy way to do it for now using sysinfo library and update linux2rest, hopefully more time or something better may be possible in the future.
> core: frontend: components: SystemCondition: Filter out docker binds in disks

- core/frontend/src/components/video-manager/VideoStream.vue
> core: frontend: Change icon and tooltip for SDP URL copy button

- install/install.sh
This will make it clear if the size is lower than 1GB, the number will not be 0 or 1, but the size in MB, making it more clear.
> install: install: Move size from GB to MB

- core/Dockerfile
The changelog can be accessed [here](https://github.com/bluerobotics/blueos-docker-base/releases/tag/v0.0.8)
> core: Dockerfile: Use new blueos-base:v0.0.8

- install/boards/bcm_27xx.sh
We are having USB problems with cameras where they stop working with the old firmware / bootloader / VL085 firmware
> install: boards: bcm_27xx: Update firmware for raspbian

- bootstrap/bootstrap/bootstrap.py
From:
```
/bootstrap/bootstrap.py:175: UserWarning: Error trying to pull an upda
te image: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=patrick_1.0.2&fromImage=bluerobotics%2Fblueos-core: Not Found ("manifest for blu
erobotics/blueos-core:patrick_1.0.2 not found: manifest unknown: manifest unknown")
warn(f"Error trying to pull an update image: {error}")
```
> bootstrap: bootstrap: Revert to factory if getting NotFound error

- .github/workflows/docs-check.yml
Provides a fail indicator for PRs with the "docs-needed" label.
Process found at https://stackoverflow.com/a/71504928/15326510
~DO NOT MERGE until BlueOS-1.1 base docs have been published.~
> workflow: create docs-check

- core/frontend/src/types/autopilot/parameter.ts
> core: frontend: autopilot: parameter: Use hexadecimal to show DEV_ID

- core/frontend/src/components/system-information/Firmware.vue
- core/frontend/src/cosmos.ts
> Fix bootloader date format

- .github/workflows/test-and-deploy.yml
just creating a draft to check if CI finds some errors for us
> CI: build armv8 64bit images

- core/frontend/src/components/app/SettingsMenu.vue
There is no reason to wait only 4 seconds, we can wait longer since the calculation time is based on the amount of files that exist.
> core: frontend: SettingsMenu: Wait for log_folder_size longer

- .github/workflows/test-and-deploy.yml
Right now are using the same file name for both architectures, this PR use different names, fixing the problem when doing a release using the glob pattern.
> Fix artifacts names

- core/frontend/src/components/health/HealthTrayMenu.vue
- core/libs/commonwealth/commonwealth/mavlink_comm/MavlinkComm.py
- core/libs/commonwealth/commonwealth/mavlink_comm/VehicleManager.py
- core/libs/commonwealth/commonwealth/mavlink_comm/typedefs.py
This goes on the assumption that the vehicle is only one system with multiple components.
it relies on mavlink2rest to detect the most recent message received and locks on to that ID
Relevant to #1466
> Allow using system ids other than 1

- core/services/beacon/main.py
This deals with some edge cases where after a failure, some runners were just forgotten about and weren't retried
> core: beacon: only add runner to list after registering

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
- core/frontend/src/components/vehiclesetup/viewers/GenericViewer.vue
- core/frontend/src/components/vehiclesetup/viewers/VehicleViewer.vue
needs some cleaning up, and probably refactoring the the arm button into a component
tested with a servo in the pwm rail and 5v jumped to it
> core: frontend: Implement motor test 

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
Bigger title, space between each motor control
Set switch as red once armed
> core: frontend: vehiclesetup: PwmSetup: Improve ui

- core/frontend/src/App.vue
- core/frontend/src/components/wizard/Wizard.vue
- core/frontend/src/store/beacon.ts
- core/services/beacon/main.py
- core/services/beacon/settings.py
Needs ~~#1582~~ and #1585
Add wizard setup that opens on the first time that BlueOS shows
Sets vehicle name and mdns name to be used
> Add wizard

- core/services/bag_of_holding/main.py
Our services does not use space for settings names
> Fix bag settings folder name

- core/services/ardupilot_manager/setup.py
It's being overwritten by the following one
> core: services: ardupilot_manager: setup: Fix unnecessary download

- core/frontend/src/components/kraken/ExtensionCard.vue
> core: frontend: kraken: make images fit the available space

- core/tools/nginx/nginx.conf
> core: nginx: override CORS header for mavlink2rest

- core/services/kraken/kraken.py
> core: kraken: do not create user_permissions when updating an extension

- core/frontend/src/utils/helper_functions.ts
The hash inside the `g` field can have a variable size
> core: frontend: utils: helper_functions: Fix convertGitDescribeToUrl

- core/tools/mavlink_camera_manager/bootstrap.sh
* UDP latency from 192 to 128ms
* Reset now gently remove streams, which fixes the problem of not being able to create streams after calling the reset.
[Release notes](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.11.2)
> core: tools: mavlink-camera-manager: Update to t3.11.2.

- core/tools/mavlink_camera_manager/bootstrap.sh
* Reset behavior fixed: it now recreates the default streams as expected.
[Release notes](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.11.3)
> core: tools: mavlink-camera-manager: Update to t3.11.3.

- core/frontend/src/App.vue
Only show scroll when necessary.
Different from #1637, where scroll will be visible in cases where the content is full visible.
> core: frontend: App: Make scroll smart

- core/frontend/src/components/version-chooser/VersionChooser.vue
Not sure if it's too late to backport this, but it may help [people updating from old releases, if the remote isn't loading properly](https://discuss.bluerobotics.com/t/broken-link-to-githubs-ci-for-manual-upload/14108).
> core: version chooser: update outdated link

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/firmware/FirmwareInstall.py
- core/services/ardupilot_manager/flight_controller_detector/Detector.py
- core/services/ardupilot_manager/typedefs.py
With this small change, we can support running Ardupilot Linux-based firmwares for boards other than the Navigator.
This was motivated to support the Argonot system, from SymbyTech (a request from @DevinNorgarb).
The only downside for now is that when there's no firmware installed for that board, we will use the one we have stored for Navigator.
The PR is in draft mode until we confirm the sensors used to identify this board.
Fix #1623.
> Support non-navigator linux boards (initially Argonot)

- core/services/versionchooser/setup.py
The latest version 2.3 gets in conflict with connexion
> core: services: versionchooser: setup: Fix werkzeug version

- core/frontend/yarn.lock
Fixed:
```
error @achrinza/node-ipc@9.2.5: The engine "node" is incompatible with this module. Expected version "8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18". Got "19.9.0"                                                                                                
```
> core: frontend: yarn: Update to work with latest node version

- core/frontend/src/components/utils/PullProgress.vue
> core: frontend: components: PullProgress: Add minimum size to dialog

- core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
Simplify code and update new_value when flags change
Fix #1562
> core: frontend: components: ParameterEditorDialog: Fix bitflag edition

- core/frontend/src/views/MainView.vue
> Fix spacing on main view 

- core/frontend/src/views/MainView.vue
> core: frontend: views: MainView: Decrease title size to fix text wrap

- core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
> frontend: parameter-editor: Fix missing flag selection on editor

- core/frontend/src/components/wifi/ConnectionDialog.vue
- core/services/wifi/main.py
> Allow connecting to unsafe network wifi 

- core/services/helper/main.py
Events are deprecated, moving uvicorn to use our own loop
> core: services: helper: Fix periodic loop

- core/frontend/src/components/autopilot/AutopilotManagerUpdater.ts
- core/frontend/src/components/wifi/WifiManager.vue
- core/frontend/src/components/wizard/ActionStepper.vue
- core/frontend/src/components/wizard/RequireInternet.vue
- core/frontend/src/components/wizard/Wizard.vue
Allows wizard to request user to connect to internet and install firmware for current board
> Wizard: Configure boat firmware and support custom page configuration

- core/frontend/src/components/kraken/InstalledExtensionCard.vue
Previously, we used the second slash-separated path component instead of the last one for the image name.
This is incorrect as, e.g. in the below example. The name of the image identified by "docker.io/library/alpine" is "alpine", not "library"
> Show correct name of image for an installed extension

- core/frontend/src/components/autopilot/AutopilotManagerUpdater.ts
- core/frontend/src/components/wizard/Wizard.vue
- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/firmware/FirmwareManagement.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/settings.py
This will save the firmware downloaded during the wizard as the default fw in userdata.
we'll still fallback to a fw in the docker container
fix #1729 
image will be up at williangalvani/blueos-core : default_fw as soon as [this](https://github.com/Williangalvani/blueos-docker/actions/runs/5192546688/jobs/9362068931) finishes.
to test, make sure you are using a beta fw, then go through the wizard
after the wizard, you will have sub 4.1.0. switch to a beta again.
now click "restore default firmware" it should get you back to 4.1.0
> Set the default firmware during the wizard

- core/frontend/src/views/ExtensionManagerView.vue
> core: frontend: use flex containers for extensions store

- core/frontend/src/components/wizard/Wizard.vue
Skip is for the current session. Disable is until the next Wizard version change.
Not quire sure how I feel about this one 🤔
> core: frontend: wizard: add skip and disable options to wizard

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
select fields do not work with the 'required' keyword alone
> core: frontend: video streams: fix validation of select fields

- core/tools/mavlink_camera_manager/bootstrap.sh
Most important changes:
- Fix WebRTC SDP, allowing Redirect 4k RTSP sources to be used with WebRTC
- Fix wrong MAVLink ids, allowing (again) multiple streams with QGC
[Release notes](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.11.6)
> core: tools: mavlink-camera-manager: Update to t3.11.6.

- core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
> core: frontend: parameterEditorDialog: save when pressing enter

- core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
fix #1771 and a another bug where we had to click outside of the textfield for the save button to get enabled.
> Fix two bugs on ParameterEditorDialog

- core/frontend/src/components/autopilot/AutopilotManagerUpdater.ts
- core/frontend/src/components/parameter-editor/ParameterEditor.vue
- core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
- core/frontend/src/components/parameter-editor/ParameterLoader.vue
- core/frontend/src/components/vehiclesetup/Configure.vue
- core/frontend/src/components/vehiclesetup/overview/ParamSets.vue
- core/frontend/src/components/vehiclesetup/viewers/VehicleViewer.vue
- core/frontend/src/components/wizard/ActionStepper.vue
- core/frontend/src/components/wizard/DefaultParamLoader.vue
- core/frontend/src/components/wizard/RequireInternet.vue
- core/frontend/src/components/wizard/Wizard.vue
- core/frontend/src/libs/MAVLink2Rest/index.ts
- core/frontend/src/store/mavlink.ts
- core/frontend/src/types/autopilot.ts
- core/frontend/src/types/parameter_repository.d.ts
- core/frontend/src/views/VehicleSetupView.vue
This add defaults parameters for BlueROV2, BlueBoat120, and Sitl (rover/sub).
https://github.com/bluerobotics/BlueOS-docker/assets/4013804/0654cb48-e8c5-4858-8526-f6a403cdfa80
I opted to have individual sets of parameters. The trickiest thing is the Pixhawk Servo assignments, which changes between standard and heavy, while also being different than Navigator.
I believe this will be a lot easier to maintain than having multiple individual files, one for each possible combination.
We _could_  use a code like this to actually generate the parameter files, but I believe this is more meaningful.
This does not try to fetch parameters from an online repository, though we _could_ do that later if we judge it necessary.
We could also have "maximum supported version" of firmware for …
> Add interface for loading parameters

- core/frontend/src/components/autopilot/AutopilotManagerUpdater.ts
- core/frontend/src/components/wizard/DefaultParamLoader.vue
- core/frontend/src/components/wizard/Wizard.vue
- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/firmware/FirmwareManagement.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/typedefs.py
- core/tools/ardupilot_tools/bootstrap.sh
supports injecting them into the .apj firmware for stm32 boards, and creating a .params file in userdata for linux
https://github.com/bluerobotics/BlueOS-docker/assets/4013804/2a471371-c7af-4c92-9682-41fe34638f10
ps: I just increased the width of the select so the full label shows up
additional fix for #1734
this can be tested by running the wizard and chosing a default set, and then resetting the parameters to firmware defaults in qgc and checking if the configuration remains (easier to see frame type in the 3d viewer, for sub at least)
fix #1720 
fix #1722 
fix #1726
> Allow embedding parameters into firmware

- core/frontend/src/components/kraken/InstalledExtensionCard.vue
The large overlay blocked the buttons, which means it blocked event the "logs" button when something went wrong.
before:
later:
> core: frontend: extension manager: show spinner in bars instead of as a large overlay

- core/Dockerfile
Basically GStreamer stuff: [release log](https://github.com/bluerobotics/blueos-docker-base/releases/tag/v0.0.9)
> core: Dockerfile: Use new blueos-base:v0.0.9

- core/frontend/src/components/wizard/RequireInternet.vue
- core/frontend/src/components/wizard/Wizard.vue
> core: frontend: wizard: move wifi connection to first step of wizard

- bootstrap/bootstrap/bootstrap.py
- Fixes a bug where an effectively broken  image (williangalvani/blueos-core:fixotg) was not reverted to factory.
- Reduces the verbosity
- increases core timeout to 5 minutes, as that is a last-resort fix anyway and we REALLY dont want false positives.
> Bootstrap tweaks

- bootstrap/bootstrap/bootstrap.py
I woke up to this in the morning after setting an invalid image last night:
> bootstrap: bugfix: reboot after ressetting to defaults

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
Fix https://github.com/bluerobotics/BlueOS-docker/issues/1815
> core: frontend: ParameterEditor: Empty parameter file entry before the menu shows

- core/frontend/src/components/wizard/Wizard.vue
Usually Start / Continue buttons are on the right, and cancel on the left
> core: frontend: components: wizard: Move 'start' button the the right side

- core/frontend/src/views/ExtensionView.vue
~needs testing~ it seems fine on my end, but more testing is welcome
williangalvani/blueos-core:lock_port
> core: frontend: lock in to detected port for extensions

- core/services/helper/main.py
Most of the CPU was spent inside the HTTP requests done by `aiohttp` and `request`. By replacing them with the low-level `http.client`, both the speed and CPU usage were improved.
Closes #1855 
---
All development data and tools can be accessed [here](https://github.com/joaoantoniocardoso/BlueOS-docker/tree/new_helper_dev/core/services/helper/dev_benchmark)
By doing several runs of the services, the port scanning is not idempotent, meaning that the list of available services can differ from one call to the other.
After analysis, it turns out that the only service that has different outputs is the Ping service (at port `9110`): sometimes it refuses to answer. Increasing the timeouts of the requests of the port_scan, the problem happens less.
Apart from this service, if the skipped ports …
> Optimize helper

- core/tools/blueos_startup_update/blueos_startup_update
lesson learned: the order of the elements of a set is not deterministic.
Closes #1807
> Fix core: tools: blueos_startup_update: Make the order of the configs deterministic

- bootstrap/bootstrap/bootstrap.py
- bootstrap/test_bootstrap.py
- core/services/helper/main.py
not tested yet, but a docker is up at  williangalvani/blueos-bootstrap:addreturn
> bootstrap: add missing 'return False'  in is_running()

- bootstrap/test_bootstrap.py
no functional changes, just covering more cases with testing,
> bootstrap: improve tests to test timeout detection and restarting

- bootstrap/startup.json.default
- core/frontend/src/components/app/DnsConfigurationMenu.vue
- core/frontend/src/components/app/InternetTrayMenu.vue
- core/frontend/src/components/app/NetworkInterfaceMenu.vue
- core/frontend/src/components/app/NetworkInterfacePriorityMenu.vue
- core/services/cable_guy/api/dns.py
- core/services/cable_guy/api/manager.py
- core/services/cable_guy/main.py
- core/start-blueos-core
- core/tools/blueos_startup_update/blueos_startup_update
Closes #1871
---
https://github.com/bluerobotics/BlueOS/assets/5920286/73d7bdea-59fd-43c6-a3dc-9e418c6197cc
> Add dns config

- core/frontend/src/components/system-information/NetworkCard.vue
IPv6 appears with `:` and not only with `::`
> core: frontend: components: NetworkCard: Fix IPv6 identification

- bootstrap/startup.json.default
master is throwing 
```
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 33 column 13 (char 922)Starting 
```
when trying to rever to factory.
> Fix bootstrap defaults file

- core/frontend/src/App.vue
- core/frontend/src/components/version-chooser/VersionCard.vue
- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/types/frontend_services.ts
- core/frontend/src/types/version-chooser.ts
- core/frontend/src/utils/version_chooser.ts
- core/services/versionchooser/main.py
- core/services/versionchooser/openapi/versionchooser.yaml
- core/services/versionchooser/utils/chooser.py
Fix #1510 
The button is only visible when the remote is the same as `bluerobotics`, and it'll only update to the version of the current BlueOS running.
> core: services: versionchooser: Allow updating bootstrap

- core/services/wifi/main.py
There is a case where the same network can be stored multiple times on the network service, this ensure that when the user remove the network, it'll remove all occurrence of the same network. We should move the service to use bssid over ssid to avoid such problems in the future;
```
Saved networks:
networkid  ssid        bssid    flags
-----------  ----------  -------  ---------
0  PATRICK_2G  any
1  PatrickG    any      [CURRENT]
2  PATRICK_2G  any
```
PS: I got in a point where the same network showed 7 times
> core: services: wifi: Remove all wifis with same ssid in database

- core/frontend/src/views/ExtensionView.vue
should fix #1907 
the idea here is that the query makes the browser think "this could be a different page" and not use a cached version.
> core: frontend: add cache-busting

- core/services/beacon/settings.py
Closes #1917 
The settings expect the Interfaces to be:
```JSON
{
"name": "uap0",
"domain_names": ["blueos-hotspot"],
"advertise": ["_http"],
"ip": "ips[0]"
}
```
`as_dict` is not implemented in JsonObject, but `JsonObject`'s `._data` is what we need:
> core: services: beacon: Fix V2->V3 settings migration

- core/services/beacon/default-settings.json
Make it easy to configure softwares to connect on cable by default.
> core: services: beacon: Add blueos-ethernet for beacon

- core/frontend/src/App.vue
request by @ES-Alexander
Makes sense to me
> core: frontend: move internet icon to the left of the wifi icon

- core/frontend/src/components/utils/BrIframe.vue
Fix #1930 
needs testing, waiting for the image to build
thanks @rafaellehmkuhl for the help finding the [issue](https://stackoverflow.com/questions/21025319/iframe-creates-extra-space-below#:~:text=The%20iframe%20element%20is%20an,bottom%3B%20to%20the%20iframe%20element.&text=The%20easiest%20way%20to%20do,%22%22%20in%20the%20iframe%20params)
> core: frontend: add display:block to BrIframe

- core/tools/mavlink_camera_manager/bootstrap.sh
Most important changes:
- Fix untreated latency messages, which make the latency to be recalculated during the stream.
- Fix RTSP hot reload.
[Release notes](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.12.1)
> core: tools: mavlink-camera-manager: Update to t3.12.1

- core/frontend/src/libs/MAVLink2Rest/MessageID.ts
> core: frontend: mavlink2rest: Add missing HEARTBEAT message id

- core/services/helper/main.py
Fix https://github.com/bluerobotics/BlueOS/issues/1965
The current architecture is not working with port 80, HTTP. So the code was changed to support 443, HTTPS.
> Fix telemetry system

- core/tools/blueos_startup_update/blueos_startup_update
The default is Check=True.
Check=True raises an exception when the return code is not zero (such as if the password was changed), that means we never actually return False. instead the script crashes and BlueOS is no more.
> core: blueos_startup_update: set check=False when testing run_command()

- core/frontend/src/components/app/NetworkInterfacePriorityMenu.vue
- core/services/cable_guy/api/manager.py
- core/services/cable_guy/main.py
Fix #1539
Right now to have it working it's required to do a system reboot.
Doing dhcpcd service restart breaks our wpa_supplicant connection. #1958 was an attempt to fix that.
> core: services: cable_guy: Move interface priority from ipr to dhcpcd

- core/frontend/src/components/speedtest/NetworkSpeedTest.vue
Since we are going to support boats and more vehicles, it's hard to have results for each one based one
now:
Before:
Fix #1977
> core: frontend: NetworkSpeedTest: Remove network result status

- core/Dockerfile
[Release log](https://github.com/bluerobotics/blueos-docker-base/releases/tag/v.0.0.10)
> core: Dockerfile: Use new blueos-base:v0.0.10

- bootstrap/startup.json.default
- core/libs/commonwealth/commonwealth/utils/commands.py
- core/services/commander/main.py
- core/tools/blueos_startup_update/blueos_startup_update
- core/tools/scripts/red-pill
This adds the mount  `/home/pi/.ssh` into core.
if an id_rsa file already exists, it is used. if not, we create a new one.
we then switch commander to use the ssh key instead of the password.
The old sshpass behavior is kept as a fallback, as some things (cough blueos_startup_update) run before commander does the ssh setup.
helps #854 and #952
> Switch to using an ssh key for accessing the host computer

- core/services/versionchooser/utils/chooser.py
This fix the format of the warning message
How python linter works ? Are they valid ? Do they exist ? Do they work ?
One day we will know. 
Tested
> core: services: versionchooser: chooser: Fix print format

- core/start-blueos-core
> core: try to create a new tmux session if user_terminal does not exist

- core/services/ping/ping1d_mavlink.py
raised here: https://github.com/bluerobotics/BlueOS/pull/1940/files#r1306488880
> core: ping: fix typo in mavlink driver

- core/frontend/src/components/app/PowerMenu.vue
> core: frontend: add autopilot restart button to power menu

- core/tools/linux2rest/bootstrap.sh
Reverts bluerobotics/BlueOS#2056
0.4.8 appears to have problems with cpu frequency and temperature sensor
> Revert "core: tools: linux2rest: Use latest version 0.4.8 <- 0.4.6"

- install/install.sh
from: https://discuss.bluerobotics.com/t/how-to-install-blueos-on-a-raspberry-pi-2/14903
> install: Check for rfkill before running it

- .github/workflows/test-and-deploy.yml
- core/Dockerfile
From the helper:
```
--always
Show uniquely abbreviated commit object as fallback.
```
With that, people that fork the project will not be obligated to push a tag or something for the build to work, the hash will be used as fallback.
> core: Use always in git describe

- install/install.sh
As a follow-up from #2083, based on [systemd](https://systemd.io/BUILDING_IMAGES/) we should also remove the random seeds.
> install: remove random-seeds for a safer build

- bootstrap/startup.json.default
- core/Dockerfile
- core/tools/blueos_startup_update/blueos_startup_update
This PR able blueos-core to access /usr/blueos/extensions folder.
- Resolves #2003
- Enables the use of the standard discussed in #1640
> Folder extensions

- .github/workflows/test-and-deploy.yml
- core/Dockerfile
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
- core/services/ardupilot_manager/mavlink_proxy/MAVP2P.py
- core/services/ardupilot_manager/mavlink_proxy/Manager.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
- core/tools/install-static-binaries.sh
- core/tools/mavp2p/bootstrap.sh
Should helps #2070 
How to test:
Terminal -> `mv /usr/bin/mavlink-routerd /usr/bin/mavlink-routerd2`
Go to `autopilot` tmux
Restart the service
> core: tools: mavp2p: Add first version

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/settings.py
- core/services/ardupilot_manager/setup.py
- core/services/install-services.sh
without this, all SITL instances try to use the "vectored" sub model, which doesn't work great with rover(and others) code.
fix #2094, we'd still need a ui update though
> core: ArdupilotManager: allow setting the SITL frame

- .hooks/pre-push
- core/services/nmea_injector/nmea_injector/tests/test_TrafficController.py
the parallelism is causing some tests to flap, this is my latest attempt at fixing them.
it can be tested with `for i in {1..50}; do pipenv run pytest -n 40; done`
this:
- adds missing mavp2p install
- make router tests use different ports
- update nmea-injector tests to so it both waits for udp ports to be free before using them, and uses a fake filesystem for the settings file
> Fix flapping tests

- core/frontend/src/App.vue
> core: frontend: remove left-over mentions of 'service-scanner' component

- core/services/install-services.sh
- core/services/major_tom/main.py
- core/services/major_tom/setup.py
- core/services/major_tom/src/core.py
- core/services/major_tom/src/metrics.py
- core/services/major_tom/src/typedefs.py
- core/start-blueos-core
This creates Major Tom, again. The code is mostly by @voorloopnul 
This leverages on loguru to store and rotate the data.
> Major Tom 2:  A missão

- core/frontend/vite.config.js
> core: frontend: vite.config: Remove selfHandleResponse

- core/tools/mavlink_camera_manager/bootstrap.sh
The most relevant updates for BlueOS here are:
* Thread leaks related to WebRTC got fixed, improving stability when working with Cockpit and 3rd-party WebRTC software.
* The MAVLink part was rewritten, getting rid of the most common error in the logs (the would-block errors)
[Full change log here](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.12.2).
> core: tools: mavlink-camera-manager: Update to t3.12.2

- bootstrap/startup.json.default
- core/Dockerfile
- core/tools/blueos_startup_update/blueos_startup_update
> Allow blueos to use binaries on the host computer by default

- pyproject.toml
It's currently giving wrong error messages
> pyproject: Fix black version

- core/services/ardupilot_manager/main.py
> core: autopilot manager: bump memory limit to 200mb

- core/services/ardupilot_manager/flight_controller_detector/board_identification.py
[Some Pixhawk boards use FMUv3](https://discuss.ardupilot.org/t/determining-pixhawk-fmu-version/54312).
I'm hopeful this would avoid issues like [this one](https://discuss.bluerobotics.com/t/pixhawk-1-compatible-board-2-4-8-could-not-load-firmware-file-for-validation/15259), but haven't actually confirmed to make sure.
> core: ardupilot-manager: improve Pixhawk support

- core/tools/mavlink_camera_manager/bootstrap.sh
The main fix is a freezing that happens when recreating streams, especially when dealing with multiple streams, introduced on t3.12.2.
[Full change log here](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.12.3).
> core: tools: mavlink-camera-manager: Update to t3.12.3

- install/install.sh
If /etc/dhcpd.conf didn't exist, this would crash with "sed: can't read /etc/dhcpcd.conf: No such file or directory".
Prevents a crash of the install script when installing on top of a clean install of Raspberry Pi OS.
> Don't modify /etc/dhcpd.conf if it does not exist

- core/tools/nginx/cors.conf
- core/tools/nginx/nginx.conf
This patch allows external applications, like Cockpit, to use the service to store configuration data.
> core: bag-of-holdings: Disable CORS policy

- core/frontend/src/components/kraken/InstalledExtensionCard.vue
- core/frontend/src/views/ExtensionManagerView.vue
> core: frontend: extensions manager: use flex container to display extension cards

- core/frontend/src/components/kraken/InstalledExtensionCard.vue
> core: frontend: Extensions Manager: fix buttons 'escaping' extension cards

- core/tools/mavlink2rest/bootstrap.sh
Change logs:
- https://github.com/mavlink/mavlink2rest/releases/tag/t0.11.18
- https://github.com/mavlink/mavlink2rest/releases/tag/t0.11.17
- https://github.com/mavlink/mavlink2rest/releases/tag/t0.11.16
- https://github.com/mavlink/mavlink2rest/releases/tag/t0.11.15
- https://github.com/mavlink/mavlink2rest/releases/tag/t0.11.14
> BlueOS: Update to use mavlink2rest to 0.11.18

- core/services/ardupilot_manager/main.py
it needs to be defined after we declare everything else as a versioned api.
fix #2220
> core: frontend: fix ardupilotmanager "/" endpoint

- .hooks/pre-push
> CI: pre-push-hooks: use xargs syntax compatible with both Linux and Macos

- core/libs/commonwealth/commonwealth/mavlink_comm/MavlinkComm.py
Fixes another datetime comparison issue
> core: commonwealth: drop tzinfo injection

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
- core/frontend/src/store/mavlink.ts
- core/frontend/src/utils/mavlink.ts
> Create identified messages field in store, use it in pwmsetup

- core/frontend/package.json
- core/frontend/src/components/autopilot/EndpointManager.vue
`--fix` in package.json made our ci run in "fix" mode, which means it was not actually checking for linting issues (it always returned 0).
> Fix linting

- core/frontend/src/components/bridges/BridgeCreationDialog.vue
- core/frontend/src/types/system-information/serial.ts
- core/services/bridget/bridget.py
This also makes the option not-selectable
Also switches to linux2rest for fetching ports, to fix #2238 
fix #2197
> Bridget: check if ports are in use by autopilot when creating a new bridge

- bootstrap/bootstrap/setup.py
fixes an issue with latest websocket-client (which we don't even use afaik)
> bootstrap: lock all dependencies

- core/services/helper/main.py
> core: helper: bump memory use limit to 200mb

- bootstrap/bootstrap/bootstrap.py
- bootstrap/test_bootstrap.py
`time.time()` use system clock to return current time. If the system time changes while in operation, with the timezone or connecting to the internet NTP server, our delta calculation will be wrong.
This pr uses `time.monotonic()` that:
> Return the value (in fractional seconds) of a monotonic clock, i.e. a clock that cannot go backwards. The clock is not affected by system clock updates. The reference point of the returned value is undefined, so that only the difference between the results of two calls is valid.
Fix #2260 #2248 #2105 
Detected from Tony log:
```
2023-12-07 08:16:14.876 | INFO     | bootstrap.bootstrap:start:180 - Starting bluerobotics/blueos-core
2023-12-07 08:16:16.935 | INFO     | bootstrap.bootstrap:start:197 - core (bluerobotics/blueos-core:1.1.1) started
2023-12-07 …
```
> bootstrap: Fix delta time calculation using monotonic clock

- core/frontend/src/views/FileBrowserView.vue
- core/frontend/src/views/TerminalView.vue
This makes it so we don't rely on nginx rewrite directives to reach the service. this fixes an issue when serving blueos from non-standard ports
> core: frontend: update some service paths

- core/frontend/src/App.vue
- core/frontend/src/types/helper.ts
- core/services/helper/main.py
This allows services to dynamically change their query arguments
I used it for setting mainlink and stun urls for cockpit, for example. I could just update register_service at start
> ServiceMetadata: add extra query

- core/Dockerfile
- core/libs/install-libs.sh
- core/services/install-services.sh
For a faster build.
This replaces "setup.py install" with "pip install", which will use the additional index-url.
it also stops installing pre-requisites when we don't need to build anything.
> core: do not compile unnecessarily

- core/Dockerfile
- core/libs/install-libs.sh
- core/services/beacon/setup.py
- core/services/bridget/setup.py
- core/services/commander/setup.py
- core/services/helper/setup.py
- core/services/install-services.sh
- core/services/kraken/setup.py
- core/services/ping/setup.py
- core/services/versionchooser/setup.py
- core/services/wifi/setup.py
- pyproject.toml
Current python (3.7) is not supported anymore, we need to update
From: #2256
> 1.1: core: Update to use a newer python version and base image

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
- core/frontend/src/components/vehiclesetup/overview/LightsInfo.vue
- core/frontend/src/components/vehiclesetup/viewers/GenericViewer.vue
Found this issue while trying to adjust some stuff and it wasn't working properly.
Cross-referenced with [the ArduSub RC Input docs](https://www.ardusub.com/developers/rc-input-and-output.html#rc-inputs) and realised the BlueOS ones were off by one.
> core: vehicle-setup: fix ArduSub lights mappings

- deploy/pimod/blueos.Pifile
it is not set in pimod who knows why
passing job here:
https://github.com/Williangalvani/blueos-docker/actions/runs/7416124592/job/20181038839
> CI: specify pi user on pimod

- core/start-blueos-core
this can be used with a command line such as
```
docker run --net=host -e "BLUEOS_DISABLE_SERVICES=cable_guy,beacon,kraken,wifi,bridget,commander,nmea_injector,iperf3,versionchooser,ping,log_zipper" --rm -it williangalvani/blueos-docker:individual_services
```
This makes it safer to run the dockers in x86 environments without messing up your networking and whatnot
> core: allow disabling services using environment variables

- core/tools/mavlink_camera_manager/bootstrap.sh
The main fixes are related to stream recreation crashes and MAVLink thread leaks.
[Full change log here](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.12.4).
> core: tools: mavlink-camera-manager: Update to t3.12.4

- core/services/commander/main.py
- core/start-blueos-core
Once the system gets in a critical state where the disk is full, it gets in a condition that recover is almost impossible. The system is unstable, the backend services and frontend may not work or be available for the user to recover at all. As a last resource, we delete BlueOS logs if the filesystem. 
Fix https://github.com/bluerobotics/BlueOS/issues/2323
> Try to recover the system if available size in critical

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
should fix #2206 
needs testing
> core: frontend: do not update motors when blueos is not in focus

- core/frontend/src/components/vehiclesetup/Configure.vue
This is the base for implementing all the sensor calibrations and peripherals setup. I'm opening this PR so we could parallelize some of the tasks at hand.
> core: frontend: split vehicle setup configurations

- core/frontend/src/utils/mavlink_prettifier.ts
> Improve mavlink inspector

- core/frontend/src/components/vehiclesetup/overview/OnboardSensors.vue
Sensor may contain calibration for the sensor itself and also for the termal sensor on it.
This improves the interface to provide such information on the ui in a friendly way.
> Improve calibration  information

- core/frontend/src/components/vehiclesetup/overview/OnboardSensors.vue
- core/frontend/src/store/mavlink.ts
- MAVLink use filter as a regex argument, we should use the messages names that we receive over the regex as key for the structure
- setMessageRefreshRate accepts a regex, not a literal. We need to enforce the string that we want using ^..$
This PR:
Master:
> Fix mavlink updateMessage usage  and barometer data

- core/services/bag_of_holding/main.py
Till now, one could only pass dicts/objects, limiting functionality.
Fix #2340
> core: services: bag of holdings: Allow using primitives on set operations

- core/frontend/src/components/version-chooser/VersionChooser.vue
From a friendly stackoverflow:
> In most browsers, you can make your browser display values previously entered in input fields by giving a name to the input.
> core: frontend: components: version-chooser: Allow browsers to save repository history

- core/services/ping/pingmanager.py
Hopefully fixes #1200 (or at least significantly reduces the likelihood of it).
**Details:**
- ⚠️ Untested
- should be testable at `esalexander/blueos-core`, `:ping-fix-attempt` (in the BlueOS Version Chooser)
- Uses the approach I suggested [here](https://github.com/bluerobotics/BlueOS/issues/1200#issuecomment-1914132647)
- It would be fully robust to also/instead regularly check for duplicated ports in the drivers (and restart them as necessary), but that seems excessive to me, and more involved to program and test
- Ideally this code should also stop treating a port as being connected to once the connection is established, but that seems like extra effort for minimal gain (as far as I'm aware it's not important for the ports to be consistently the same, so as long as unique ones get …
> core: services: ping: minimise port duplication races

- .hooks/pre-push
We should run the linters first and the tests later
> hooks: pre-push: Move pytest to run after linters

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
The main problem here is that `should_run` was not set as False on the start of the function, resulting on `auto_restart_autopilot` to conflict with the firmware installation procedure.
> Fix conflict between kill_autopilot and auto_restart_autopilot

- core/frontend/src/App.vue
- core/frontend/src/types/helper.ts
- core/services/helper/main.py
some system go a long way trying to prevent being embedded into iframes. or are just plainly badly designed.
My router is an example. it does something with window.top.
This should also avoid other iframe related issues that I don't quite remember right now.
This can be tested with the `iframes` tag of the blueos-proxy extension
> Allow extension links to avoid iframes

- core/services/ardupilot_manager/main.py
Fix error message from raise_lock
> core: services: ardupilot_manager: main: Turn raise_lock generic

- core/tools/mavlink_camera_manager/bootstrap.sh
Apart from small crash and deadlock fixes, we now have arm64 (aarch64) binary releases, and WebRTC's STUN configuration via CLI.
[Full change log here](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.12.5).
> core: tools: mavlink-camera-manager: Update to t3.12.5

- core/frontend/src/components/vehiclesetup/Configure.vue
- core/frontend/src/components/vehiclesetup/configuration/lights.vue
> Create configuration page for lights

- core/start-blueos-core
- core/tools/mavlink_camera_manager/bootstrap.sh
Overall:
* MCM is now using the MAVLink System ID from the BlueOS system.
* Some improvements regarding GStreamer pipelines and Signalling server.
* Several Dependencies were updated.
[Full change log here](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.12.6).
> core: tools: mavlink-camera-manager: Update to t3.12.6 + Pass MAVLink System ID to MCM

- core/frontend/src/components/wizard/ActionStepper.vue
- core/frontend/src/components/wizard/Wizard.vue
It was weird to show the loading icon while the user does not click in start.
This is fixed by adding a new variable to control the started state.
> core: frontend: components: wizard: Fix action step state to not show as loading when apply is not clicked

- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
- core/tools/mavlink_router/bootstrap.sh
Alternative to #2385, it removes the tlog since it can result in some running problems
> Use official mavlink router 2

- core/services/ardupilot_manager/main.py
- core/services/bag_of_holding/main.py
- core/services/beacon/main.py
- core/services/bridget/main.py
- core/services/cable_guy/main.py
- core/services/commander/main.py
- core/services/kraken/main.py
- core/services/log_zipper/main.py
- core/services/nmea_injector/nmea_injector/main.py
- core/services/pardal/main.py
- core/services/ping/main.py
- core/services/versionchooser/main.py
- core/services/wifi/main.py
This only limits virtual memory:
https://linux.die.net/man/2/setrlimit#:~:text=RLIMIT_AS,resource%20is%20unlimited.
on top of it, it is also redundant with the ulimit limiter at [run-service.sh](https://github.com/bluerobotics/BlueOS/blob/master/core/run-service.sh)
> core: services: stop using python-based memory limiting

- core/frontend/src/components/video-manager/VideoThumbnail.vue
A problem on the video page is that mostly of the time is showing the fetching animation over showing the thumbnail itself.
The PR changes the logic to show the last thumbnail, and only show the fetching animation when a thumbnail is not available.
> frontend: components: VideoThumbnail: Show last thumbnail over fetching animation

- core/start-blueos-core
When setting up multiple cameras, GStreamer may reserve excessive memory, even if it's not fully utilized. This memory allocation is causing issues when multiple cameras are in use.. According to João, we shouldbe fine if we remove this limit.
> core: start-blueos-core: Remove memory limit for video manager

- core/tools/mavlink_camera_manager/bootstrap.sh
The relevant parts:
- Fixes MAVLink disconnection when a parsing error happens.
- Disabled Tracy (some additional probing threads were added on the last version, we've done a downgrade to avoid having them)
[Full change log here](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.12.7).
> core: tools: mavlink-camera-manager: Update to t3.12.7

- core/services/ardupilot_manager/firmware/test_FirmwareDownload.py
This fix CI and is a blocker for our open PRs.
> core: services: ardupilot_manager: firmware: test: Update number of firmwares

- core/frontend/src/components/beacon/BeaconTrayMenu.vue
* Adds a double check for check in `is_connected_to_wifi` potentially avoid unexpected behavior where both wired and wireless interfaces could have the same IP
* Change computed property `wireless_interface_domains` to instead of checking for interfaces with type different than WIRED to consider only WIFI and HOTSPOT as Wireless interfaces, since usb interfaces currently holds type unknown and would be classified as Wireless
Probably linked to #2362
> frontend: Beacon: Add double check for wireless network

- core/services/beacon/main.py
- core/services/beacon/typedefs.py
Add a new interface type in beacon to avoid USB interfaces to get listed as UNKNOWN interface type and change to use guess_from_name in set_hostname instead of replicating the same logic.
Probably linked to #2274
> core: services: Fix USB not being listed in Beacon

- core/tools/mavlink_camera_manager/bootstrap.sh
* src: stream: pipeline: Fix wrong frame duration
* src: stream: rtsp: shmsrc needs to do-timestamp
[Full change log here](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.12.8).
> core: tools: mavlink-camera-manager: Update to t3.12.8

- core/frontend/src/one-more-time.ts
* Add delay functionality between calls in one more time lib
> core: frontend: Add delay in one-more-time

- core/tools/mavlink_camera_manager/bootstrap.sh
The RTSP was still not fixed on the Raspberry Pi (which has an older GStreamer):
* src: stream: rtsp: shmsrc needs to wait for connection
Full Changelog: https://github.com/mavlink/mavlink-camera-manager/compare/t3.12.8...t3.12.9
> core: tools: mavlink-camera-manager: Update to t3.12.9

- core/frontend/src/components/ethernet/AddressDeletionDialog.vue
- core/frontend/src/components/ethernet/InterfaceCard.vue
- core/frontend/src/components/wifi/DisconnectionDialog.vue
Add the check for when the user is trying to delete the IP being used to connect to BlueOS or when trying to delete the last IP of some interface.
Closes #2406
> Warn users when deleting current IP being used or the last interface IP

- core/frontend/src/components/wizard/Wizard.vue
> [Wizard] Fix return button

- core/frontend/src/components/beacon/BeaconTrayMenu.vue
- core/frontend/src/components/video-manager/VideoDiagnosticHelper.vue
- core/frontend/src/types/beacon.ts
This update enhances how BeaconTrayMenu reports the connection methods to BlueOS, introducing proper report for unknown interfaces and adding USB as a recognized type, reflecting beacon's expanded listings.
Related to #2198
> Enhancement Network Connection Detection in BeaconTray

- core/frontend/src/components/nmea-injector/NMEAInjector.vue
- core/frontend/src/one-more-time.ts
This add a delay logic to avoid fast appearances from the loading component causing a flickering on the UI
Fixes #2422
> Fix flickering problem in NMEA injector page

- core/frontend/src/components/vehiclesetup/overview/ParamSets.vue
https://github.com/bluerobotics/BlueOS/assets/4013804/10e9d1fb-020d-4e5a-a458-7abc96faed27
fix #2429
> Add button for resetting parameters to firmware defaults

- core/services/versionchooser/utils/chooser.py
> Add force tag when deleting images in version chooser

- core/frontend/src/components/system-information/SystemCondition.vue
The API can return CPU or cpu_thermal temp1.
To avoid that we are just going to match with cpu.
> core: frontend: components: SystemCondition: Improve temperature code

- core/frontend/src/components/parameter-editor/ParameterLoader.vue
- core/frontend/src/components/vehiclesetup/overview/ParamSets.vue
Change to use correct parameters values and units instead of just showing the raw enumeration value
Closes #2447
> Correct parameters name in ParameterLoader

- core/frontend/src/components/vehiclesetup/Configure.vue
- core/frontend/src/components/vehiclesetup/calibration.ts
- core/frontend/src/components/vehiclesetup/overview/BaroCalib.vue
> Add first calibration abstraction

- core/frontend/src/components/wizard/DefaultParamLoader.vue
- core/frontend/src/components/wizard/ScriptLoader.vue
- core/frontend/src/components/wizard/Wizard.vue
- core/frontend/src/libs/filebrowser.ts
Needs more testing, but looking good so far. I'll review it tomorrow
>  Scripts on Wizard

- core/frontend/src/App.vue
> core: frontend: App: Fix v-stepper disappearing when the screen width is small

- core/start-blueos-core
- core/tools/linux2rest/bootstrap.sh
This new version follows the same log structure as mavlink-camera-manager and also allows the user to log custom system information
> core: tools: linux2rest: Update to v0.5.4

- core/services/ardupilot_manager/firmware/test_FirmwareDownload.py
- core/services/ardupilot_manager/firmware/test_FirmwareInstall.py
Ardupilot manager tests fail my pre-push hooks here.
@rafaellehmkuhl can you confirm that there are no binaries for mac? have you ran into these failing tests before?
> core: ArdupilotManager: skip some tests on MacOS

- core/frontend/src/components/kraken/ExtensionModal.vue
- core/frontend/src/views/ExtensionManagerView.vue
Allow users to uninstall from current extension modal instead of showing a disabled `installed` button.
> Allow uninstall from extension modal

- core/frontend/src/components/vehiclesetup/Configure.vue
- core/frontend/src/components/vehiclesetup/configuration/accelerometer/ArdupilotAccelerometerSetup.vue
- core/frontend/src/components/vehiclesetup/configuration/accelerometer/FullAccelerometerCalibration.vue
- core/frontend/src/components/vehiclesetup/configuration/accelerometer/QuickAccelerometerCalibration.vue
- core/frontend/src/components/vehiclesetup/configuration/common.ts
- core/frontend/src/components/vehiclesetup/overview/OnboardSensors.vue
> Add UI for accelerometer calibration

- deploy/deploy.sh
Fixes this warning making clear the append statement
```
DEV_PART2+=2
^-------^ SC2324 (warning): var+=1 will append, not increment. Use (( var += 1 )), declare -i var, or quote number to silence.
```
> Fix shellcheck warning listed in deploy

- core/frontend/src/components/vehiclesetup/configuration/compass/LargeVehicleCompassCalibrator.vue
This is the only way to get the actual error message from the autopilot...
> core: frontend: add statustextwatcher on error for compass calibrations

- core/frontend/src/components/vehiclesetup/configuration/compass/LargeVehicleCompassCalibrator.vue
- core/frontend/src/components/vehiclesetup/overview/ParamSets.vue
- core/frontend/src/libs/MAVLink2Rest/index.ts
This creates `mavlink2rest.sendCommandLong()` and `mavlink2rest.waitForAck()` and updates the current calibration code to use them
> Refactor COMMAND_LONG code

- core/Dockerfile
- core/frontend/src/components/bridges/BridgeCard.vue
- core/frontend/src/components/bridges/BridgeCreationDialog.vue
- core/frontend/src/components/bridges/Bridget.vue
- core/frontend/src/types/bridges.ts
- core/libs/bridges/bridges/bridges.py
- core/services/bridget/bridget.py
- core/services/bridget/main.py
- core/services/bridget/settings.py
- core/services/ping/ping1d_driver.py
- core/services/ping/pingdriver.py
- core/start-blueos-core
- core/tools/bridges/bootstrap.sh
- core/tools/install-system-tools.sh
- core/tools/sudo/bootstrap.sh
This splits udp port handling into udp target port and udp lister port.
client will always send data to `udp_target_port`.
server will always listen at `udp_listen_port`.
additionally, this now allows the client to pick the port it will bind to, using `udp_listen_port`.
this is useful for implementations where whatever is talking to us is sending/receiving packets naively, without an actual udp "connection". 
~depends on https://github.com/patrickelectric/bridges/pull/11~
fix #2305 
fix #2304
> Bridges update

- core/frontend/src/utils/deviceid_decoder.ts
IST8308 as wrongly displaying as eAHRS due to checking the bus number instead of type in the switch
> core: frontend: fix device decoder

- core/services/versionchooser/utils/chooser.py
Stop can take time and as we saw in the pass, can also get in a long waiting state. Lets just kill, bootstrap operation can't go wrong.
> core: services: versionchooser: chooser: Kill bootstrap over stopping

- core/services/versionchooser/utils/chooser.py
Fixes cases where the update bootstrap could be externally called without the image has been pulled prior to it.
> Add image check before updating bootstrap in version chooser

- core/frontend/src/App.vue
Fix small error appearing on console when clicking in logo when already in home.
> Add path check prior to pushing repeated path in router when using logo to navigate to home

- install/boards/bcm_27xx.sh
this should make blueos_startup_update stop running in the first boot.
I have a following patch that adds tests of blueos_startup_update and bcm_27xx to our pre push hook tests
> install: fix configuration of config.txt

- core/run-service.sh
- core/start-blueos-core
fix #2393 
fix #2387
fix #2378
> Use cgroups for limiting memory usage

- core/frontend/src/components/kraken/ExtensionCreationDialog.vue
> core: frontend: extensions: raise error if tag is included in docker name

- core/frontend/src/components/utils/BrIframe.vue
- core/frontend/src/utils/shaders.ts
Based on discussions with @patrickelectric , this PR introduces a loading component in BrIFrame using shader and canvas for faster loading. It also implements a simple bubble fragment shader for the loading screen, laying the groundwork for the application's splash screen.
Currently, the loading logo geometries are rendered by the fragment shader directly. For better efficiency, it might be preferable in the future to transition to a vertex buffer and render on a second pass, rather than utilizing rect functions in fShaders.
> Add plain shader loading overlay in BrIframe

- core/services/kraken/kraken.py
When installing some extension, the progress popup closes unexpectedly after clicking in install, but the extension still being installed, since the way digest was being passed was considered invalid reference the front end closes the popup but the back still installing. With the fix the digest is passed in a compatible manner and the progress popup when installing keeps open.
> Fix invalid reference pass in digest passed on install on kraken

- core/libs/commonwealth/commonwealth/utils/general.py
This fixes the lsof operation that is blocking and using 100% of cpu in some cases.
```
2024-02-27 19:22:03.150 | DEBUG    | __main__:zip_files:29 - Deleted file: /shortcuts/system_logs/ardupilot-manager/logfile_02-22-2024_10:39:21.log
2024-02-27 19:22:08.175 | ERROR    | commonwealth.utils.general:file_is_open:46 - Failed to check if file /shortcuts/system_logs/ardupilot-manager/logfile_02-27-2024_11:30:22.log is open, Command '['lsof', PosixPath('/var/logs/blueos/services/ardupilot-manager/logfile_02-27-2024_11:30:22.log')]' timed out after 5 seconds
```
> core: libs: commonwealth: general: Add timeout for lsof operation

- core/frontend/src/components/vehiclesetup/configuration/compass/ArdupilotMavlinkCompassSetup.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/AutoCoordinateDetector.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/CalibrationQualityIndicator.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/CompassMaskPicker.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/FullCompassCalibrator.vue
This is the calibration method available on QGC, MissionPlanner, and etc.
[Screencast from 2024-04-19 16-49-10.webm](https://github.com/bluerobotics/BlueOS/assets/4013804/709852eb-89f8-44d1-8ed5-032cfe640575)
ps: the progress bar is actually centered in the code, I made the video before I fixed it
> Add UI for onboard compass calibration

- .eslintrc.js
This catches unnecessary else blocks. sadly doesn't seems to work after `throw`
also, this works with --fix, which is neat
> eslint: add no-else-return

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
[Screencast from 2024-04-24 13-59-44.webm](https://github.com/bluerobotics/BlueOS/assets/4013804/013c4e38-9c7e-4666-b0d0-5fd62de5eaa8)
helps #1818 
At least gets us to parity with qgc on that regard
tested with a servo on both sub and rover
> core: frontend: allow reversing motors in the frontend

- core/Dockerfile
Fix https://github.com/bluerobotics/BlueOS/issues/2435
> core: Dockerfile: Enforce style for git version

- core/frontend/src/components/wizard/DefaultParamLoader.vue
- core/frontend/src/components/wizard/RequireInternet.vue
- core/frontend/src/components/wizard/ScriptLoader.vue
- core/frontend/src/components/wizard/Wizard.vue
> Make parameters and scripts loader update based on is_online from Wizard

- core/services/kraken/api/__init__.py
- core/services/kraken/api/v1/routers/__init__.py
- core/services/kraken/api/v2/routers/__init__.py
- core/services/kraken/manifest/__init__.py
Pylint is throwing W0406 without real cause based on other changes like removing comments or rearranging the code.
> Fix random W0406 by pylint in module imports in __init__.py

- core/services/ping/ping360_driver.py
- core/services/ping/ping360_ethernet_driver.py
- core/services/ping/ping360_ethernet_prober.py
- core/services/ping/pingmanager.py
- core/services/ping/pingutils.py
- core/services/ping/portwatcher.py
Some robustness improvements that will hopefully fix #2569.
I've tested this on my machine, and it doesn't seem to have any regressions, and the dropped network device handling works 👍 
Not sure whether it fixes the duplication issue because I haven't run into it in the first place, so I've asked Aaron to see if the issue is fixed on his system.
Given the PR doesn't seem to hurt things we could potentially merge as-is, but it may also be worth waiting to see whether the issue is actually resolved (by testing from someone who can replicate it).
> Improve ethernet ping device handling

- core/frontend/src/components/kraken/InstalledExtensionCard.vue
- core/frontend/src/views/ExtensionManagerView.vue
When there is a single item on the installed extensions page, the card min-width is too small:
Fixed to:
> Installed Extensions Page: Fix single extension card min width

- core/frontend/src/components/autopilot/AutopilotSerialConfiguration.vue
- core/services/ardupilot_manager/typedefs.py
> Ardupilot udp serial port fix

- core/start-blueos-core
- core/tools/blueos_startup_update/blueos_startup_update
Required for Bookworm support.
Tested on current builds and on pi5
Ideally we'd make it a class instead of using globals, but I'd rather keep the change small.
~This will error if neither of the files exist, how should we handle that?~ I made it so we never halt start-blueos-core due to errors in blueos_startup_update
> blueos_startup_update: find config.txt and cmdline.txt dynamically

- core/frontend/src/components/kraken/ExtensionSettings.vue
- core/frontend/src/components/kraken/KrakenManager.ts
- core/frontend/src/types/kraken.ts
- core/frontend/src/views/ExtensionManagerView.vue
- core/services/kraken/api/v2/routers/manifest.py
- core/services/kraken/config.py
- core/services/kraken/kraken.py
- core/services/kraken/manifest/__init__.py
- core/services/kraken/manifest/exceptions.py
- core/services/kraken/manifest/manifest.py
- core/services/kraken/manifest/models.py
- core/services/kraken/settings.py
- core/services/kraken/setup.py
> Kraken: Add Manifest V2 with multiple manifest support

- core/tools/blueos_startup_update/blueos_startup_update.py
this install step was not in blueos_startup_update
https://github.com/bluerobotics/BlueOS/blob/master/install/boards/bcm_27xx.sh#L83-L84
> blueos_startup_update: add 'remove_console' step

- core/libs/commonwealth/commonwealth/utils/commands.py
- core/tools/blueos_startup_update/blueos_startup_update.py
the current "echo" method can break files with `"`
Can be tested on my remote williangalvani/blueos-core:upload_file
just take something out of cmdline.txt or config.txt and restart the core container
> Commonwealth: create upload_file()

- core/services/ardupilot_manager/main.py
> ArdupilotManager: reduce verbosity when there's no board running

- core/tools/blueos_startup_update/blueos_startup_update.py
fix #2176 
I tested by doing `chown -R root:root /home/pi/.ssh` and restarting the container. but it is already root:root in our images, I had manually changed it to do `ssh-copy-id`
> Fix ssh ownership

- bootstrap/startup.json.default
- core/tools/blueos_startup_update/blueos_startup_update.py
Our startup and blueos_startup_update files are inconsistent. also it _should_ require rw access for cgroups to work. it seems to be working regardless...
needs testing
> Cgroups updates

- core/frontend/src/components/cloud/CloudTrayMenu.vue
Change set major tom token to preserve other keys since when changing token major tom itself may already have set other keys and CloudTrayMenu was overriding it
> Frontend: CloudTrayMenu: Fix set major tom token in bag to not delete other existing keys

- .github/workflows/test-and-deploy.yml
Fix:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> ci: test-and-deploy: Update action checkout to v4

- core/tools/mavlink_camera_manager/bootstrap.sh
The MCM was using the wrong settings file, [as reported here](https://github.com/mavlink/mavlink-camera-manager/issues/417).
> core: tools: mavlink-camera-manager: Update to t3.15.1

- .github/workflows/test-and-deploy.yml
- .hooks/pre-push
- poetry.toml
- pyproject.toml
This migrates the hooks/pre-push to use Poetry directly, and makes all the files contained within the project's virtual environment, instead of loading files on the users' folder, making the development environment more replicable.
To use the pre-push, the user must have a Python 3.11 available. Before, it would use whatever the system's Python was, failing to run when the user had 3.12 or 3.10 for example.
To test:
- checkout to this PR's branch
- clean the project: `\rm -rf .venv poetry.lock`
- run the pre-push hook: `.hooks/pre-push`
To check whether it had any impact on the normal installation:
- Try out the `joaoantoniocardoso/blueos-core`:`fix-pre-push` on BlueOS
I have tested it myself, but more samples are welcome.
After this patch is merged, we can all clean our system:
* `ls …
> fix pre-push hooks, and move to Poetry

- core/frontend/src/components/mavlink/MavlinkUpdater.vue
0 means we get all messages. using 1 means we were losing a lot of heartbeats, as we have multiple components sending them at 1Hz and our mavlink interface was not designed with this in mind
This fixes issues in the Motor Test page where it loses heartbeats and doesn't detect arming/disarming and modes properly
> frontend: use 0 frequency for HEARTBEAT messages

- CoC.md
- README.md
> CoC: Add first commit

- core/libs/commonwealth/commonwealth/settings/bases/pykson_base.py
> core: libs: commonwealth: settings: pykson: Save in pretty json

- .gitmodules
- core/frontend/src/components/parameter-editor/ParameterEditor.vue
- core/frontend/src/types/autopilot/parameter-table.ts
- core/frontend/src/types/autopilot/parameter.ts
- core/frontend/src/types/autopilot/px4/metadata-fetcher.ts
> frontend: Add PX4 parameter metadata

- core/services/kraken/kraken.py
- core/services/kraken/manifest/exceptions.py
- core/services/kraken/manifest/manifest.py
Fix #2727
* Add ManifestBackendOffline error in manifest fetch
* Add treatment to try to start anyway if fails to fetch manifest
> kraken: Add treatment for ext start when offline

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
- core/frontend/src/types/video.ts
- core/frontend/src/utils/pattern_validators.ts
Closes #2737 
When in dev mode:
If set some pirate mode variant in dev mode but switching back to normal mode only that one will be added, and if change it will not more be available:
> frontend: VideStreamCreation: Add more RTSPs variants (UDP, TCP, HTTP) support

- core/frontend/src/components/health/HealthTrayMenu.vue
On the pi, the temp is labeled ""cpu_thermal temp1" This should be generic enough
fix #2750
> frontend: HealthTrayMenu: fix 'loading...' temperature on PIs

- core/frontend/src/App.vue
- core/frontend/src/libs/settings.ts
- core/frontend/src/store/settings.ts
* Add new conditionals for dev mode
* Add new way to enter dev mode in App
* Remove cloud integration unless in dev mode
> frontend: App: Add new way to enter in dev mode

- core/services/kraken/extension/extension.py
Closes #2763 
When installing some extension using atomic flag, and this extension already have some installed version running, if the install from the new version fails, kraken wasn't re enabling the previously running one.
> kraken: Fix non restarting on atomic install kraken

- core/frontend/src/components/utils/ParameterLoadingSpinner.vue
- core/frontend/src/components/vehiclesetup/configuration/accelerometer/ArdupilotAccelerometerSetup.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/ArdupilotMavlinkCompassSetup.vue
- core/frontend/src/views/VehicleSetupView.vue
Also apply it to all of the vehicle-setup section, which makes everything smoother as the data doesn't get populated slowly, and removes duplicated code
we have to check how loading default parameters deal with it
> Create component for "gating" pages and wait until parameters finish loading

- core/frontend/src/components/kraken/InstalledExtensionCard.vue
- core/frontend/src/views/ExtensionManagerView.vue
> frontend: extensions: Improve installed extensions layout and card styling/title

- core/libs/commonwealth/commonwealth/utils/streaming.py
Reduce default timeout in streaming timeout to have better experience in places like log fetcher
> libs: common: streaming: Reduce default timeout in timeout streaming

- core/frontend/src/components/vehiclesetup/configuration/accelerometer/FullAccelerometerCalibration.vue
- core/frontend/src/components/vehiclesetup/configuration/accelerometer/QuickAccelerometerCalibration.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/ArdupilotMavlinkCompassSetup.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/CompassLearn.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/FullCompassCalibrator.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/LargeVehicleCompassCalibrator.vue
> Small calibration fixes

- bootstrap/bootstrap/bootstrap.py
- core/services/kraken/extension/extension.py
- core/services/versionchooser/utils/chooser.py
> Limit maximum log size

- install/configs/journald.conf
- install/install.sh
> install: configs: Add first version

- core/frontend/src/components/kraken/cards/StoreExtensionCard.vue
Context from internal discussion:
* "Download" numbers seemed inflated and unreasonable
* Apparently [docker pulls is for manifest pulls, not image downloads](https://github.com/docker/hub-feedback/issues/1047#issuecomment-687965123)
* Even that [may be inflated](https://github.com/docker/hub-feedback/issues/2182)
* If you become a [verified publisher](https://www.docker.com/partners/programs/) they give you more useful market insights / statistics (but we can't expect that from every Extension owner)
> Revert "core: frontend: components: kraken: StoreExtensionCard: Add number of downloads"

- core/start-blueos-core
The previous code did not work since it was running with the extensions folder that can have a huge number of files
Not sure about the original work done in: #2322
Edit: Tested and fixed the problem of having extensions with more than 200k files
> core: start-blueos-core: Fix permission logic

- bootstrap/startup.json.default
- core/services/wifi/main.py
- core/tools/blueos_startup_update/blueos_startup_update.py
This will set the priority to the external wifi adapter
> Add support to external wifi adapter

- core/frontend/src/components/parameter-editor/InlineParameterEditor.vue
- core/frontend/src/components/vehiclesetup/Configure.vue
- core/frontend/src/components/vehiclesetup/overview/GyroCalib.vue
> add interface for Gyro calibration

- core/frontend/src/components/kraken/Utils.ts
Fix error when using custom non semver version breaking extension from store page
> Frontend: Allow non semver versions tags to be used in extensions

- core/frontend/src/views/ExtensionManagerView.vue
This fix cases where user edits the tag and the installed extension card changes instantaneously without create being pressed
> Frontend: ExtManagerView: Fix passing a reference of installed extension to edit extension card

- core/services/helper/main.py
this will help us understand why some extensions just vanish for a while. as we'll be able to tell what port they are running on.
> helper: improve logging

- core/frontend/index.html
- core/tools/nginx/nginx.conf
This should fix some weird caching issues when we switch versions, which required forcing refreshes
> frontend: index.html: add meta tags and headers  to avoid caching index.html

- core/frontend/src/components/kraken/modals/ExtensionCreationModal.vue
- core/frontend/src/views/ExtensionManagerView.vue
When editing:
When creating:
Also allow custom permissions to be either empty or valid json, since sometimes when user does not wants to use custom permissions they can only send empty
> frontend: Change Create/Edit extension card top differ from Create and Editing operations

- core/frontend/src/router/index.ts
- core/frontend/src/views/FileBrowserView.vue
This passes urls through to filebrowser, so we can link folders to users without using the hard-coded ports.
something like http://blueos.local/tools/file-browser/files/configs/
> frontend: pass urls through to filebrowser

- core/frontend/src/components/kraken/BackAlleyTab.vue
Closes #2812 
Filters:
Sorts:
Note: After 8 items in Companies/Categories filters it will turn in a virtual scroll to void going out of vertical space
> Frontend: BackAlleyTab: Add new filters and sorts

- core/frontend/src/components/kraken/modals/ExtensionCreationModal.vue
* Return to conditionally use correct v-model for permissions depending on is_editing, if is editing use formatted_permissions otherwise use the new_extension.permission to store correctly
> Frontend: ExtCreationModal: Use correct v-model

- core/libs/commonwealth/commonwealth/utils/commands.py
- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/flight_controller_detector/Detector.py
- core/services/ardupilot_manager/flight_controller_detector/linux/argonot.py
- core/services/ardupilot_manager/flight_controller_detector/linux/detector.py
- core/services/ardupilot_manager/flight_controller_detector/linux/linux_boards.py
- core/services/ardupilot_manager/flight_controller_detector/linux/navigator.py
- core/tools/blueos_startup_update/blueos_startup_update.py
splitting it up to make the review process smoother
tested on pi4/bullseye
test on pi5/bookworm
~port mapping on pi4/bullseye has changed =[~
updated  serial mapping for pi4 on bullseye
> Linux refactor: Episode I

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/mavlink_proxy/Endpoint.py
> Fix Endpoint comparison, always overwrite mavlink2rest one

- core/services/ardupilot_manager/ArduPilotManager.py
- core/start-blueos-core
Revert changes made da3f785 since we  need to make sure we have backward compatibility with settings.json when migrating from newer versions to older ones and reapply them but using a new endpoint instead of modifying exiting one.
> Add new entry for mavlink2rest in default ArdupilotManager endpoints

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/flight_controller_detector/linux/linux_boards.py
This fixes an issue where the serial port mapping in ArdupilotManager is not being used, instead it always uses the board's default definition
> ArdupilotManager: generate serial command line options in ardupilotmanager instead of boards

- core/frontend/src/components/wifi/WifiManager.vue
- core/frontend/src/components/wifi/WifiUpdater.vue
- core/frontend/src/store/wifi.ts
- core/frontend/src/types/wifi.ts
- core/services/wifi/Hotspot.py
- core/services/wifi/main.py
- core/services/wifi/typedefs.py
This greys out the hotspot buttons and prevents the backend from trying to enable it if the underlying OS is not supported
~needs testing~ tested on pi4/bookworm
> Handle (for now) unsupported hotspot functionality in bookworm

- core/services/ardupilot_manager/ArduPilotManager.py
I don't know why, but `self.settings.sitl_frame` and `self.configuration["sitl_frame"]` are not matching.
I don't know why that is happening, but I have already lost 2 hours on this and I got more important stuff to work on.
This fixes the issue where the SITL frame saved in the settings is ignored and overwritten.
> ArdupilotManager: fix loading sitl frame

- core/frontend/src/App.vue
- core/frontend/src/components/common/NotSafeOverlay.vue
- core/frontend/src/components/health/HealthTrayMenu.vue
- core/frontend/src/store/autopilot.ts
- core/frontend/src/views/Autopilot.vue
- core/frontend/src/views/ExtensionManagerView.vue
- core/frontend/src/views/NetworkTestView.vue
- core/frontend/src/views/VersionChooser.vue
- core/libs/commonwealth/commonwealth/mavlink_comm/VehicleManager.py
- core/services/ardupilot_manager/main.py
> creating "safe mode"

- core/frontend/src/views/Autopilot.vue
trying to understand how ci allowed this through...
> Frontend: Autopilot: add missing NotSafeOverlay import

- core/frontend/src/App.vue
- core/frontend/src/menus.ts
- core/frontend/src/types/helper.ts
- core/frontend/vite.config.js
- core/services/helper/main.py
- core/start-blueos-core
- core/tools/nginx/nginx.conf
reviving #1842 as a fallback for remote control
This introduces a new optional `works_in_relative_paths`  to the services metadata.
These will use a relative path (under `/extensionv2/`) to load the extension in the browser.
This allows them to be used seamlessly behind a webserver with ssl.
> Improve remote access support

- core/frontend/src/App.vue
- core/frontend/src/components/health/GpsTrayMenu.vue
> Show topbar icons for 2 Gps systems, display yaw if available

- core/frontend/src/components/scanner/availableServicesTable.vue
Previously, the hostname would get truncated at the first colon.
> Fix service links when using IPv6 addresses

- core/libs/commonwealth/commonwealth/utils/DHCPServerManager.py
This just changes things so that we don't serve the whole range while we don't have a proper configuration interface for the dhcp servers
> Cable-guy: DHCP servers with unspecified lease ranges now serve 101-200

- core/services/helper/main.py
- core/services/helper/nginx_parser.py
- core/tools/nginx/nginx.conf
Nginx supports full regex-based rules, but we don't actually need them
1. Switch to prefix-based locations, which are easier to understand and gets rid of unnecessary rewrite rules.
2. This has the effect of also allowing the server to rewrite "Location" and "Refresh" headers, which would otherwise require manually using `proxy_redirect`.
3. This avoids hardcoding the protocol and IP address (which make troubleshooting network issues very confusing!)
> Nginx: use prefixes instead of regexes

- core/tools/ardupilot_tools/bootstrap.sh
we need to include this patch to support beta+n values in the software versions:
https://github.com/ArduPilot/ardupilot/pull/27599
> autopilot_fw_decoder: bump to current ardupilot master

- .github/workflows/test-and-deploy.yml
- deploy/pimod/blueos.Pifile
- install/boards/config.toml
- install/install.sh
~requires~ build will work regardless, but networking will be challenging without #2682 
artifacts can be downloaded here:
https://github.com/Williangalvani/blueos-docker/actions/runs/11014995068
> add Pi5 and Pi4-boorkworm image deployments

- core/tools/nginx/nginx.conf
Undo my introduction of invalid syntax in #2913, which breaks blueos.
It turns out that you can't start a URL with a leading colon. The only reason I thought it gave the same results is because `service nginx reload` bailed when loading the new config, but left the server running with the same state.
> Fix nginx.conf syntax that I broke

- core/frontend/src/App.vue
- core/frontend/src/store/system-information.ts
- core/frontend/src/types/system-information/system.ts
- core/frontend/src/widgets/Networking.vue
ideally the math should be done by linux2rest itself...
a current bug is that if you go to the system page, you get doubled the requests, and as they seem to be cached in linux2rest's side, the value jumps to zero and back
The values are also not super consistent with other tools, but that could be due to the super low sampling rate
> frontend: create widget to show upload/download speeds

- core/services/kraken/extension/extension.py
- core/services/kraken/kraken.py
- core/services/kraken/main.py
Since some extensions may be failing to start repeatedly, add a exp delay and start attempts tracking to avoid kraken main loop being flooded with start attempts and degrade overall performance
> Core: Kraken: Improve main loop tasks and add exp delay to avoid flooding

- core/services/wifi/WifiManager.py
- core/tools/install-system-tools.sh
also handles the not-supported hotspot in a couple of other spots to cleanup logs.
> Fix wifi not getting an ip address on bookworm

- core/services/wifi/main.py
This was being logged and logs are sometimes shared publicly for troubleshooting.
> wifi: stop leaking sensitive data

- core/services/ardupilot_manager/mavlink_proxy/Manager.py
When modifying the tool directly without settings control property should_be_running usually generates multiple starts of the tool
> Core: Autopilot Manager: Fix multiple starts race when setting preferred router

- core/Dockerfile
- core/services/ardupilot_manager/mavlink_proxy/MAVLinkServer.py
- core/services/ardupilot_manager/mavlink_proxy/Manager.py
- core/tools/install-static-binaries.sh
- core/tools/mavlink_server/bootstrap.sh
Working fine with SITL, the problem when connecting with an autopilot is probably a missing stream-request in the router. That should be configured with command line as mavp2p.
https://github.com/bluerobotics/mavlink-server/issues/30
> Add MAVLinkServer

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/exceptions.py
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
- core/services/ardupilot_manager/mavlink_proxy/Endpoint.py
- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
- core/services/ardupilot_manager/mavlink_proxy/MAVLinkServer.py
- core/services/ardupilot_manager/mavlink_proxy/MAVP2P.py
- core/services/ardupilot_manager/mavlink_proxy/MAVProxy.py
- core/services/ardupilot_manager/mavlink_proxy/Manager.py
- core/services/ardupilot_manager/mavlink_proxy/exceptions.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
- core/services/ardupilot_manager/typedefs.py
* Isolate mavlink_proxy type definitions and exceptions in its own module
> Core: AutoPilot Manager: Isolate mavlink proxy types and endpoints - (Serial PX4 support part 3) 

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/firmware/FirmwareInstall.py
- core/services/ardupilot_manager/flight_controller_detector/linux/navigator.py
- core/services/ardupilot_manager/setup.py
- core/services/ardupilot_manager/typedefs.py
~needs https://github.com/ArduPilot/ardupilot/pull/28239~
> ArdupilotManager: add navigator64 support

- bootstrap/Dockerfile
- core/Dockerfile
See https://docs.docker.com/reference/build-checks/ for a list of checks
> Address all changes suggested by docker build checks

- core/frontend/src/components/ethernet/InterfaceCard.vue
the <span> was required as the tooltip doesnt work on disabled elements
> Frontend: ethernet: add tooltip informing why the DHCP server button is disabled

- core/frontend/src/components/vehiclesetup/Configure.vue
- core/frontend/src/components/vehiclesetup/configuration/accelerometer/FullAccelerometerCalibration.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/ArdupilotMavlinkCompassSetup.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/FullCompassCalibrator.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/LargeVehicleCompassCalibrator.vue
Makes some wording consistent
Allows closing accel cal dialog
Make calibrations "not-safe" when armed
Only show cancel button for full calibration when it is in a cancel-able state
> Setup tweaks

- core/frontend/src/components/vehiclesetup/configuration/compass/ArdupilotMavlinkCompassSetup.vue
This happens in sitl. the code always tries to reorder compasses if more than 3 are available, as it checks for "undefined"
> VehicleSetup: fix issue in vehciles with more than 3 compasses

- core/libs/commonwealth/commonwealth/utils/logs.py
1. Remove dividers - these are unnecessary and the colon causes problems (fixes #2969)
2. Switch order from month,day,year to year,month,day. This ensures correct collation when sorted
> Change logfile name

- install/configs/blueos.service
- install/install.sh
The current install script uses rc.local to start the blueos-bootstrap container, which works fine on Raspberry Pi SoCs. However, it does not work for other SoCs, such as the Nvidia Jetson Nano, which does not use rc.local. This patch will use a systemd service to start the blueos-bootstrap container on boot, supported by both Raspberry Pi SoCs and Nvidia Jetson SoCs.
> Switch blueos-bootstrap from rc.local to systemd

- core/services/ardupilot_manager/autopilot_manager.py
> Autopilot Manager: pass process pid as string when using 'kill'

- core/frontend/src/types/autopilot/parameter-table.ts
This allows integrators to override the parameters metadata with their own. It is specially useful if they changed the firmware version.
> frontend: parameter-table: allow using metadata override

- core/services/helper/main.py
* Allow to set a source IP address when getting best server to allow testing internet speed using other interfaces
> backend: helper: Allow set source IP on speedtest

- core/frontend/src/components/wizard/DefaultParamLoader.vue
This fixes the issue of double parameter entries as Navigator64 `includes` "Navigator"
> frontend: defaultParameterLoader: add trailing slash to filters

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
- core/frontend/src/types/video.ts
- core/frontend/src/utils/pattern_validators.ts
> Add H265 support endpoint for camera manager

- core/frontend/src/components/health/HealthTrayMenu.vue
- core/frontend/src/components/system-information/SystemCondition.vue
these are the temps available on my (radxa) system:
> frontend: add 'soc' option when looking for temperature source

- core/libs/commonwealth/commonwealth/settings/bases/pydantic_base.py
* Change to use in both older and newer pydantic versions dict with json.dumps instead of using write directly
> core:libs:commonwealth:Unify dump in pydantic save

- core/libs/commonwealth/commonwealth/utils/commands.py
- core/services/commander/main.py
- core/start-blueos-core
- core/tools/scripts/red-pill
I used this to install BlueOS on a Radxa Zero 3E running ubuntu.
The issue is there's no `pi` user there, so it requires these changes in order to be able to install the ssh key.
Additionaly, this is the updated startup.json:
```
{
"core": {
"binds": {
"/dev/": {
"mode": "rw"
},
"/etc/blueos": {
"bind": "/etc/blueos",
"mode": "rw"
},
"/etc/dhcpcd.conf": {
"bind": "/etc/dhcpcd.conf",
"mode": "rw"
},
"/etc/machine-id": {
"bind": "/etc/machine-id",
"mode": "ro"
},
"/etc/resolv.conf.host": {
"bind": "/etc/resolv.conf.host",
"mode": "ro"
},
"/home/pi/.ssh": {
"bind": "/home/pi/.ssh",
"mode": "rw"
},
"/home/rock/.ssh": {
"bind": "/home/rock/.ssh",
"mode": "rw"
},
"/run/udev": {
"bind": "/run/udev",
"mode": "ro"
},
"/sys/": {
"bind": "/sys/",
"mode": "rw"
}, …
```
> allow getting ssh user and password from environment variables

- core/services/helper/main.py
> core: services: helper: Add root page

- core/services/kraken/api/v2/routers/manifest.py
- core/services/kraken/manifest/manifest.py
Allow fetching all extensions versions available in a given manifest or in consolidated manifest for easy use on auto update features
> Core: Services: Kraken: Allow fetching availbale versions of a given Extension

- core/compose/compose.yml
Some people are having issues trying to run BlueOS in development mode due to stale information about MajorTom service (#3030, #2953)
> fix: update telemetry service details on compose.yml

- .hooks/pre-push
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
This reduces the mavlink_proxy.test_all test from 108s to ~60s on my machine
> Faster tests

- core/frontend/src/components/parameter-editor/InlineParameterEditor.vue
- core/frontend/src/components/parameter-editor/ParameterLabel.vue
> frontend: add tooltips on InlineParameterEditor with parameter name, options, and description

- core/tools/blueos_startup_update/blueos_startup_update.py
tested by running `BLUEOS_DISABLE_PATCHES=userdata,cgroups,nginx,dwc2,ssh,i2c4,dns blueos_startup_update.py`
fix #3035
> bluoes_startup_update: add fine-grained patch suppression

- core/start-blueos-core
Master is broken since BLUEOS_DISABLE_SERVICES is empty by default
> core: start-blueos-core: Fix tmux setenv when variable is empty

- .github/workflows/test-and-deploy.yml
- core/Dockerfile
- core/frontend/src/components/app/ReportMenu.vue
- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/store/mavlink.ts
- core/frontend/src/utils/helper_functions.ts
- core/services/ardupilot_manager/firmware/FirmwareDownload.py
- install/README.md
- install/boards/bcm_2712.sh
- install/boards/bcm_27xx.sh
- install/boards/configure_board.sh
- install/install.sh
- install/network/avahi.sh
At some point the github repo was renamed from BlueOS to BlueOS-docker. Updated the name in documentation and scripts to match.
> Update name of git repo

- core/services/cable_guy/api/manager.py
- core/services/cable_guy/main.py
- core/services/cable_guy/networksetup.py
should fix the case where the pi is not getting a dynamic ip automatically when using networkmanager
also fixes 
```
2025-01-13 18:54:19.966 | INFO     | api.manager:add_static_ip:258 - Adding static IP '192.168.2.2' to interface 'eth0'.
2025-01-13 18:54:20.972 | ERROR    | networksetup:add_static_ip:89 - Failed to set static ip 192.168.2.2 for eth0: 'NetworkConnectionSettings' object is not subscriptable
```
> Cable guy tweaks

- core/tools/mavlink_camera_manager/bootstrap.sh
This patch:
- Fixes OpenAPI specs by defining the return codes/errors.
- Improves Redirec to WebRTC compatibility by re-payloading the RTP packages.
[changelog](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.18.1)
> core: tools: mavlink-camera-manager: Update to t3.18.1

- core/services/ardupilot_manager/autopilot_manager.py
- core/services/ardupilot_manager/mavlink_proxy/Manager.py
* Avoid start autopilot again if already running.
> services: autopilot-manager: avoid double starts

- core/frontend/src/components/kraken/cards/InstalledExtensionCard.vue
When user have a stable version running and manifest somehow does not generates complete and latest from manifest is older than current one, installed ext card is suggesting an older version as update.
> Core: Frontend: InstalledExtensionCard: Fix has update available for stable versions

- core/services/wifi/wifi_handlers/networkmanager/networkmanager.py
fixes the issue where the hotspot doesnt come on by default on the first boot on bookworm, because the settings are null
> Wifi: enable hotspot if setting is unset(null)

- core/services/cable_guy/api/manager.py
- core/services/cable_guy/networksetup.py
- core/tools/blueos_startup_update/blueos_startup_update.py
- core/tools/install-system-tools.sh
now using dhclient instead of networkmanager directly...
needs more testing
testing can be done by connecting to blueos via wifi, then
```
rm /roo/.config/cable-guy/settings.json  # to reset settings
red-pill
nmcli -g NAME,DEVICE con show | grep eth0 | cut -d: -f1 | xargs -r nmcli con delete
```
> Fix Bookworm networking at once

- core/services/ardupilot_manager/setup.py
~letting ci build this one for testing.~ tested
should fix the default firmware for navigator64 not being found on a fresh install
> Navigator64 fixes

- core/services/helper/main.py
Fix parsing error when response has no body
Previously, you could see errors like this in the log:
```
2025-01-23 23:30:16.526 | WARNING  | __main__:detect_service:333 - Failed parsing the service title: object of type 'NoneType' has no len()
```
> core: cable-guy: Fix parsing error when response has no body

- install/install.sh
This prevents the install script from crashing if run on an existing blueos machine.
> Overwrite /etc/resolv.conf.host if it exists

- core/frontend/src/views/MainView.vue
Improves the main apps UI, changing from default row/cols combination to a grid system and when using small screens devices fallback for single column flex display.
Default Size:
Medium size:
Medium size menu collapsed
Small size:
Minimum size:
Closes #2594
> frontend: MainView: Fix grid distribution

- core/frontend/src/components/app/SettingsMenu.vue
Since currently no user feedback is given when performing operations, this PR adds an overlay with information about current operation and in case of errors add an alert at the top of the settings menu to make clear to user that operation was not successful.
Feedback provided for user:
Closes #2820
As the timeouts were shorts most of remove operations were failing, so timeouts for removing logs and reset were increased.
Probably fix #2821 by timeout increasing
> frontend: SettingsMenu: Add feedback and increase timeouts

- core/tools/nginx/nginx.conf
With that, any path that returns a resource can be accessed via the cache path.
Tested with:
- http://192.168.2.2/cache/keanu-reeves.org/wp/wp-content/uploads/2024/05/Keanu-Reeves-Kirsten-Stewart-and-800x400.jpg
- http://192.168.2.2/cache/firmware.ardupilot.org/manifest.json
> core: tools: nginx: Add cache path

- core/services/wifi/wifi_handlers/networkmanager/networkmanager.py
> core: wifi: wifi_handlers: networkmanager: Add default gateway for wifi hotspot

- bootstrap/startup.json.default
- core/frontend/src/components/version-chooser/DockerLogin.vue
- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/types/version-chooser.ts
- core/frontend/src/utils/version_chooser.ts
- core/services/versionchooser/docker_login.py
- core/services/versionchooser/main.py
- core/services/versionchooser/openapi/versionchooser.yaml
- core/tools/blueos_startup_update/blueos_startup_update.py
Allows users to perform a Docker login to the default Docker registry or custom registries using their Docker username and password or a Personal Access Token (PAT).
Effectively allows for the following:
* Mirrors the functionality of the `docker login` command.
* Saves credentials to `.docker/config.json` for both the normal user and the root user (if specified).
* Affects the entire Docker daemon context, enabling all BlueOS services to fetch images or other resources from the authenticated registry.
To access users must be in `pirate mode` on the version chooser page:
---
By default, the dialog logs in using only the normal Raspberry Pi user (not root) and the default Docker registry (`https://index.docker.io/v1/`). 
If needed, users can:
- Authenticate to a custom registry by enabling …
> VersionChooser: Allow login for docker daemon by version chooser interface

- core/services/beacon/main.py
Fixes #2548 
⚠️ UNTESTED ⚠️
Probably a good idea to make sure this works properly for both ethernet and USB-OTG connections before merging.
If it's possible for the `domain_names` variable to not exist or be an empty list then we should catch/handle that (`except` the `AttributeError`, and/or make sure to append the `hostname` if it's not there at the end, like is being done with the default).
> core: services: beacon: fix broken ethernet domain name config

- core/frontend/src/components/common/DevicePathHelper.vue
tested by connecting the frontend to a pi4 and a pi5 on bookworm
> Frotend: DevicePathHelper: fix image mapping for bookworm

- core/services/wifi/wifi_handlers/networkmanager/networkmanager.py
This prevents unnecessary changes to profiles by NetworkManager
Helps #3185
> Wifi: use fetch_secrets=False on get_saved_wifi_networks

- core/frontend/src/App.vue
- core/frontend/src/libs/settings.ts
- core/frontend/src/store/settings.ts
> Unified settings

- core/frontend/public/libs/ffmpeg/LICENSE
- core/frontend/public/libs/ffmpeg/README.md
When checking the compiled version of ffmpeg we get:
`configuration: --target-os=none --arch=x86_32 --enable-cross-compile --disable-asm --disable-stripping --disable-programs --disable-doc --disable-debug --disable-runtime-cpudetect --disable-autodetect --nm=emnm --ar=emar --ranlib=emranlib --cc=emcc --cxx=em++ --objcc=emcc --dep-cc=emcc --extra-cflags='-I/opt/include -O3 -msimd128' --extra-cxxflags='-I/opt/include -O3 -msimd128' --disable-pthreads --disable-w32threads --disable-os2threads --enable-gpl --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libopus --enable-zlib --enable-libwebp --enable-libfreetype --enable-libfribidi --enable-libass --enable-libzimg`
The `enable-gpl` with `libx264` and `libx265` results in a …
> core: frontend: public: libs: ffmpeg: Update license to GPL3

- core/libs/commonwealth/src/commonwealth/utils/logs.py
Green is client:
Enhancements:
- Configure the log sink to open the zenoh session in client mode with a default TCP endpoint
> core: libs: commonwealth: utils: logs: Move log to run as client

- core/frontend/vite.config.js
All other endpoints have it, I had some problems with bun/yarn dev when running without it.
> frontend: vite.config: Add missing changeOrigin for version-chooser

- core/tools/blueos_startup_update/blueos_startup_update.py
~not~tested.
The issue here is that the ssh setup was being done _after_ blueos_startup_update, when commander started up.
This meant it would always fail on the first boot, to succeed later on after commander ran at least once.
fix #3038
> core: move setup_ssh() over to startup_blueos_update
