bluerobotics/BlueOS

- install/README.md
> install: Add README

- install/install.sh
Unblock both wifi and bluetooth
Fix #14
> install: Add unblock all with rfkill

- .pylintrc
- Add new test for dictionaries
- Add description why no-member should be disabled: https://github.com/bluerobotics/companion-docker/pull/19#discussion_r482017356
> pylint: Update configuration file

- .github/workflows/python-test.yml
- .hooks/pre-push
> hooks: Add pre-push hook as test

- .github/workflows/python-test.yml
- .hooks/pre-push
It's using 68% since it's the actual coverage of the code, the idea is to improve this to over 9000
We can go up to 84% with mavproxy and mavlink-router installed, but we can do that in the next pull request
Fix #31
> Add coverage

- core/.dockerignore
> core: Add .dockerignore

- .github/workflows/deploy.yml
This makes our CI build both docker images
> CI: Allow deploying multiple dockers

- core/services/ardupilot_manager/firmware_download/FirmwareDownload.py
- core/services/ardupilot_manager/firmware_download/test_FirmwareDownload.py
- Add optional for failures
- Extract filename to preserve extensions
> FirmwareDownload: Improve download function

- core/services/ardupilot_manager/firmware_download/FirmwareDownload.py
- core/services/ardupilot_manager/firmware_download/test_FirmwareDownload.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
- core/services/ardupilot_manager/setup.py
How to test:
Replace install script docker to: `COMPANION_CORE="patrickelectric/companion-core"`
Open QGC or mavproxy to connect in: `tcp:raspberry_pi_ip:5766`
> Add initial navigator support 

- core/services/ardupilot_manager/main.py
> core: services: ardupilot_manager: Wait ardupilot to finish when running navigator

- install/install.sh
~depends on #42~
needs testing
> Install: update to use bootstrap

- bootstrap/bootstrap/bootstrap.py
> bootstrap: Fix name of companion-core for consistency

- .github/workflows/deploy.yml
> github: actions: deploy: Use new docker actions

- install/install.sh
> install: Remove iterator part from docker call

- install/install.sh
> install: Check for available free space

- core/services/wifi/main.py
> services: wifi: Add homepage with link to all paths

- .hooks/pre-push
> hooks: pre-push: Get absolute path directly from git

- core/services/helper/README.md
- core/services/helper/main.py
- core/services/helper/setup.py
- core/services/install-services.sh
- core/start-companion-core
It'll show all available ports with a http server running:
patrickelectric/companion-core:latest
> Add simple helper service

- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
- core/services/ardupilot_manager/mavlink_proxy/Manager.py
> Improve message if no MAVLink interface found

- .github/workflows/deploy.yml
> github: deploy: Move from armv6 to armv7

- core/Dockerfile
- core/start-companion-core
- core/tools/mavlink_camera_manager/bootstrap.sh
> Add camera manager service

- install/README.md
Improve information related to how use the install scripts with different remotes and versions
> install: README: Add information about custom builds

- install/boards/bcm_27xx.sh
> install: boards: Add missing REMOTE and VERSION for bcm_27xx

- core/tools/mavlink_camera_manager/bootstrap.sh
> core: tools: mavlink-camera-manager: Add x86 binary

- .github/workflows/deploy.yml
Download latest master version to improve build step in our CI
> github: workflows: deploy: Pull image before build to improve speed

- core/tools/mavlink_camera_manager/bootstrap.sh
Add extra check when the camera disconnects without gstreamer knowing and add the capability to provide for files for pipeline.
Changelog: https://github.com/patrickelectric/mavlink-camera-manager/releases/tag/t3.0.2
Fix #145
> core: tools: mavlink_camera_manager: Update to t3.0.2

- bootstrap/bootstrap/bootstrap.py
- bootstrap/test_bootstrap.py
> Bootstrap: don't pull a new image if there is a local version available

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
- core/services/ardupilot_manager/mavlink_proxy/Endpoint.py
- core/services/ardupilot_manager/mavlink_proxy/Manager.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
To be approved after #152 
Fix #164
> Use sets for endpoint aggregation logic

- core/services/ardupilot_manager/ArduPilotManager.py
This was tested and is working with both MavlinkRouter and MAVProxy.
> Connect Navigator to the mavlink Manager

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/Endpoint.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
To be approved after #165  
Implements #153
> Fancy endpoints

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
This "fixes" CI on master.
We should consider fixing the implementation instead.
> core: services: aurdupilot_manager: suppress 'consider-using-with' warning

- .hooks/pre-push
> CI: Use 'black' profile on Isort

- README.md
> README: Update badge reference

- core/services/cable_guy/main.py
- core/services/cable_guy/setup.py
> cable_guy: Update fastapi-versioning version with the latest features 

- core/services/wifi/WifiManager.py
- core/services/wifi/main.py
- core/services/wifi/setup.py
Fix #198 
- Segregate WifiManager class to dedicated file
- Replace dynamically generated routes with OpenAPI docs (swagger/redoc)
- Add types for WifiManager data
- Replace error-string-return with warning+httpexception
> Move WiFi service to FastAPI

- core/services/helper/.gitignore
- core/services/helper/html/index.html
- core/services/helper/main.py
- core/services/helper/setup.py
> core: services: html: Update service to use fastapi and html files

- install/install.sh
> install: Remove lost debug line

- .eslintrc.js
> eslint: Disallow multi-spaces

- core/services/helper/html/index.html
> core: helper; Fix webpage reference for API documentation

- core/services/helper/main.py
- core/services/helper/setup.py
urllib has a poor performance resulting in high cpu usage:
- ~40% when running in a raspberry pi 4
This commit improve the usage to around ~10%
Fix #253
> core: helper: Move from urllib to requests

- core/tools/mavlink_camera_manager/bootstrap.sh
The latest version adds title to the webpage,
allowing Helper service to name it.
Fix #259 
> core: tools: mavlink_camera_manager: Update to t3.0.3

- .pylintrc
- core/Dockerfile
- core/services/install-services.sh
- core/services/ping/bridges.py
- core/services/ping/main.py
- core/services/ping/ping1d_driver.py
- core/services/ping/ping360_driver.py
- core/services/ping/pingdriver.py
- core/services/ping/pingmanager.py
- core/services/ping/pingprober.py
- core/services/ping/pingutils.py
- core/services/ping/portwatcher.py
- core/services/ping/serialhelper.py
- core/services/ping/setup.py
- core/start-companion-core
- core/tools/bridges/bootstrap.sh
Convenience startup.json:
```
{
"core": {
"tag": "ping",
"image": "williangalvani/companion-core",
"enabled": true,
"webui": false,
"network": "host",
"binds": {
"/dev/": {
"mode": "rw"
},
"/sys/": {
"bind": "/sys/",
"mode": "ro"
},
"/var/run/wpa_supplicant/wlan0": {
"bind": "/var/run/wpa_supplicant/wlan0",
"mode": "rw"
},
"/tmp/wpa_playground": {
"bind": "/tmp/wpa_playground",
"mode": "rw"
},
"/var/run/docker.sock": {
"bind": "/var/run/docker.sock",
"mode": "rw"
}
},
"privileged": true
}
}
```
Helps #264
> Implement Ping service

- core/services/wifi/.gitignore
- core/services/wifi/WifiManager.py
- core/services/wifi/frontend/index.html
- core/services/wifi/main.py
- core/services/wifi/setup.py
- core/services/wifi/wpa_supplicant.py
- core/start-companion-core
What this PR adds:
- Frontend to the Wifi service
- Ability to see available networks and connect to them
- Ability to disconnect from connected networks
- Ability to check information regarding available and connected network
What this PR does not add:
- [List of saved networks and option to connect to them](https://github.com/bluerobotics/companion-docker/issues/239)
- [Possibility of connecting to a network that does not show up on the list](https://github.com/bluerobotics/companion-docker/issues/238)
> Wifi frontend

- core/Dockerfile
- core/services/ardupilot_manager/ArduPilotManager.py
- core/start-companion-core
- core/tools/mavlink2rest/bootstrap.sh
> Core: Add MAVLink2Rest

- core/services/versionchooser/static/index.html
- core/services/versionchooser/static/style.css
The process can take a few seconds. The spinner lets the user know that something is happening in the background.
> Core: add a spinner when fetching images

- core/services/install-services.sh
Helps #277 (by making it fail not-silently).
> Use set -e on install-services.sh

- core/Dockerfile
- core/start-companion-core
- core/tools/ttyd/bootstrap.sh
fix #235 
it would be cool to have a motd with basic tmux usage
> Add ttyd service

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/firmware_download/FirmwareDownload.py
- core/services/ardupilot_manager/flight_controller_detector/Detector.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
- core/services/ardupilot_manager/mavlink_proxy/main.py
- core/services/ardupilot_manager/settings.py
- core/services/ardupilot_manager/setup.py
- Move "prints" and "warns" to logging when appropriate 
- Make logging output non-verbose by default
- Add option to use verbose output with -v.
> core: ardupilot-manager: Add proper logging

- core/Dockerfile
- core/configuration/tmux.conf
- core/start-companion-core
> Core: Add tmux configuration file

- core/services/versionchooser/utils/dockerhub.py
Oops.
As we already filter the architecture in fetch_remote_tags(), the digest we have
is already for the correct image. This way we don't need to use the fat manifest
at all.
The correct fix all along was to use the digest to fetch the sha.
fix #280
> core: versionchooser: use the previously existing digest instead of re-fetching.

- core/services/versionchooser/static/index.html
> Version chooser: Change "local changes" to "out of sync" and add update button

- core/services/ardupilot_manager/ArduPilotManager.py
If ArduPilot fails or reboots it'll be restarted.
Fix #170 
> core: ardupilot-manager: Run ArduPilot inside while loop

- .github/workflows/tests.yml
> CI: use the same version of mavlink-router used in deployment

- core/tools/mavlink_camera_manager/bootstrap.sh
due to https://github.com/patrickelectric/mavlink-camera-manager/issues/6
> Core: temporary revert mavlink-camera-manager to t3.0.1

- .github/workflows/deploy.yml
> [WIP] CI: deploy: Add check for core size

- core/services/ardupilot_manager/firmware_download/FirmwareDownload.py
> Ardupilot Manager : add run permissions to binary before trying to validate firmware file

- .coveragerc
- .hooks/pre-push
- pyproject.toml
> pyproject: Add pytest integration

- core/Dockerfile
- core/libs/commonwealth/README.md
- core/libs/commonwealth/commonwealth/utils/apis.py
- core/libs/commonwealth/commonwealth/utils/logs.py
- core/libs/commonwealth/setup.py
- core/libs/install-libs.sh
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/setup.py
- core/services/cable_guy/main.py
- core/services/cable_guy/setup.py
- core/services/helper/main.py
- core/services/helper/setup.py
- core/services/install-services.sh
- core/services/wifi/main.py
- core/services/wifi/setup.py
The Commonwealth of Services, generally known simply as the Commonwealth, is a technological association of Companion services to share common knowledge.
> Introducing `commonwealth`

- core/services/cable_guy/api/manager.py
- core/services/cable_guy/main.py
Fix #286 
Default config is static IP `192.168.2.2` on interface `eth0`.
> core: cable_guy: Use default config when no settings file is found

- core/Dockerfile
- core/libs/commonwealth/commonwealth/utils/DHCPServerManager.py
- core/services/cable_guy/api/manager.py
- core/services/cable_guy/api/settings/dnsmasq.conf
- core/services/cable_guy/html/index.html
- core/services/cable_guy/main.py
- core/services/cable_guy/setup.py
- core/tools/dnsmasq/bootstrap.sh
Fix #287 
- Add dnsmasq as DHCP Server provider
- Use 192.168.2.2 as gateway
- Offer IPs in the 192.168.2.100-200 range
- Changes default  GCS Link to 192.168.2.2
- Add proper logging to cable-guy
> Add DHCP Server to companion

- core/tools/mavlink_camera_manager/bootstrap.sh
Fix pipeline reset with Blue Robotics low light camera
Docker: patrickelectric/companion-core:mavlink-camera-manager-t3.0.4
> core: tool: mavlink_camera_manager: Update to t3.0.4

- core/services/versionchooser/main.py
- core/services/versionchooser/openapi/versionchooser.yaml
- core/services/versionchooser/static/index.html
- core/services/versionchooser/utils/chooser.py
an image for testing is available at williangalvani/companion-core:delete
> Implement delete button on versionchooser

- core/Dockerfile
- core/services/ardupilot_manager/frontend/index.html
- core/services/cable_guy/html/index.html
- core/services/helper/html/index.html
- core/services/helper/main.py
- core/services/versionchooser/static/index.html
- core/services/wifi/frontend/index.html
- core/start-companion-core
- core/tools/nginx/bootstrap.sh
- core/tools/nginx/nginx.conf
Image available at williangalvani/companion-core:nginx
services will be accessible both at the regular place and at /\<service-name\>/.
the trailing / is required for now (but that is fixeable via nginx).
some paths of static files had to be changed to relative paths so they work in a different url path.
it still needs cleaning, reorganization, and testing.  Let me know what you think.
(I will cleanup the .conf file, please don't worry about whitespaces or whatever there)
> Adding Nginx

- core/tools/mavlink2rest/bootstrap.sh
> core: mavlink2rest: Update version with relative URL calls

- core/services/install-services.sh
- core/tools/dnsmasq/bootstrap.sh
- core/tools/nginx/bootstrap.sh
This fix problems related to not updated mirrors
> Add apt update before calls of apt install

- core/tools/mavlink_camera_manager/bootstrap.sh
Fix problem relative to URL redirect with HTTP server
> core: mavlink-camera-manager: Update version with relative URL calls

- core/frontend/src/libs/MAVLink2Rest.ts
To test: patrickelectric/companion-core:mavlink2rest_ts
(you'll see MAV_TYPE_SUBMARINE at 10Hz)
Check console output, you'll see the attitude values. 
The code is the following:
```js
mavlink2rest.startListening('HEARTBEAT').setCallback((message) => {
console.log(message.mavtype.type)
}).setFrequency(10)
```
> core: frontend: libs: Add MAVLink2Rest library

- core/Dockerfile
Improve build speed using a different stage for it
Docker: patrickelectric/companion-core:multistage
> core: Dockerfile: Add multistage to download binaries

- .github/workflows/tests.yml
- core/libs/commonwealth/setup.py
- core/libs/install-libs.sh
> CI: Add missing libs installation for core

- core/Dockerfile
- core/services/helper/main.py
- core/start-companion-core
- core/tools/filebrowser/bootstrap.sh
Fix #236 
features list:
https://filebrowser.org/features
Thanks to @NickNothom for the reference
> core: Add FileBrowser

- .github/workflows/deploy.yml
Decrease limit from 750MB to 700MB
> CI: deploy: Decrease docker size limit

- core/tools/linux2rest/bootstrap.sh
> core: linux2rest: Update version with relative URL calls

- core/services/versionchooser/.gitignore
Ignore static files for frontend downloaded by setup.py
> core: version-chooser: Add gitignore

- core/frontend/package.json
- core/frontend/src/App.vue
- core/frontend/src/components/scanner/availableServicesTable.vue
- core/frontend/src/components/scanner/servicesScanner.vue
- core/frontend/src/store/index.ts
- core/frontend/src/store/servicesScanner.ts
- core/frontend/src/types/SERVICE.d.ts
- core/frontend/src/views/MainView.vue
- core/frontend/tsconfig.json
- core/frontend/yarn.lock
questions:
make it not as wide? I don't like my current solution.
is src/components a good place for the component?
is it worth declaring an interface to remove the "anys" in there?
image coming soon to a docker registry near you. (williangalvani/companion-core:helper)
> Add Service Scanner to frontend

- core/Dockerfile
Decrease the compressed imagem by half and the final image by almost 1/3 
Companion core based over this PR: patrickelectric/companion-core:small_gst_desktop
> Update core to v0.0.2

- core/services/ardupilot_manager/setup.py
- core/services/versionchooser/setup.py
- core/services/wifi/setup.py
Fix build to detect missing static files
> Force error when failing to download static files

- core/frontend/package.json
- core/frontend/src/App.vue
- core/frontend/src/components/notifications/ConfigMenu.vue
- core/frontend/src/components/notifications/NotificationCard.vue
- core/frontend/src/components/notifications/NotificationManager.vue
- core/frontend/src/components/notifications/TrayButton.vue
- core/frontend/src/components/scanner/servicesScanner.vue
- core/frontend/src/store/notifications.ts
- core/frontend/src/types/common.ts
- core/frontend/src/types/frontend_services.ts
- core/frontend/src/types/notifications.ts
- core/frontend/yarn.lock
Allows services to push notifications and add a notification manager to the top-left corner.
Image available at: `rafaellehmkuhl/companion-core:notifications`
> Add notification system

- core/start-companion-core
- core/tools/nginx/nginx.conf
> core: Add docker REST API access 

- core/start-companion-core
- Fix order of configuration file parameter for tmux server
- Set necessary local environment variables for all services
patrickelectric/companion-core:improve_start
> core: Improve start script

- install/network/companion.service
> install: network: Add txt-record fields in avahi configuration for GCS connection

- core/frontend/src/components/scanner/availableServicesTable.vue
> core: frontend: scanner: Fix viewer for services and documentation

- .github/workflows/deploy.yml
> CI: deploy: Update size limit to 450MB

- core/tools/mavlink2rest/bootstrap.sh
This version contains the documentation endpoint
Image: patrickelectric/companion-core:update_mavlink2rest0.11.6
> core: tools: mavlink2rest: Update to the latest version

- .eslintrc.js
- core/frontend/src/App.vue
- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/frontend/src/router/index.ts
- core/frontend/src/store/autopilot.ts
- core/frontend/src/types/autopilot.ts
- core/frontend/src/types/frontend_services.ts
- core/frontend/src/views/FirmwareView.vue
Image available at `rafaellehmkuhl/companion-core:firmware-frontend`.
> Firmware on the frontend

- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
> core: ardupilot-manager: Log router command being used

- core/frontend/src/App.vue
- core/frontend/src/router/index.ts
- core/frontend/src/views/FileBrowserView.vue
- core/frontend/src/views/TerminalView.vue
- core/frontend/src/views/VersionChooser.vue
Embed the following tools on the main frontend as dedicated views:
- File-browser
- Terminal
- Version-chooser
> Add tools views

- core/frontend/src/components/autopilot/EndpointManager.vue
- core/frontend/src/components/common/SpinningLogo.vue
- core/frontend/src/components/ethernet/EthernetManager.vue
- core/frontend/src/components/logs/LogManager.vue
- core/frontend/src/components/wifi/WifiManager.vue
Allow components to specify spinning-logo size.
> core: frontend: Allow custom spinning-logo size

- core/frontend/src/App.vue
- core/frontend/src/components/autopilot/AutopilotManagerUpdater.vue
- core/frontend/src/components/autopilot/EndpointManager.vue
- core/frontend/src/router/index.ts
- core/frontend/src/store/autopilot_manager.ts
- core/frontend/src/types/autopilot.ts
- core/frontend/src/views/GeneralAutopilot.vue
- core/services/ardupilot_manager/ArduPilotManager.py
Contains current running platform as well as a button to restart the autopilot.
Fix #445
> Add autopilot general view

- core/tools/mavlink_camera_manager/bootstrap.sh
Add swagger documentation
Available on: patrickelectric/companion-core:mavlink_camera_manager_t3.0.8
> core: tools: mavlink_camera_manager: Update to t3.0.8

- .github/workflows/deploy.yml
> CI: deploy: Increase core size limit to 500MB

- core/services/versionchooser/frontend/index.html
image available at williangalvani/companion-core:fixversionchooser
I'm unable to test right now due to rate-limiting
> Fix embedded version-chooser

- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/exceptions.py
- core/services/ardupilot_manager/firmware/FirmwareManagement.py
- core/services/ardupilot_manager/firmware/FirmwareUpload.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_comm/MavlinkComm.py
- core/services/ardupilot_manager/settings.py
- core/services/ardupilot_manager/setup.py
> ardupilot-manager: Add default firmwares and allow restoring

- core/tools/linux2rest/bootstrap.sh
- Add openapi and swagger endpoint
> core: tools: linux2rest: Update to v0.1.8

- core/frontend/src/App.vue
- core/frontend/src/components/ethernet/EthernetManager.vue
- core/frontend/src/components/ethernet/EthernetTrayMenu.vue
- core/frontend/src/components/wifi/NetworkCard.vue
- core/frontend/src/components/wifi/WifiManager.vue
- core/frontend/src/components/wifi/WifiTrayMenu.vue
- core/frontend/src/utils/wifi.ts
Docker: patrickelectric/companion-core:icons
> core: frontend: Update panel icons based on the wifi signal strength and ethernet connection status

- core/frontend/package.json
- core/frontend/src/App.vue
- core/frontend/src/components/health/HealthTrayMenu.vue
- core/frontend/src/components/mavlink/MavlinkUpdater.vue
- core/frontend/src/libs/MAVLink2Rest/index.ts
- core/frontend/src/store/mavlink.ts
- core/frontend/src/types/common.ts
- core/frontend/src/types/frontend_services.ts
- core/frontend/src/types/mavlink.ts
- core/frontend/src/utils/mavlink.ts
- core/frontend/yarn.lock
Docker: patrickelectric/companion-core:health
> Health indicator: Revolution 

- core/frontend/src/App.vue
- core/frontend/src/router/index.ts
- core/frontend/src/views/AvailableServicesView.vue
- core/frontend/src/views/MainView.vue
Fix #574 
Docker: patrickelectric/companion-core:welcome_page
> Improve welcome page and move available services under tools menu

- core/frontend/src/components/video-manager/VideoManager.vue
> core: frontend: Sort video devices by name

- core/services/versionchooser/frontend/index.html
- core/services/versionchooser/main.py
- core/services/versionchooser/setup.py
- core/services/versionchooser/test_versionchooser.py
- core/services/versionchooser/utils/chooser.py
- core/tools/nginx/nginx.conf
williangalvani/companion-core:async-chooser
> Make version-chooser properly async

- core/frontend/src/components/video-manager/VideoDevice.vue
- core/frontend/src/components/video-manager/VideoManager.vue
- core/frontend/src/components/video-manager/VideoStream.vue
- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
- core/frontend/src/store/video.ts
- core/frontend/src/types/video.ts
> Allow stream edit

- core/libs/commonwealth/commonwealth/utils/decorators.py
> core: lib: commonwealth: Fix comment temporary_cache

- bootstrap/main.py
> bootstrap: Update helper with correct docker name

- core/services/ping/pingdriver.py
Ping1D hangs with such high baudrates
Fix #357
> core: services: ping: Do not use baudrates over 3M

- deploy/github-runner/RAEDME.md
- deploy/github-runner/companion-runner.sh
- deploy/pimod/README.md
- deploy/pimod/companion.Pifile
github-runner: Script to run a github self hosted runner on the raspberry for CI
pimod: Create .img files for companion based on the Pifile description
> deploy: Add github-runner and pimod files

- core/services/ardupilot_manager/exceptions.py
- core/services/ardupilot_manager/firmware/FirmwareDownload.py
> core: services: ardupilot_manager: Add NoCandidate error

- .eslintrc.js
- core/frontend/src/components/video-manager/VideoControlsDialog.vue
- core/frontend/src/components/video-manager/VideoUpdater.vue
- core/frontend/src/store/video.ts
- core/frontend/src/types/video.ts
Adds support for disabled/inactive controls
Fix #494 
To be merged after #650
> Support disabled/inactive controls

- core/services/versionchooser/frontend/index.html
- core/services/versionchooser/main.py
- core/services/versionchooser/openapi/versionchooser.yaml
- core/services/versionchooser/utils/chooser.py
- core/tools/nginx/nginx.conf
Fix #285 
Available on: patrickelectric/companion-core:offline-version-chooser
> core: version chooser: Add option to upload docker image files

- core/frontend/src/components/common/SpinningLogo.vue
- core/frontend/src/components/utils/iframe.vue
- core/frontend/src/views/FileBrowserView.vue
- core/frontend/src/views/TerminalView.vue
- core/frontend/src/views/VersionChooser.vue
> core: frontend: Add loading icon with iframe

- core/frontend/src/libs/filebrowser.ts
The token takes time to be received, we need to await for it
- Fix #665 
- docker: docker.io/patrickelectric/companion-core:fix_filebrowser
> core: libs: filebrowser: Fix token request

- core/frontend/src/components/logs/LogManager.vue
> core: frontend: components: logs: Stop loading if folders does not exist

- core/frontend/src/components/logs/LogManager.vue
- core/frontend/src/libs/filebrowser.ts
- Add some missing async/await updates from #669
> core: frontend: filebrowser: Add missing async/await

- install/install.sh
> install: Update script to add supported architectures

- core/services/ping/main.py
- core/services/ping/pingdriver.py
- core/services/ping/pingmanager.py
- core/services/ping/pingutils.py
- core/services/ping/setup.py
- core/services/ping/typedefs.py
- Fix #652 
- docker: patrickelectric/companion-core:ping_rest
> core: ping: Add REST API

- core/frontend/src/components/video-manager/VideoUpdater.vue
- core/frontend/src/components/wifi/ConnectionDialog.vue
- core/frontend/src/components/wifi/WifiManager.vue
- core/frontend/src/components/wifi/WifiUpdater.vue
- core/frontend/src/types/wifi.ts
> Small frontend fixes

- core/tools/logviewer/bootstrap.sh
- Improve underwater rendering
- Fix issue with height being rendered wrongly
- Create deviceIdViewer
- Fix using quaternion
- Fix issue with plotting some expressions
> Core: Bump logviewer to 0.9.6

- core/Dockerfile
> core: Dockerfile: Update to companion-base:v0.0.3

- core/frontend/src/components/ethernet/InterfaceCard.vue
> Validate inputed IP on ethernet frontend

- core/Dockerfile
> core: Dockerfile: Update to companion-base:v0.0.4

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/firmware/FirmwareManagement.py
> Validate firmwares before running

- core/frontend/src/components/notifications/NotificationCard.vue
- core/frontend/src/components/notifications/NotificationManager.vue
> core: frontend: Expand notification message on click

- core/services/ardupilot_manager/ArduPilotManager.py
Image already available.
Fix #710
> Persistent default endpoints

- core/frontend/src/components/app/SettingsMenu.vue
- core/frontend/src/libs/settings.ts
- core/frontend/src/store/settings.ts
> Add settings system on frontend

- core/tools/mavlink_camera_manager/bootstrap.sh
> core: tools: mavlink_camera_manager: Update github url

- .github/workflows/deploy.yml
> github: deploy: Deploy projects also as blueos-*

- core/frontend/package.json
- core/frontend/src/components/app/BackendStatusChecker.vue
- core/frontend/src/store/settings.ts
- core/frontend/src/types/common.ts
- core/frontend/src/types/frontend_services.ts
- core/frontend/src/views/MainView.vue
- core/frontend/vue.config.js
> core: frontend: Rename project to use new BlueOS name

- core/tools/mavlink_camera_manager/bootstrap.sh
docker image (updated to 3.1.1): `patrickelectric/companion-core:update_mavlink_camera_manager_3_1_0`
[changelog](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.1.1)
> core: tools: mavlink_camera_manager: Update to version t3.1.1

- bootstrap/bootstrap/bootstrap.py
- bootstrap/test_bootstrap.py
Any thoughts on what happened to our image size?
> bootstrap: generalize for multiple containers

- core/frontend/vue.config.js
This makes easy to change the address when necessary for testing
> frontend: vue.config: Set single variable for server address

- core/services/versionchooser/setup.py
Temporary solution for jsonchema support
From: https://github.com/zalando/connexion/pull/1447
Fix: https://github.com/zalando/connexion/issues/1430
> core: services: versionchooser: Fix connexion version

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
- core/frontend/src/store/video.ts
- core/frontend/src/utils/pattern_validators.ts
- core/tools/mavlink_camera_manager/bootstrap.sh
Docker: patrickelectric/companion-core:camera_manager_3_2_1
Fix #738
> core: tools: mavlink_camera_manager: Update to version t3.2.1

- core/frontend/src/App.vue
- core/frontend/src/components/app/ErrorMessage.vue
- core/frontend/src/libs/error-message.ts
- core/frontend/src/store/video.ts
Fix #744 
docker: patrickelectric/companion-core:add_error_message
How to test: Add a rtsp endpoint with a port that is not 8554
> frontend: Add error message displayer 

- core/frontend/src/App.vue
- core/frontend/src/utils/helper_functions.ts
Docker: patrickelectric/companion-core:add_href_version
> src: App: Add href for git_info

- core/frontend/src/utils/helper_functions.ts
Add check for undefined string
> core: utils: helper_functions: Fix convertGitDescribeToUrl

- .github/workflows/tests.yml
- core/services/versionchooser/main.py
- pyproject.toml
Latest version include fix for uncorrect dependency version on `click` package
> core: Update `black` to latest version

- .github/workflows/tests.yml
- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/exceptions.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
- core/services/ardupilot_manager/mavlink_proxy/MAVProxy.py
- core/services/ardupilot_manager/mavlink_proxy/Manager.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
- core/services/versionchooser/main.py
- pyproject.toml
- Move endpoint-handling logic to the MavLink Manager class
- Fix master endpoint logic
- Improve error-handling and logging (remove unnecessary logging)
> Refactor mavlink-manager related code

- core/frontend/src/components/video-manager/VideoStream.vue
- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
- core/frontend/src/types/video.ts
- core/tools/mavlink_camera_manager/bootstrap.sh
- Add thermal option
docker: patrickelectric/bootstrap:camera-manager-3-3-0
> Update camera manager to t3.3.0

- core/services/versionchooser/test_versionchooser.py
we were missing the organization name in the mocked data.
> core: version-chooser: update tests

- core/frontend/package.json
- core/frontend/src/App.vue
- core/frontend/src/components/app/ReportMenu.vue
- core/frontend/src/plugins/vuetify.ts
> core: frontend: Add feedback button 

- .github/workflows/tests.yml
- core/libs/commonwealth/commonwealth/settings/manager.py
- core/libs/commonwealth/commonwealth/settings/settings.py
- core/libs/commonwealth/commonwealth/settings/tests/test_manager.py
- core/libs/commonwealth/commonwealth/settings/tests/test_settings.py
- core/libs/commonwealth/setup.py
- core/services/bridget/bridget.py
- core/services/bridget/settings.py
- pyproject.toml
docker: patrickelectric/companion-core:commonwealth_settings
Fix #707
> core: Commonwealth : Add settings

- core/services/versionchooser/frontend/index.html
- core/services/versionchooser/utils/chooser.py
Fix #765 
Fix #757
image building to williangalvani/companion-core:version-chooser-errors
> core: version-chooser: expose dockerhub errors to user

- core/frontend/.gitignore
It also helps the IDE to figure out where to search or not
> core: frontend: Update gitignore with yarn files

- .github/ISSUE_TEMPLATE/ui-corrections.yml
Github issue template for UI/UX requests
> github: template: Add ui-corrections

- .github/ISSUE_TEMPLATE/bugs.yml
Github issue template to report a bug
> github: template: Add bugs

- core/frontend/src/components/app/ReportMenu.vue
The category now has a new name and category_id
> core: frontend: ReportMenu: Update category_id

- core/frontend/package.json
- core/frontend/src/components/autopilot/EndpointCard.vue
- core/frontend/src/components/common/DefaultTooltip.vue
- core/frontend/src/main.ts
- core/frontend/src/types/shims-general.ts
- core/frontend/yarn.lock
- Add tooltip-as-directive lib
- Add tooltips on EndpointCard
> Add tooltips

- core/frontend/src/components/health/HealthTrayMenu.vue
- core/frontend/src/store/mavlink.ts
- core/frontend/src/store/system-information.ts
- core/frontend/src/types/mavlink.ts
- core/frontend/src/types/system-information/platform.ts
We can use different formula and behavior.
Thougths?
> core: frontend: animate heart icon with vehicle heartbeats, show warning icons for high temperature and disk usage

- core/frontend/src/components/version-chooser/VersionChooser.vue
> core: frontend: components: version-chooser: Fix typo

- core/frontend/src/components/version-chooser/VersionCard.vue
Makes it easier for people where english is not the main language
> core: frontend: components: VersionCard: Change from pull to download

- core/frontend/src/components/app/PowerMenu.vue
> core: frontend: components: PowerMenu: Fix layout and add text for icons

- core/frontend/src/App.vue
> core: frontend: App: Disable submenus when pirate mode is off

- core/frontend/src/App.vue
> core: frontend: App: Change menu title from Autopilot to Vehicle

- core/frontend/src/components/app/SettingsMenu.vue
> core: frontend: components: SettingsMenu: Use better icons for reset settings

- core/libs/commonwealth/commonwealth/utils/DHCPServerManager.py
- core/services/cable_guy/api/settings.py
- core/services/cable_guy/main.py
Fix #824 by using the `--test` argument on `dnsmasq` binary check.
> core: cable-guy: Fix increasing number of `dnsmasq` processes

- core/frontend/src/store/system-information.ts
> core: frontend: store: system-information: Remove debug messages

- core/frontend/src/store/system-information.ts
- core/tools/linux2rest/bootstrap.sh
> Update linux2rest to 0.2.0

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
> core: frontend: add udp and rtsp in the video endpoint placeholder

- core/frontend/src/libs/filebrowser.ts
> core: frontend: libs: filebrowser: Remove unnecessary variable

- core/frontend/src/components/video-manager/VideoManager.vue
> core: frontend: hide fake streams when not in pirate mode

- core/frontend/src/components/health/HealthTrayMenu.vue
> core: frontend: fix disk_usage_percent calculation

- core/frontend/src/components/health/HealthTrayMenu.vue
> core: frontend: components: health: Remove lost debug message

- core/Dockerfile
- core/tools/scripts/bootstrap.sh
- core/tools/scripts/red-pill
docker: patrickelectric/scripts
https://www.youtube.com/watch?v=zE7PKRjrid4
> core: Add command to go to the console outside docker

- core/configuration/motd
> core: configuration: motd: Add command to access the raspberry console

- core/frontend/src/App.vue
- core/frontend/src/router/index.ts
- core/frontend/src/types/frontend_services.ts
- core/frontend/src/views/NetworkTestView.vue
- core/frontend/vue.config.js
- core/services/pardal/README.md
- core/services/pardal/main.py
- core/start-companion-core
- core/tools/nginx/nginx.conf
docker: patrickelectric/companion-core:network_test
Helps #448
> core: Add network test

- core/frontend/src/components/app/PowerMenu.vue
- core/services/commander/main.py
docker: patrickelectric/commander_power
Fix #563 
Helps #850
> Fix shutdown/reboot

- install/install.sh
> install: install: Enable trace when running install via CI

- core/services/commander/main.py
docker: `patrickelectric/companion-core:command`
Fix #850
> core: commander: Allow sending arbitrary commands to host computer

- core/tools/nginx/nginx.conf
> core: tools: nginx: Update configuration file to allow blueos and companion

- core/frontend/src/components/health/HealthTrayMenu.vue
> components: health: Fix heartbeat icon to use only vehicle heartbeat

- core/frontend/src/App.vue
- core/frontend/src/components/app/UpdateTime.vue
- core/frontend/src/components/system-information/AboutThisSystem.vue
- core/frontend/src/types/frontend_services.ts
- core/frontend/src/types/system-information/system.ts
- core/frontend/src/views/SystemInformationView.vue
- core/services/commander/main.py
- core/tools/linux2rest/bootstrap.sh
Fix #74 
docker: patrickelectric/blueos-core:set_time
> Allow frontend to set system time

- .eslintrc.js
- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/types/version-chooser.ts
- core/frontend/src/utils/version_chooser.ts
Helps with #599 and #601 
docker: `patrickelectric/new_version_chooser_of_post_apocalyptic_armageddon`
> core: frontend: utils: Add version_chooser

- core/services/ardupilot_manager/ArduPilotManager.py
otherwise we can get ANYHTING from the system using mavftp
> Core: ArdupilotManager: change firmware cwd

- core/frontend/src/components/video-manager/VideoStream.vue
- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
- core/frontend/src/types/video.ts
Fix #867
Image available at `rafaellehmkuhl/blueos-core`
> frontend: video: Allow multiple IPs for each stream

- core/frontend/src/App.vue
- core/frontend/src/components/app/NewVersionNotificator.vue
- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/libs/settings.ts
- core/frontend/src/store/settings.ts
- core/frontend/src/utils/version_chooser.ts
> frontend: Add notificator when a new version is available

- core/frontend/src/components/version-chooser/VersionChooser.vue
text and multpart are failing, undefined works as expected
Fix #892
> core: frontend: componenets: version-chooser: Fix content-type for docker image file

- core/frontend/package.json
- core/frontend/src/App.vue
- core/frontend/src/components/app/PowerMenu.vue
- core/frontend/src/components/app/ReportMenu.vue
- core/frontend/src/components/app/SettingsMenu.vue
- core/frontend/src/components/ethernet/EthernetTrayMenu.vue
- core/frontend/src/components/notifications/TrayButton.vue
- core/frontend/src/components/wifi/WifiTrayMenu.vue
- core/frontend/src/libs/settings.ts
- core/frontend/src/main.ts
- core/frontend/src/store/settings.ts
- core/frontend/src/views/MainView.vue
- core/frontend/yarn.lock
This is an initial implementation. We can progressively add more in-depth tours on each component/service as we want.
Image available at `patrickelectric/blueos-core:add-tour`
> Add welcome tour

- core/frontend/src/App.vue
> core: frontend: App: Fix tour

- core/frontend/src/components/health/HealthTrayMenu.vue
- core/frontend/src/libs/MAVLink2Rest/Endpoint.ts
> Fix heartbeat

- core/frontend/src/libs/MAVLink2Rest/index.ts
> core: frontend: libs: mavlink2rest: Remove development message

- core/services/beacon/settings.py
Deals with this when disconnecting wifi:
Exception left broad intentionally, just in case there are other exceptions along the way.
> core: beacon: improve exception handling

- core/frontend/src/views/MainView.vue
> core: frontend: views: MainView: Improve visual

- core/frontend/src/App.vue
fix #915
Also stops scrolling to elements (was it doing it only for me?)/ and sets target to the last element so it has the same style as the others.
> Tour tweaks

- core/frontend/src/components/app/NewVersionNotificator.vue
- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/utils/version_chooser.ts
An error here means the data is incomplete, not necessarily absent.
> core: version-chooser: fix displaying error

- core/services/helper/main.py
- core/services/pardal/main.py
> core: services: pardal: Add root page

- core/frontend/src/App.vue
> core: frontend: App: Redirect page to use blueos.local

- core/tools/linux2rest/bootstrap.sh
> core: tools: linux2rest: Update version of v0.2.3

- core/frontend/src/components/autopilot/FirmwareManager.vue
> core: frontend: components: FirmwareManager: Disable firmware selection when fetching

- core/frontend/src/components/version-chooser/VersionChooser.vue
> frontend: version-chooser: Fix text color on pull dialog

- core/frontend/src/views/NetworkTestView.vue
> core: frontend: views: NetworkTestView: Move from await to finally

- core/frontend/src/components/autopilot/FirmwareManager.vue
Fix #938 
@patrickelectric @Williangalvani @ES-Alexander @joaoantoniocardoso please check the texts to see if they match what you think should be explained about each version.
> frontend: autopilot: Add information about each firmware version type

- core/frontend/src/components/system-information/AboutThisSystem.vue
- core/frontend/src/components/system-information/Kernel.vue
- core/frontend/src/components/system-information/Network.vue
- core/frontend/src/components/system-information/Processes.vue
- core/frontend/src/components/system-information/SystemCondition.vue
- core/frontend/src/store/system-information.ts
- core/tools/linux2rest/bootstrap.sh
- Use multiple endpoints and fetch data only when necessary for each page
- It should fix #883
docker: patrickelectric/blueos-core:update_system
> core: frontend: system-information: Break system-information to use multiple endpoints

- core/frontend/src/components/autopilot/EndpointManager.vue
- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/frontend/src/components/logs/LogManager.vue
- core/frontend/src/components/video-manager/VideoManager.vue
Endpoints, before and after:
Video, before and after: 
Firmware, before and after:
Logs, before and after:
> Improve pages layout

- .hooks/pre-push
https://github.com/bluerobotics/BlueOS-docker/runs/5853419360?check_suite_focus=true#step:6:24
https://github.com/bluerobotics/BlueOS-docker/actions/runs/2103316912
> hooks: Fix missing coverage report in pytest

- core/frontend/src/components/wifi/NetworkCard.vue
- core/frontend/src/components/wifi/WifiManager.vue
> frontend: wifi: Display ip address on network card (if available)

- core/frontend/src/components/system-information/Processes.vue
> core: frontend: components: system-information: Processes: Remove debug message

- core/frontend/src/App.vue
> core: frontend: Improve main menu for small and big screens 

- core/libs/commonwealth/commonwealth/utils/apis.py
- core/libs/commonwealth/commonwealth/utils/logs.py
- core/services/ardupilot_manager/firmware/FirmwareInstall.py
- core/services/ardupilot_manager/firmware/FirmwareManagement.py
- core/services/ardupilot_manager/firmware/FirmwareUpload.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
Error received for duplicated name, before and after:
Error received for duplicated parameters, before and after:
Fix #975
> Specify ardupilot errors

- core/frontend/src/components/autopilot/EndpointManager.vue
- core/frontend/src/components/bridges/Bridget.vue
- core/frontend/src/components/common/SpinningLogo.vue
- core/frontend/src/components/ethernet/EthernetManager.vue
- core/frontend/src/components/logs/LogManager.vue
- core/frontend/src/components/nmea-injector/NMEAInjector.vue
- core/frontend/src/components/utils/iframe.vue
- core/frontend/src/components/version-chooser/VersionCard.vue
- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/components/video-manager/VideoDevice.vue
- core/frontend/src/components/video-manager/VideoManager.vue
- core/frontend/src/components/wifi/WifiManager.vue
> Subtitle on spinning logo

- core/frontend/src/store/system-information.ts
- core/tools/linux2rest/bootstrap.sh
Fix kernel log behavior and performance
[changelog](https://github.com/patrickelectric/linux2rest/releases/tag/v0.3.0)
docker: patrickelectric/blueos-core:pull
ref: #932
> core: Update linux2rest to v0.3.0

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
> frontend: video: Add warning when creating streams from 'Fake source'

- core/Dockerfile
- core/tools/install-static-binaries.sh
- core/tools/install-system-tools.sh
- Uses new parallel function to help with tools installation
docker: patrickelectric/update_docker_build
> core: Update dockerfile to use new base v0.0.5

- core/libs/commonwealth/commonwealth/utils/tests/test_decorators.py
Add initial test for decorators
> core: libs: commonwealth: utils: Add test folder

- core/frontend/src/App.vue
- core/frontend/src/components/beacon/BeaconTrayMenu.vue
- core/frontend/src/store/beacon.ts
- core/frontend/src/types/beacon.ts
- core/frontend/src/types/frontend_services.ts
- core/frontend/vue.config.js
- core/services/beacon/main.py
- core/services/beacon/typedefs.py
- core/tools/nginx/nginx.conf
image is up at williangalvani/blueos-core:beaconip
you should see something like this when connecting via blueos-wifi.local:
and an additonal button to switch to a wired connection if one is detected
> Detect wifi connections and show available wired connections when possible

- core/services/ardupilot_manager/ArduPilotManager.py
> ArdupilotManager: log command line used to launch ardupilot linux

- core/libs/bridges/bridges/bridges.py
- core/services/bridget/bridget.py
- core/tools/bridges/bootstrap.sh
- Allow multiple clients connected 
- Allow usage of by-path and by-id inputs
> Update to use new bridges 0.8.1

- core/tools/mavlink_camera_manager/bootstrap.sh
> core: tools: mavlink-camera-manager: Remove temporary files

- .github/workflows/test-and-deploy.yml
Previous version is not working anymore
> CI: Use latest actions-yarn action

- core/Dockerfile
> core: Update base image to v0.0.6

- core/frontend/src/App.vue
> core: frontend: Change code from extensions to packages

- README.md
Probably a good idea to add more stuff here more generally, but this is at least a step forwards for now.
> README: add docs link

- core/services/beacon/main.py
not tested. should fix the zerotier problem
> core: beacon: add missing try/catch block

- core/frontend/src/components/app/NewVersionNotificator.vue
> core: frontend: components: NewVersionNotificator: Notify user about new versions once a day

- core/services/bridget/bridget.py
Logs were missing or inconsistent, making debug confuse.
> bridget: Fix some inconsistent logs

- core/services/ardupilot_manager/firmware/FirmwareInstall.py
- core/services/ardupilot_manager/flight_controller_detector/board_identification.py
- core/services/ardupilot_manager/typedefs.py
> ardupilot-manager: Add support for Pixhawk CubeOrange board

- core/tools/mavlink_camera_manager/bootstrap.sh
> core: tools: mavlink-camera-manager: Update to t3.5.0

- core/tools/linux2rest/bootstrap.sh
For more information about the changes: https://github.com/patrickelectric/linux2rest/releases/tag/v0.4.1
patrickelectric/blueos-core:linux2rest_update_v0.4.0
> core: tools: linux2rest: Update to v0.4.1

- core/tools/bridges/bootstrap.sh
For more information about this version: https://github.com/patrickelectric/bridges/releases/tag/0.8.1
> core: tools: bridges: Update to 0.8.1

- core/frontend/src/components/app/ReportMenu.vue
- core/frontend/src/components/autopilot/AutopilotManagerUpdater.vue
- core/frontend/src/components/health/HealthTrayMenu.vue
- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/components/video-manager/VideoStream.vue
- core/frontend/src/store/beacon.ts
- core/frontend/src/utils/update_time.ts
> core: frontend: Remove unused imports and variables

- core/frontend/src/components/bridges/BridgeCard.vue
- core/frontend/src/components/bridges/BridgeCreationDialog.vue
- core/frontend/src/components/bridges/Bridget.vue
- core/frontend/src/store/system-information.ts
- core/frontend/src/types/bridges.ts
- core/frontend/src/types/system-information/serial.ts
- core/tools/linux2rest/bootstrap.sh
- Use `/dev/serial/by-path` when available over `/dev/{device}`
- Docker: patrickelectric/blueos-core:update_bridges_interface
> Update bridges interface

- core/tools/mavlink_camera_manager/bootstrap.sh
for more information about the new version:
https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.6.0
docker: patrickelectric/blueos-core:update_mavlink_camera_manager_3_6_0
> core: tools: mavlink-camera-manager: Update to t3.6.0

- core/frontend/src/views/NetworkTestView.vue
> core: frontend: views: NetworTestView: Add result alert

- core/frontend/src/views/NetworkTestView.vue
Makes it more clear what download and upload are
> core: frontend: views: NetworTestView: Improve state text

- core/frontend/src/components/video-manager/VideoManager.vue
- core/frontend/src/store/video.ts
Waiting for a new version of mavlink-camera-manager :ok: 
> core: frontend: components: video-manager: Add reset stream settings button

- core/Dockerfile
> core: Dockerfile: Use new blueos-base:v0.0.7

- core/frontend/src/assets/css/animations.css
- core/frontend/src/components/version-chooser/VersionCard.vue
- core/frontend/src/main.ts
From this
To this
And from this
To this
Fix #1027 
Fix #1071
> Fix version chooser layout

- core/frontend/src/views/MainView.vue
> core: frontend: views: MainView: Improve welcome message

- core/frontend/src/components/video-manager/VideoManager.vue
- core/services/commander/main.py
- install/install.sh
> Allow user to enable raspberry camera legacy mode

- core/tools/linux2rest/bootstrap.sh
About the new version: https://github.com/patrickelectric/linux2rest/releases/tag/v0.4.4
Fix the problem related to weird cpu usage numbers 
> core: tools: linux2rest: Update to use v0.4.4

- core/frontend/src/App.vue
Reverts bluerobotics/BlueOS-docker#1053
> Revert "core: frontend: Change code from extensions to packages"

- core/services/wifi/WifiManager.py
PRs #1096 and #1098 successfully fixed previous the problem related on #1097. This new PR adds some small improvements to prevent undesirable behaviors.
> wifi-manager: Hotspot improvements

- .hooks/pre-push
> hooks: pre-push: Add tag format check

- core/tools/linux2rest/bootstrap.sh
For more information: https://github.com/patrickelectric/linux2rest/releases/tag/v0.4.5
Fix #1101 
> core: tools: linux2rest: Update to use v0.4.5

- core/libs/bridges/bridges/bridges.py
I dream on a day where Python std will have type hints
I dream on a day without daily errors footprints
I dream on a day where Python will have a good documentation with types
I dream on a day with peace in my mind
Before:
After:
> core: bridges: Fix check for error message

- core/tools/linux2rest/bootstrap.sh
Helps with #1115 
[v0.4.6 release notes](https://github.com/patrickelectric/linux2rest/releases/tag/v0.4.6)
> core: tools: linux2rest: Update to use v0.4.6

- core/frontend/src/components/bridges/BridgeCreationDialog.vue
- core/tools/bridges/bootstrap.sh
Fix #1113
- Chagelog for bridges [0.9.0](https://github.com/patrickelectric/bridges/releases/tag/0.9.0)
> Add client mode in bridges

- core/tools/mavlink_camera_manager/bootstrap.sh
[Pre-Release t3.6.2](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.6.2)
> core: tools: mavlink-camera-manager: Update to t3.6.2

- core/frontend/src/components/autopilot/EndpointCreationDialog.vue
helps https://github.com/bluerobotics/BlueOS-docker/issues/1052
> core: frontend: help fill ip address for autopilot endpoints

- core/frontend/src/components/video-manager/VideoDiagnosticHelper.vue
- core/frontend/src/components/video-manager/VideoManager.vue
> core: frontend: create VideoDiagnosticHelper.vue

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
- core/frontend/src/types/video.ts
[Screencast from 25-08-2022 13:30:09.webm](https://user-images.githubusercontent.com/4013804/186720248-cc629741-692c-453a-946d-c90d6b082bca.webm)
depends on #1122
helps #1052
> core: frontend: make streamtype an enum and pre-fill stream urls

- bootstrap/bootstrap/bootstrap.py
> bootstrap: bootstrap: Add missing timeout for requests.get

- core/frontend/src/components/autopilot/EndpointCreationDialog.vue
- core/frontend/src/components/video-manager/VideoStream.vue
> core: frontend: Minor frontend changes (support team requests)

- core/tools/nginx/nginx.conf
image up at williangalvani/blueos-core:fixlogviewer.
> core: tools: nginx: fix logviewer entry

- core/frontend/src/views/MainView.vue
> core: frontend: Fix broken links on welcome page

- core/libs/commonwealth/commonwealth/settings/settings.py
- core/libs/commonwealth/commonwealth/settings/tests/test_settings.py
- core/libs/commonwealth/setup.py
- core/services/beacon/settings.py
Enforce that all fields are derivated from Pykson.Field
> Update settings test and fix settings definition in commonwealth

- core/libs/commonwealth/setup.py
- core/services/beacon/main.py
- core/services/beacon/settings.py
> Fix beacon behaviour in hotspot (replaces #1139)

- core/frontend/src/App.vue
- core/frontend/src/router/index.ts
- core/frontend/src/views/ExtensionView.vue
I don't know why it seems to be refreshing the page, though. thoughts?
> Create ExtensionView, show extensions in Iframe

- core/libs/commonwealth/commonwealth/utils/Singleton.py
- core/services/beacon/main.py
- pyproject.toml
Ruff had some updates that added some new checks that are [causing our actions to fail](https://github.com/bluerobotics/BlueOS-docker/actions/runs/3162433305/jobs/5149017220).
This PR fixes and/or ignores the newly raised errors as relevant.
> Fix ruff errors

- core/frontend/package.json
- core/frontend/src/App.vue
- core/frontend/src/components/kraken/ExtensionCard.vue
- core/frontend/src/components/kraken/ExtensionModal.vue
- core/frontend/src/menus.ts
- core/frontend/src/router/index.ts
- core/frontend/src/types/frontend_services.ts
- core/frontend/src/types/kraken.ts
- core/frontend/src/views/ExtensionManagerView.vue
- core/frontend/src/views/ExtensionView.vue
- core/frontend/vue.config.js
- core/frontend/yarn.lock
- core/services/install-services.sh
- core/services/kraken/extension.py
- core/services/kraken/kraken.py
- core/services/kraken/main.py
- core/services/kraken/settings.py
- core/services/kraken/setup.py
- core/start-blueos-core
- core/tools/nginx/nginx.conf
This is my proposal of an extensions manager. It is written to work together with https://github.com/Williangalvani/BlueOS-extensions-repository
There are some unsolved problems:
And some features that will come later
The goal is to make these as incremental changes in subsequent PRs
> Create the Kraken

- core/Dockerfile
- core/frontend/src/App.vue
- core/frontend/src/components/app/PowerMenu.vue
- core/services/bridget/main.py
- core/start-blueos-core
Fix some old references/comments that have been left around.
> Companion purge

- core/frontend/src/components/utils/PullProgress.vue
- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/utils/pull_tracker.ts
This will be used by the Kraken aswell
> core: frontend: version-chooser: refactor docker pull output

- core/frontend/src/components/utils/PullProgress.vue
- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/utils/pull_tracker.ts
- core/frontend/src/views/ExtensionManagerView.vue
https://user-images.githubusercontent.com/4013804/196457525-f8a8fa54-2056-40c5-9be4-befa993377ca.mov
> Progressbar on docker pull

- core/frontend/src/types/kraken.ts
- core/frontend/src/views/ExtensionManagerView.vue
- core/services/kraken/main.py
> core: frontend: extensionmanager: show status for installed extensions

- core/frontend/package.json
- core/frontend/src/main.ts
- core/frontend/src/types/json-viewer.d.ts
- core/frontend/src/views/ExtensionManagerView.vue
- core/frontend/yarn.lock
https://user-images.githubusercontent.com/4013804/196598770-fdd57e5d-6f7e-41d9-9b1e-902c9671f566.mov
> Extension Manager: show permissions as json tree

- core/frontend/src/views/ExtensionManagerView.vue
- core/services/kraken/kraken.py
- core/services/kraken/main.py
https://user-images.githubusercontent.com/4013804/196813004-b88c0c5d-90dc-4df1-aba9-142ef481a6f0.mov
There's room for improvement, but I think this is a nice start.
I want to make it stream the data live, and interpret colors properly, in other PRs
> Allow displaying logs of running extensions 

- core/frontend/src/components/utils/PullProgress.vue
"persistent" was on the wrong element
> core: pullprogress: make it persistent

- core/frontend/src/views/ExtensionManagerView.vue
> core: frontend: views: ExtensionManagerView: Add getContainer

- core/frontend/package.json
- core/frontend/src/views/ExtensionManagerView.vue
- core/frontend/yarn.lock
> Add icons to Extension Manager

- core/services/kraken/kraken.py
> core: services: kraken: Fix typo

- core/frontend/src/components/mavlink-inspector/MavlinkInspector.vue
> core: frontend: components: MAVLinkInspector: Add filter for mavlink messages

- install/install.sh
Fixes for #1205 and an issue I didn't open related to missing default for `RUNNING_IN_CI`.
> Installer fixes

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> core: frontend: components: parameter-editor: Add progress bar

- core/frontend/src/components/version-chooser/VersionChooser.vue
Previous message was ambiguous and potentially confusing.
> core: version-chooser: improve switching message

- core/frontend/src/views/SystemInformationView.vue
Fix kernel icon after mdi update
> frontend: SystemInformationView: Fix kernel icon

- .github/workflows/test-and-deploy.yml
based on
https://github.com/actions/checkout/issues/758#issuecomment-1097027361
> CI: work around cloning submodules

- core/frontend/src/views/ExtensionManagerView.vue
- core/libs/commonwealth/commonwealth/utils/commands.py
- core/services/commander/main.py
- core/services/kraken/kraken.py
- core/services/kraken/main.py
- core/tools/blueos_startup_update/blueos_startup_update
- install/boards/bcm_27xx.sh
- install/boards/bcm_28xx.sh
I'm without time to create the UI, but I did a quick look of how to extract the data and get more familiar with the docker API. 
The memory report only works with cgroups enabled in cmdline. It'll be fixed in our future BlueOS images, and users could run the if check that'll update the line.
> kraken: Add cpu and memory status

- .gitmodules
> gitmodules: Update ArduPilot-Parameter-Repository user

- .gitmodules
Empower us to support older firmware versions
> core: Update ArduPilotParameter name and reference

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> core: components: parameter-editor: Fix check for selected bits on editor

- core/frontend/vue.config.js
> core: frontend: vue-config: Allow user to set proxy address via env variable

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> core: components: parameter-editor: Fix display of bitmask values

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> core: components: parameter-editor: Fix check for no input

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> core: components: parameter-editor: Use increment as step for parameter values

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> core: components: parameter-editor: Improve range information on parameter editor

- core/frontend/package.json
- core/frontend/src/components/parameter-editor/ParameterEditor.vue
- core/frontend/src/libs/MAVLink2Rest/index.ts
- core/frontend/yarn.lock
Needs to be merged after #1254
Fix #1211
> Allow loading parameter from file

- core/frontend/src/libs/MAVLink2Rest/index.ts
When settings multiple parameters on the vehicle we ended up doing more than 1200 posts call.
The server handle it but it's not a good thing to do, with the PR we are going to use the websocket to send all messages with it.
> Use websocket to send messages over post calls

- core/libs/commonwealth/setup.py
Still needs a new pykson release
> core: commonwealth: bump pykson to 1.0.2

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> core: frontend: make linter happy

- core/frontend/package.json
- core/frontend/src/components/parameter-editor/ParameterEditor.vue
- core/frontend/yarn.lock
https://user-images.githubusercontent.com/1215497/206900008-06662526-0e0d-480e-a81c-e9ce3da4a3bb.mp4
> parameter-editor: Add fuzzy finder

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
Check the case where 0 is a valid option
Fix #1276
> core: frontend: components: parameter-editor: Fix check for None in value

- core/frontend/src/components/mavlink-inspector/MavlinkInspector.vue
> core: frontend: components: MAVLinkInspector: Fix filter

- .eslintrc.js
- .github/workflows/test-and-deploy.yml
- core/frontend/src/App.vue
- core/frontend/src/components/kraken/ExtensionCreationDialog.vue
- core/frontend/src/components/system-information/Processes.vue
- core/frontend/src/store/autopilot.ts
- core/frontend/src/types/autopilot/parameter-table.ts
Master is broken with 53 warnings after the latest merges
The PR fix a couple of them and decrease the counter to 46
> Fix linter warnings

- deploy/pimod/blueos.Pifile
potential fix for CI. (I hope)
> deploy: pifile: bump pump to 1200M

- core/frontend/src/App.vue
- Add BlueOS before version
- Add By Blue Robotics
> core: frontend: Improve menu bottom information

- core/frontend/src/App.vue
> core: frontend: Fix tour menu item pointing to the bottom

- core/frontend/src/menus.ts
> core: frontend: Update main page from home to dashboard

- core/frontend/src/menus.ts
> core: frontend: Rename ping page to Ping Sonar Devices

- core/frontend/src/App.vue
> core: frontend: Center tour over main page and not over entire window

- core/frontend/src/App.vue
> core: frontend: Remove tour steps if the network is already connected

- core/frontend/src/views/Autopilot.vue
> core: frontend: views: Autopilot: Create simple table for autopilot information

- .eslintrc.js
- core/frontend/package.json
- core/frontend/src/App.vue
- core/frontend/src/router/index.ts
- core/frontend/vue.config.js
> core: frontend: Change frontend name to BlueOS

- core/frontend/package.json
- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/frontend/yarn.lock
> Improve autopilot page

- core/frontend/src/components/system-information/Processes.vue
> core: frontend: system-information: Processes: Fix chip size for cpu usage

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> core: frontend: ParameterEditor: Fix bit logic from parameter value to edited_bitmask

- core/frontend/src/components/logs/LogManager.vue
https://user-images.githubusercontent.com/1215497/212078769-5c0d8974-a49b-4318-a657-ddbfeec1dc68.mp4
> Improve log page with tooltips and more space between buttons, from SMS feedback

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
> core: frontend: VideoStreamCreationDialog: Move buttons to card-actions and add cancel button

- core/frontend/src/App.vue
- core/frontend/src/views/MainView.vue
> Add mini pirate in submenu

- core/frontend/src/components/autopilot/EndpointCard.vue
- core/frontend/src/components/autopilot/EndpointManager.vue
> core: frontend: Endpoint: Fix style to use more screen

- core/frontend/src/components/bridges/Bridget.vue
> core: frontend: Bridget: Improve text description

- core/frontend/src/components/nmea-injector/NMEAInjector.vue
> core: frontend: NMEAInjector: Improve text description

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
> core: frontend: VideoStreamCreationDialog: Move from 'Encode' to 'Encoding'

- core/frontend/src/App.vue
- core/frontend/src/components/health/HealthTrayMenu.vue
> core: frontend: Change pirate icon style to top bar

- core/frontend/src/components/video-manager/VideoControlsDialog.vue
> core: frontend: VideoControlsDialog: Add close button on video settings

- core/frontend/src/views/NetworkTestView.vue
> core: frontend: NetworkTestView: Improve text capitalization

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
Includes: https://github.com/bluerobotics/BlueOS-docker/pull/1322
https://user-images.githubusercontent.com/1215497/212071603-f6fbf5f7-87fa-4689-89a5-84a0e312623e.mp4
> Improve parameter editor based on SMS feedback

- core/frontend/src/components/nmea-injector/NMEAInjector.vue
> core: frontend: nmea injector: show supported NMEA sentences

- core/frontend/src/views/Autopilot.vue
> core: frontend: Autopilot: Add path to the record over using if checks in template

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
> core: frontend: VideoStreamCreationDialog: Fix default stream address when opening dialog

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
> core: frontend: VideoStreamCreationDialog: Add default name for stream

- core/frontend/src/components/autopilot/EndpointCreationDialog.vue
> core: frontend: EndpointCreationDialog: Add default endpoint name and owner

- core/frontend/src/components/mavlink-inspector/MavlinkInspector.vue
> core: frontend: MAVLinkInspector: Update search bar name to 'Search'

- core/frontend/src/components/utils/iframe.vue
> core: frontend: iframe: Remove border

- core/frontend/src/components/scanner/availableServicesTable.vue
> core: frontend: availableServicestable: Open hyperlinks in new tabs

- core/frontend/src/components/system-information/SystemCondition.vue
- core/frontend/src/components/system-information/SystemConditionCard.vue
> core: frontend: SystemCondition: Add icon

- core/frontend/src/components/version-chooser/VersionChooser.vue
https://user-images.githubusercontent.com/1215497/212785064-aeda08bc-4c5f-4bc9-af5d-bc70cd3e531e.mp4
Fix #1110
> core: frontend: VersionChooser: Add paginator for remote versions

- core/frontend/src/components/app/ReportMenu.vue
> core: frontend: ReportMenu: Remove slack button

- core/frontend/src/components/speedtest/Graph.vue
> core: frontend: speedtest: Graph: Add support to light and dark theme

- core/frontend/src/views/NetworkTestView.vue
> core: frontend: NetworkTestView: Fix max width

- core/frontend/src/components/speedtest/Graph.vue
> core: frontend: speedtest: Graph: Remove controls

- .github/workflows/test-and-deploy.yml
- core/frontend/src/components/autopilot/AutopilotManagerUpdater.ts
- core/frontend/src/components/autopilot/AutopilotSerialConfiguration.vue
- core/frontend/src/components/common/DevicePathHelper.vue
- core/frontend/src/store/autopilot_manager.ts
- core/frontend/src/types/autopilot.ts
- core/frontend/src/views/Autopilot.vue
- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/Endpoint.py
- core/services/ardupilot_manager/typedefs.py
- pyproject.toml
[Screencast from 2022-12-22 15-16-05.webm](https://user-images.githubusercontent.com/4013804/209201851-b1909db6-5843-413f-a856-54b2c31a44b3.webm)
> Allow configuring linux serial ports

- core/frontend/src/components/autopilot/EndpointCreationDialog.vue
> core: frontend: ParameterEditor: Add cancel button to creation form

- core/frontend/src/components/bridges/BridgeCreationDialog.vue
> core: frontend: BridgeCreationDialog: Add cancel button

- core/frontend/src/components/nmea-injector/NMEASocketCreationDialog.vue
> core: frontend: NMEASocketCreationDialog: Add cancel button on creation dialog

- core/frontend/src/components/mavlink-inspector/MavlinkInspector.vue
> core: frontend: MAVLinkInspector: Fix components width and height

- core/frontend/src/components/version-chooser/VersionChooser.vue
> core: frontend: VersionChooser: Only update user if the latest stable has a superior version

- core/frontend/src/components/mavlink-inspector/MavlinkInspector.vue
- core/frontend/src/components/parameter-editor/ParameterEditor.vue
- core/frontend/src/components/system-information/Processes.vue
> Add lens icon for search bar

- core/frontend/src/components/version-chooser/VersionChooser.vue
> core: frontend: VersionChooser: Add text to inform users about pirate mode

- core/frontend/src/components/scanner/availableServicesTable.vue
> core: frontend: availableServicesTable: Add text informing about the page

- core/frontend/src/App.vue
> core: frontend: App: Improve welcomed text

- core/frontend/src/App.vue
> core: frontend: App: Improve internet connection text to be more direct

- core/frontend/src/App.vue
- core/frontend/src/components/app/PirateModeMenu.vue
- core/frontend/src/components/app/PirateModeTrayMenu.vue
- core/frontend/src/components/app/SettingsMenu.vue
- core/frontend/src/components/health/HealthTrayMenu.vue
https://user-images.githubusercontent.com/1215497/212980960-e49c609c-fd97-4e83-bd15-4d6583d25f79.mp4
Fix #1339
> New pirate mode UI

- core/frontend/src/components/bridges/BridgeCreationDialog.vue
- core/frontend/src/components/common/DevicePathHelper.vue
Add miniatures on bridges menu
> Add miniatures in bridges menu

- core/frontend/src/components/nmea-injector/NMEAInjector.vue
> core: frontend: NMEAInjector: Open links in new tab

- core/tools/mavlink_camera_manager/bootstrap.sh
[See changes on release notes](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.10.0)
This is needed for #1376 to work as expected
Test image: [joaoantoniocardoso/blueos-core/update-mavlink-camera-manager](https://hub.docker.com/layers/joaoantoniocardoso/blueos-core/update-mavlink-camera-manager/images/sha256-19895be609e498c53300cd078348f2af5bbd42fa54da534f7aa00829e1962078?context=explore)
> core: tools: mavlink-camera-manager: Update to t3.10.0.

- core/frontend/src/components/autopilot/EndpointManager.vue
Issue created by 95ee3a949803e3c4d9aad2f9b1e7efca23680561
Fix #1346 
> core: frontend: EndpointManager: Add missing fetchAvailableEndpoints

- core/frontend/src/components/version-chooser/VersionChooser.vue
> core: frontend: components: VersionChooser: Do not show previous remote version while loading new repository

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> core: frontend: fix ParameterEditor usage of disable-sort

- core/frontend/src/components/video-manager/VideoControlsDialog.vue
- core/frontend/src/components/video-manager/VideoDevice.vue
- core/frontend/src/components/video-manager/VideoThumbnail.vue
- core/frontend/src/store/video.ts
https://user-images.githubusercontent.com/5920286/213883220-34d10dbf-d929-4092-9ecc-a1dd58b1dd01.mp4
Test image: [joaoantoniocardoso/blueos-core/update-mavlink-camera-manager-and-thumbnail](https://hub.docker.com/layers/joaoantoniocardoso/blueos-core/update-mavlink-camera-manager-and-thumbnail/images/sha256-19895be609e498c53300cd078348f2af5bbd42fa54da534f7aa00829e1962078?context=explore)
> core: frontend: Add thumbnail to Video Device page

- core/services/ardupilot_manager/ArduPilotManager.py
> core: services: ardupilot_manager: Remove invalid log files

- core/frontend/src/App.vue
- core/frontend/src/plugins/vuetify.ts
Now:
Before:
Fix #https://github.com/bluerobotics/BlueOS-docker/issues/1297
> Improve menu scroll

- core/frontend/src/types/autopilot/parameter-sub-enums.ts
> core: frontend: autopilot: parameter-sub-enum: Add FRAME_CONFIG

- core/tools/mavlink2rest/bootstrap.sh
https://github.com/patrickelectric/mavlink2rest/releases/tag/t0.11.11
> core: tools: mavlink2rest: bootstrap: Update to 0.11.11

- core/frontend/src/components/vehiclesetup/viewers/VehicleViewer.vue
> code: frontend: vehiclesetup: VehicleViewer: Move if return to switch case

- core/frontend/src/components/vehiclesetup/overview/LeakInfo.vue
> core: frontend: LeakInfo: Improve LEAK parameter finder

- core/services/ardupilot_manager/ArduPilotManager.py
> core: services: ardupilot_manager: Add try block in remove_old_logs

- .hooks/pre-push
- core/services/ardupilot_manager/firmware/FirmwareInstall.py
- core/services/kraken/kraken.py
- core/services/versionchooser/utils/dockerhub.py
> Fix python linter errors

- core/tools/mavlink2rest/bootstrap.sh
> core: tools: mavlink2rest: Update to 0.11.12

- core/frontend/src/components/app/SettingsMenu.vue
- core/services/commander/main.py
> Add option to remove services log files

- core/frontend/src/components/kraken/ExtensionCreationDialog.vue
- core/frontend/src/views/ExtensionManagerView.vue
> core: frontend: properly close extension creation dialog

- core/frontend/src/components/autopilot/AutopilotManagerUpdater.ts
- core/frontend/src/components/vehiclesetup/overview/VehicleInfo.vue
- core/frontend/src/store/autopilot_manager.ts
- core/frontend/src/views/VehicleSetupView.vue
- core/libs/commonwealth/commonwealth/mavlink_comm/VehicleManager.py
- core/libs/commonwealth/commonwealth/mavlink_comm/typedefs.py
- core/services/ardupilot_manager/main.py
> Add firmware type

- .github/workflows/test-and-deploy.yml
> github: test-and-deploy: Use official docker login action

- core/frontend/src/components/vehiclesetup/viewers/NoneViewer.vue
- core/frontend/src/components/vehiclesetup/viewers/VehicleViewer.vue
> Add vehicle not found

- .github/workflows/test-and-deploy.yml
> github: ci: test-and-deploy: Upload docker image in release

- core/frontend/src/components/vehiclesetup/overview/OnboardSensors.vue
Fix #1454
This basically makes all things "computed" instead of methods
> core: frontend: vehicleSetup: compute everything

- .github/workflows/test-and-deploy.yml
- .gitmodules
- core/frontend/src/components/mavlink-inspector/MavlinkInspector.vue
- core/frontend/src/utils/mavlink_prettifier.ts
> Move yarn lint warnings number to 0

- core/frontend/src/components/kraken/InstalledExtensionCard.vue
- core/frontend/src/types/kraken.ts
- core/frontend/src/views/ExtensionManagerView.vue
should fix most of the side-notes of #1398
> Add spinner to extensions when busy

- core/frontend/src/components/vehiclesetup/overview/OnboardSensors.vue
- core/frontend/src/utils/deviceid_decoder.ts
> Add External/Internal and priority to compass overview

- core/frontend/src/libs/MAVLink2Rest/index.ts
> core: frontend: libs: MAVLink2Rest: Start websocket with fallback

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
I checked and the SERVO_FUNCTIONS _do_ change automatically after FRAME_CONFIG is updated
> core: frontend: pwm_setup: count number of motors from parameters

- core/frontend/src/components/video-manager/VideoStream.vue
- core/frontend/src/store/video.ts
> core: frontend: Add SDP file download for UDP streams

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
> core: frontend: componentes: PwmSetup: Allow user to change motor parameter

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> core: frontend: components: ParameterEditor: Show hand cursor when parameter is editable

- core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
@Williangalvani this should fix the apply not working on the first time
> core: frontend: components: ParameterEditorDialog: Update validator when value changes

- core/frontend/src/components/version-chooser/VersionCard.vue
> core: frontend: components: VersionCard: Disable buttons when loading or deleting

- core/frontend/src/components/ping/ping1d.vue
- core/frontend/src/components/ping/ping360.vue
- core/frontend/src/types/ping.ts
> Fix ping version format

- core/frontend/src/components/version-chooser/VersionChooser.vue
> core: frontend: check both tag and repository for showing current image

- core/tools/nginx/nginx.conf
> core: tools: nginx: Increase timeout for version-chooser to process image

- core/frontend/src/components/system-information/Firmware.vue
- core/frontend/src/views/SystemInformationView.vue
- core/services/commander/main.py
> System information: Add vcgencmd information

- core/frontend/src/components/app/SettingsMenu.vue
- core/services/commander/main.py
> Add system log folder size

- core/frontend/src/components/system-information/Firmware.vue
- core/services/commander/main.py
> system-information: firmware: Add up-to-date and latest

- core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
> core: frontend: components: ParameterEditorDialog: Add check for no options in parameter

- core/services/versionchooser/setup.py
> core: versionchooser: lock connexion dependency

- core/frontend/src/components/version-chooser/VersionChooser.vue
> core: frontend: allow up to 60 seconds for new core to reload

- core/frontend/src/views/ExtensionManagerView.vue
> core: frontend: ExtensionManagerView: Fix payload format

- core/frontend/src/components/system-information/NetworkCard.vue
> core: frontend: system-information: NetworkCard: Fix click to show IPv6

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> core: frontend: ParameterEditor: Fix behavior when clearable sets model as undefined

- install/boards/bcm_27xx.sh
> 1.0: Reboot if eeprom is updated

- core/configuration/motd
> Cure terminal illness

- core/tools/mavlink_camera_manager/bootstrap.sh
Closes #1556
Main points for BlueOS:
* Fixes the instability caused by the thumbnails
* Fixes MJPG stream creations
* Logs are now hourly rotated, with the `mavlink-camera-manager.YYYY-MM-DD-HH.log` name.
[Full changelog here](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.11.0)
> core: tools: mavlink-camera-manager: Update to t3.11.0.

- deploy/pimod/blueos.Pifile
> deploy: pimod: pipfile: Pump image from 1200 to 1400MB

- core/frontend/src/components/parameter-editor/ParameterEditor.vue
> Do not save parameters that are read only

- core/frontend/package.json
- core/frontend/src/views/ExtensionManagerView.vue
- core/frontend/yarn.lock
> Fix extension output

- core/frontend/src/components/kraken/ExtensionModal.vue
- core/frontend/src/views/ExtensionManagerView.vue
Fixes normal installation being unable to change versions. Hopefully the larger timeout also fixes some instances of install problems.
> Extension update fix

- core/frontend/vue.config.js
- core/services/bag_of_holding/main.py
- core/services/bag_of_holding/setup.py
- core/services/install-services.sh
- core/start-blueos-core
- core/tools/nginx/nginx.conf
This allow storing key/value pairs as json in the backend, which get stored into a json file.
fix #1583
*No AIs were harmed in writing this code
> core: create Bag of Holding

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
> core: frontend: VehicleSetupView: Show servo output

- core/frontend/src/views/VehicleSetupView.vue
Use better icons than bookshelf
> core: frontend: VehicleSetupView: Improve icons

- core/frontend/src/components/ethernet/DHCPServerDialog.vue
If was checking for something that does not exist, add correct computed method to check status
> core: frontend: components: DHCPServerDialog: Fix if check

- core/frontend/src/App.vue
- core/frontend/src/components/wizard/Wizard.vue
https://user-images.githubusercontent.com/1215497/230784266-6508060e-0288-49c2-813a-e8a5dc7b7397.mov
> Wizard: Add apply area with status and information about configuration

- install/boards/bcm_27xx.sh
> install: boards: bcm_27xx: Update bootloader and gpu firmware on boot

- core/tools/blueos_startup_update/blueos_startup_update
- install/boards/bcm_27xx.sh
Fix #1020 
It works like a charm once the DHCP server is enabled
To use with mac and having internet access at the same time:
> Add usb otg ethernet

- core/tools/mavlink_camera_manager/bootstrap.sh
RTSP streams working again :tada: 
[release log](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.11.1)
> core: tools: mavlink-camera-manager: Update to t3.11.1.

- core/frontend/src/App.vue
- core/frontend/src/components/app/ImagePicker.vue
- core/frontend/src/components/app/VehicleBanner.vue
This is based over @rjehangir proposal:
https://github.com/bluerobotics/BlueOS-docker/pull/1511#issuecomment-1458864096
**Current:**
**New:**
Ref suggestion:
> Improve vehicle sidebar interface

- core/frontend/src/components/wizard/Wizard.vue
That's necessary to update the images on the frontend and others elements that may be configured on the wizard
> core: frontend: components: Wizard: Restart page after finishing

- core/frontend/src/components/wizard/Wizard.vue
Fix version check, we should open if there is no version on bag
> core: frontend: components: Wizard: Fix check for version

- core/frontend/package.json
- core/frontend/src/App.vue
- core/frontend/src/components/common/JsonEditor.vue
- core/frontend/src/menus.ts
- core/frontend/src/router/index.ts
- core/frontend/src/store/bag.ts
- core/frontend/src/views/BagEditorView.vue
- core/frontend/yarn.lock
> Bag editor

- core/frontend/src/components/system-information/Firmware.vue
It was not assign the variables
> frontend: system-information: Firmware: Fix showing firmware and bootloader version

- deploy/github-runner/RAEDME.md
- deploy/github-runner/README.md
I could not pass through here without submitting this PR to correct this file name.
> Rename RAEDME.md to README.md

- core/tools/mavlink_camera_manager/bootstrap.sh
Closes #1627
[Release notes](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.11.4)
> core: tools: mavlink-camera-manager: Update to t3.11.4.

- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/types/version-chooser.ts
- core/frontend/src/utils/version_chooser.ts
- core/services/versionchooser/main.py
- core/services/versionchooser/openapi/versionchooser.yaml
- core/services/versionchooser/utils/chooser.py
> versionchooser: Break api with local and remote endpoints

- core/tools/mavlink_camera_manager/bootstrap.sh
Nothing new, just reducing failure points.
[Release notes](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.11.5)
> core: tools: mavlink-camera-manager: Update to t3.11.5.

- core/services/versionchooser/setup.py
Fix build for 1.0, cherry-picked from master
> core: services: versionchooser: setup: Fix werkzeug version

- core/frontend/package.json
- core/frontend/src/components/autopilot/AutopilotSerialConfiguration.vue
- core/frontend/src/utils/pattern_validators.ts
- core/frontend/yarn.lock
> frontend: AutopilotSerialConfiguration: Fix usage of non serial ports

- core/frontend/src/views/VehicleSetupView.vue
> core: frontend: views: VehicleSetupView: Improve code and visual

- core/frontend/src/components/wifi/WifiManager.vue
We got a terrible time on the xponential with a huge list of wifi networks available
> frontend: Allow user to search for wifi and add scrollbar on wifi list

- .github/workflows/test-and-deploy.yml
> ci: Add amd64 deployment

- core/services/helper/main.py
- core/services/helper/setup.py
We don't have time to have a full telemetry system for now
But that should be enough for us to have an idea
> core: services: helper: Ping BlueOS for simple telemetry system

- core/frontend/src/views/VehicleSetupView.vue
> core: frontend: fix vehicle setup tabs

- core/frontend/src/types/kraken.ts
- core/frontend/src/views/ExtensionManagerView.vue
> core: frontend: types: kraken: Add types to follow latest version

- core/services/beacon/main.py
> core: services: beacon: Print ip with broadcast name

- core/frontend/package.json
- core/frontend/src/App.vue
- core/frontend/src/libs/settings.ts
- core/frontend/src/main.ts
- core/frontend/src/store/settings.ts
- core/frontend/src/widgets/Cpu.vue
- core/frontend/src/widgets/Disk.vue
- core/frontend/yarn.lock
- Allow top bar widgets
- Allow user to drag and move it around
- Allow add / remove
- Add dynamic support
> frontend: widgets: Add first version

- core/frontend/src/components/system-information/Firmware.vue
- core/frontend/src/store/commander.ts
- core/services/commander/main.py
> Add button for eeprom update

- core/frontend/src/App.vue
- core/frontend/src/views/ExtensionManagerView.vue
this element only exists in vuetify3, moving to vuetify2
> core: frontend: Fix usage of vuetify3 element v-list-subheader

- core/frontend/package.json
- core/frontend/src/components/vehiclesetup/viewers/GenericViewer.vue
- core/frontend/yarn.lock
Helpful to draw schemes, set custom vehicle image on the UI and more.
> Allow user to download a png image with the boundaries of the 3D model

- core/frontend/src/App.vue
> core: frontend: App: Fix access to extensions that open in new pages

- core/frontend/src/components/autopilot/AutopilotManagerUpdater.ts
> core: frontend: fix SemVer not being populated

- core/frontend/vue.config.js
This needs some time invested into fixing. let's at least get things into a state where they work.
Fix #1696
> core: frontend: temporarily remove probing of addresses

- core/frontend/src/components/wizard/Wizard.vue
> core: frontend: wizard: only write wizard to bag after finishing all other steps

- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/frontend/src/views/Autopilot.vue
> core: frontend: reset frontend parameters when flashing new firmware and restarting

- core/frontend/src/components/wizard/Wizard.vue
> core: frontend: wizard: add 'other' vehicle

- core/frontend/src/menus.ts
> core: frontend: fix bag of holding frontend description

- core/frontend/src/components/version-chooser/VersionChooser.vue
> Fix version not being hidden after deletion

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
Motor 3 works, motor 1 doesnt? I'm confused
[Screencast from 2023-06-08 14-12-42.webm](https://github.com/bluerobotics/BlueOS-docker/assets/4013804/56ef4243-2df5-4e8e-bfd4-f0e156e4e09b)
~once it works, it should~ fix #1751
> core: frontend: pwmsetup: allow testing motors on rover

- core/frontend/src/types/autopilot/parameter-table.ts
> core: frontend: stop notifying ParametersTable misses, improve message

- core/frontend/src/components/video-manager/VideoDevice.vue
- core/frontend/src/components/video-manager/VideoStream.vue
- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
- core/frontend/src/types/video.ts
- core/frontend/src/utils/video.ts
> Fix support of redirect streams in the frontend

- core/frontend/src/components/video-manager/VideoDevice.vue
- core/frontend/src/components/video-manager/VideoManager.vue
- Always show sources with active streams (even fake source)
- show redirect source out of pirate mode
- add description to redirect source
> Video tweaks

- core/frontend/src/components/wifi/ConnectionDialog.vue
- core/frontend/src/components/wifi/WifiManager.vue
- core/frontend/src/store/wifi.ts
> core: frontend: update wifi store when forgetting a network

- core/frontend/src/components/video-manager/VideoStream.vue
- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
- core/frontend/src/types/video.ts
- core/tools/mavlink_camera_manager/bootstrap.sh
- Closes #1203
- Closes #1010 (by implementing the second case)
MCM [change log](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.12.0)
> Update mcm and allow disable mavlink

- core/frontend/src/components/video-manager/VideoStream.vue
> core: frontend: video-manager: Fix SDP URL copy to clipboard method

- core/frontend/src/components/app/SettingsMenu.vue
> core: frontend: components: SettingsMenu: Allow enabling Wizard

- core/services/kraken/kraken.py
> Kraken: do not blindly filter extension before properly removing it

- core/frontend/src/App.vue
- core/frontend/src/router/index.ts
- core/frontend/src/types/helper.ts
- core/frontend/src/views/ExtensionView.vue
- core/services/helper/main.py
> Create named links for extensions... again

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
- core/frontend/src/store/autopilot_manager.ts
- core/frontend/src/types/autopilot.ts
> core: frontend: types: ardupilot: Add FirmwareVehicleType

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
> Require manual mode for motor test

- core/frontend/src/components/wizard/Wizard.vue
> core: frontend: components: wizard: Avoid doing all steps again

- core/frontend/src/components/app/VehicleBanner.vue
- core/frontend/src/store/beacon.ts
> Fix beacon frontend

- core/frontend/src/components/app/PowerMenu.vue
There are more power options than "Shut Down"
> core: frontend: components: PowerMenu: Change text to be more clear 

- core/services/log_zipper/main.py
- core/start-blueos-core
> core: services: log_zipper: Fix time conversion between minutes and seconds

- core/services/wifi/main.py
Fix https://github.com/bluerobotics/BlueOS/issues/1743
Keep in mind that:
```python
network_id: Optional[int] = None
if network_id: # Will fail for both None and 0, the same apply to `not`
if network_id is not None: # Is the correct way
```
> core: services: wifi: Fix connecting to known networks

- core/frontend/src/components/version-chooser/VersionCard.vue
- core/frontend/src/components/version-chooser/VersionChooser.vue
> Disable update bootstrap button once updating

- core/frontend/src/components/video-manager/VideoStream.vue
> core: frontend: Do not wrap the stream name

- core/frontend/src/components/video-manager/VideoControlsDialog.vue
No more confusing UI feedback when changing the video controls :tada: 
https://github.com/bluerobotics/BlueOS/assets/5920286/258e81d4-f869-465d-ac94-7e6584241493
https://github.com/bluerobotics/BlueOS/assets/5920286/3889581e-0ddc-413e-b8e4-f4b4e18fa951
> core: frontend: Fix video controls odd feedback when updating

- core/frontend/src/App.vue
> App: Move scroll style to global

- core/frontend/src/assets/img/devicePathHelper/rpi4b.svg
hint: click 
to see the source diff
> core: frontend: devicePathHelper: fix Pi4 svg

- core/frontend/src/components/wifi/ConnectionDialog.vue
- core/services/wifi/main.py
> From Daniel: Fresh install of beta.27 gave me a timeout error when connecting wifi, but connected anyway
> core: services: wifi: Add more time to connect to wifi network

- core/services/ping/ping360_ethernet_prober.py
> core: ping: deal with other exception while probing for Ping360

- core/frontend/src/views/ExtensionView.vue
> core: frontend: use extensions name as page title

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
they are not working on master
> core: frontend: fix motor highlighting for rover

- core/services/ping/ping1d_mavlink.py
> Minor ping updates

- core/frontend/src/views/ExtensionView.vue
should fix the blueos-in-blueos issue
williangalvani/blueos-core:no-port-80
> core: frontend: do not return 80 if port is unknown

- core/tools/blueos_startup_update/blueos_startup_update
> core: blueos_startup_update: show time taken to apply patches

- core/frontend/src/components/common/DevicePathHelper.vue
> core: frontend: device-path-helper: reduce default size

- core/services/versionchooser/utils/chooser.py
- core/services/versionchooser/utils/dockerhub.py
> core: version chooser: fix logging

- core/frontend/src/components/system-information/Firmware.vue
> core: frontend: components: Firmware: Only show update button when the latest firmware is newer

- core/frontend/src/components/health/SelfHealthTest.vue
- core/frontend/src/views/MainView.vue
> core: frontend: create SelfHealthTest, add test for factory images

- core/services/versionchooser/utils/chooser.py
> core: services: versionchooser: Add more checks and debug information

- core/tools/install-system-tools.sh
hotspot uses apt on his bootstrap script
> core: tools: install-system-tools: Move hotspot to apt list

- core/frontend/src/components/health/SelfHealthTest.vue
- it's a vehicle problem, not a person problem
- Discuss is an implementation detail, to users it's a forum
- politeness
> core: frontend: improve warning text in SelfHealthTest.vue

- core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
fix #1914 
please test extensively if possible, to check this doesn't introduce anything weird.. again.
> core: frontend: add watcher for 'force' button

- core/tools/blueos_startup_update/blueos_startup_update
> core: tools: blueos_startup_update: Add check for run_command

- core/services/commander/main.py
> core: services: commander: Save bootstrap config before reset settings

- bootstrap/bootstrap/bootstrap.py
- bootstrap/bootstrap/setup.py
- bootstrap/main.py
- core/services/versionchooser/utils/chooser.py
- install/install.sh
This moves bootstrap to loguru, and populates a file at the same place our other logs are
> bootstrap: add logging

- core/frontend/src/components/wizard/Wizard.vue
> core: frontend: wizard: Allow user to abort if configuration runs 3 times

- core/frontend/src/components/wizard/ActionStepper.vue
- core/frontend/src/components/wizard/Wizard.vue
Fix #1947 
https://github.com/bluerobotics/BlueOS/assets/1215497/0171e819-1dac-4ee8-8e38-fed9d96b9492
> Allow user to skip wizard configuration steps

- core/frontend/src/App.vue
- core/frontend/src/components/app/SystemCheckerTrayMenu.vue
- core/frontend/src/store/commander.ts
> Notify user if BlueOS has no access to the host computer

- core/frontend/src/components/wizard/Wizard.vue
Fix #1980
Fix #1981 
Fix check for steps to skip as well
> wizard: Random fixes

- core/frontend/src/components/wizard/Wizard.vue
- core/tools/nginx/nginx.conf
> core: frontend: Wizard: Reboot flight controller if it fails to flash on the first try

- core/frontend/src/components/wizard/ActionStepper.vue
- core/frontend/src/components/wizard/Wizard.vue
Disable checkmarks while operation is in progress
> core: frontend: wizard: ActionStepper: Add loading property

- core/frontend/src/components/wizard/Wizard.vue
The final step if after everything is done
> core: frontend: wizard: Fix name of step

- core/libs/commonwealth/commonwealth/utils/commands.py
> core: commonwealth: fix ssh key path

- core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
- core/frontend/src/types/autopilot/parameter.ts
Closes #1996 
https://github.com/bluerobotics/BlueOS/assets/5920286/0f6a09a8-dcb1-499d-9fa2-bfe3e06035e1
https://github.com/bluerobotics/BlueOS/assets/5920286/a2a06eee-a999-4dde-b784-4a6ac5c3d630
> core: frontend: components: ParameterEditorDialog: Simplify and fix validation

- core/frontend/src/components/scanner/availableServicesTable.vue
- core/frontend/src/types/helper.ts
- core/services/helper/main.py
- core/services/helper/nginx_parser.py
> core: helper: add nginx_parser to map ports to service paths

- core/frontend/src/components/vehiclesetup/overview/VehicleInfo.vue
- core/frontend/src/components/vehiclesetup/viewers/GenericViewer.vue
> core: frontend: improve support for Rover, add 3d model for ground rovers

- README.md
I intended to review @patrickelectric's README updates a while ago, but only just got around to it - sorry!
Replaces and closes #2012.
> README: update language and links

- core/start-blueos-core
This represents a 12% time reduction.
> note: Reduces QGC connection from 102 seconds to 90 seconds total boot time.
> core: Improve startup time by starting high priority services first

- core/tools/nginx/nginx.conf
Fixes an issue with services with .html files.
> core: nginx: remove .html match

- core/services/kraken/kraken.py
> core: services: kraken: Kill and wait for all containers with valid name

- core/services/kraken/kraken.py
> core: services: kraken: Add more debug messages

- core/services/kraken/kraken.py
> core: services: kraken: Wait for delete operation to finish before running

- core/tools/nginx/nginx.conf
This should prevent random errors on Pi3
> core: tools: nginx: Increase timeout for all services

- core/Dockerfile
- core/tools/filebrowser/bootstrap.sh
> core: tools: Update filebrowser to v2.24.2

- core/frontend/src/components/version-chooser/VersionChooser.vue
- core/frontend/src/utils/pull_tracker.ts
- core/frontend/src/views/ExtensionManagerView.vue
- core/services/versionchooser/utils/chooser.py
> propagate errors from docker pull to the frontend

- core/frontend/src/components/autopilot/AutopilotSerialConfiguration.vue
> core: frontend: make serial port configuration save button restart autopilot

- core/frontend/src/components/common/PasswordInput.vue
should fix #2064
~not tested yet~ tested
> core: frontend: prevent submiting form when connecting to wifi

- core/frontend/src/components/wizard/DefaultParamLoader.vue
- core/frontend/src/components/wizard/Wizard.vue
[Screencast from 2023-08-28 14-51-27.webm](https://github.com/bluerobotics/BlueOS/assets/4013804/3923c207-296e-4831-8c57-daa217fa835a)
> core: frontend: wizard: make sure a default param set is chosen

- core/frontend/src/types/kraken.ts
To match bluerobotics/BlueOS-Extensions-Repository#63
> core: frontend: src: types: kraken: add `tool`

- core/frontend/src/widgets/Cpu.vue
- core/frontend/src/widgets/Disk.vue
> core: frontend: widgets: Update values periodically

- core/frontend/src/App.vue
https://github.com/bluerobotics/BlueOS/assets/1215497/970f503a-9700-4095-b176-cc346e8dc79d
With the following register_service:
```
{
"name": "Batata",
"description": "Node-RED is a programming tool for wiring together hardware devices, APIs and online services in new and interesting ways.",
"icon": "<svg role=\"img\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><title>Docker</title><path d=\"M13.983 11.078h2.119a.186.186 0 00.186-.185V9.006a.186.186 0 00-.186-.186h-2.119a.185.185 0 00-.185.185v1.888c0 .102.083.185.185.185m-2.954-5.43h2.118a.186.186 0 00.186-.186V3.574a.186.186 0 00-.186-.185h-2.118a.185.185 0 00-.185.185v1.888c0 .102.082.185.185.185m0 2.716h2.118a.187.187 0 00.186-.186V6.29a.186.186 0 00-.186-.185h-2.118a.185.185 0 00-.185.185v1.887c0 …
```
> core: frontend: App: Improve support to custom icons with svg

- core/frontend/src/components/app/PowerMenu.vue
- core/frontend/src/components/app/VehicleRebootMenu.vue
- core/frontend/src/components/autopilot/AutopilotManagerUpdater.ts
- core/frontend/src/components/autopilot/AutopilotSerialConfiguration.vue
- core/frontend/src/components/parameter-editor/ParameterEditorDialog.vue
- core/frontend/src/views/Autopilot.vue
> core: frontend: components: AutopilotManagerUpdater: Add restart function

- install/install.sh
> install: Remove machine-id 

- core/services/ping/setup.py
~needs testing~ tested. worked 10/10
fix #2060
> core: ping: bump bluerobotics-ping version to 0.1.5

- install/install.sh
We should have the file otherwise docker binds will fail
Follows #2086
> install: install: Add uninitialized machine-id

- .github/ISSUE_TEMPLATE/bugs.yml
- encourage posting screenshots and recordings for UI problems
- add a space for extra context, like system logs and forum links
> issue-templates: update bugs.yml

- core/services/beacon/main.py
> core: beacon: add domain to logs

- core/frontend/src/router/index.ts
- core/frontend/src/views/ExtensionView.vue
needs testing, testing this in the dev server is annoying
> core: frontend: pass remaining path to extensions

- core/services/ardupilot_manager/mavlink_proxy/test_all.py
> Fix mavlink_router test

- .github/workflows/test-and-deploy.yml
- bootstrap/startup.json.default
- core/Dockerfile
- core/frontend/src/types/kraken.ts
- core/frontend/src/utils/version_chooser.ts
- core/libs/commonwealth/commonwealth/utils/general.py
- core/services/helper/main.py
- core/services/helper/setup.py
- core/services/ping/setup.py
- core/start-blueos-core
- core/tools/blueos_startup_update/blueos_startup_update
- core/tools/install-static-binaries.sh
- core/tools/machineid/bootstrap.sh
- install/install.sh
> Move master commits to 1.1 branch

- core/libs/commonwealth/commonwealth/utils/general.py
- core/services/helper/main.py
> core: libs: commonwealth: general: Add blueos_version

- core/libs/commonwealth/commonwealth/utils/general.py
- core/services/ardupilot_manager/main.py
- core/services/bag_of_holding/main.py
- core/services/beacon/main.py
- core/services/bridget/main.py
- core/services/cable_guy/main.py
- core/services/commander/main.py
- core/services/helper/main.py
- core/services/kraken/main.py
- core/services/log_zipper/main.py
- core/services/nmea_injector/nmea_injector/main.py
- core/services/pardal/main.py
- core/services/ping/main.py
- core/services/versionchooser/main.py
- core/services/wifi/main.py
Limit ram usage by python programs to 100MB
> core: services: Add limit_ram_usage

- core/services/ardupilot_manager/main.py
- core/services/cable_guy/main.py
Helper needs to find the home page to identify the service
> core: Add pages for ardupilot manager and cable guy for helper

- core/services/major_tom/src/core.py
not sure of how something like this can go through CI...
> core: major_tom: fix import

- core/frontend/package.json
- core/frontend/vite.config.js
the change was unexpected and I expect more people other than me to be confused by suddenly being unable to work on the frontend.
> Restore functionality of 'yarn serve' and port to 8080

- core/frontend/src/components/kraken/InstalledExtensionCard.vue
> core: frontend: extensions: validate tag before checking if update is available

- .hooks/pre-push
- pyproject.toml
fixes an issue with mypy running in parallel and all instances using the same cache
> minor CI updates

- core/services/commander/main.py
Previously `~pi/.ssh/authorized_keys` was created with the current user (root) as owner. This causes `ssh-copy-id` to fail when the user tries to upload their ssh key to the host. Now it should have the correct permissions.
> Create authorized_keys with correct owner

- core/frontend/src/views/ExtensionManagerView.vue
Fix https://github.com/bluerobotics/BlueOS/issues/2153
> Remove examples in extension view if no filter is selected 

- LICENSE-BlueOS-Custom.md
- LICENSE-agplv3.md
- LICENSE.md
Add LICENSE, LICENSE-aglpv3 and LICENSE-BlueOS-Custom files
> LICENSE: Add first versions

- .github/workflows/test-and-deploy.yml
Fix problems with vite build
Check https://github.com/oven-sh/bun/issues/6302
> github: workflows: test-and-deploy: Fix version of bun to 1.0.3

- core/libs/commonwealth/commonwealth/utils/logs.py
> core: libs: commonwealth: utils: logs: Move rotation to 10MB

- core/services/log_zipper/main.py
This make it easier to process files
Fix #2161
> core: services: log_zipper: Use gzip over zip

- .github/workflows/test-and-deploy.yml
- pyproject.toml
It's currently giving wrong error messages
> pyproject: Fix python linter versions

- core/start-blueos-core
- core/tools/install-system-tools.sh
- core/tools/iperf3/bootstrap.sh
> core: tools: Add iperf3

- core/tools/mavlink_camera_manager/bootstrap.sh
> core: tools: mavlink-camera-manager: Update to t3.12.3

- pyproject.toml
> pyproject: Fix author format

- core/services/ardupilot_manager/firmware/FirmwareInstall.py
- core/services/ardupilot_manager/setup.py
- pyproject.toml
> Add initial support to aarch64 firmware 

- core/frontend/src/components/utils/BrIframe.vue
> core: frontend: add allowfullscreen to BRIframe

- core/services/kraken/kraken.py
This makes loading docker stats at the installed extenstions A LOT faster.
> core: kraken: fetch docker stats assynchronously

- core/frontend/package.json
potential "fix" for #2207
Not an actual fix for the underlying issue, but this change will ensure no one sees it in the repo ever again.
> Dev server host

- core/frontend/src/views/ExtensionManagerView.vue
fix #1733 
I recommend hiding whitespace changes for reviewing:
> Improve installed extensions interface

- core/services/pardal/main.py
> Pardal: reduce memory usage

- core/Dockerfile
- core/run-service.sh
- core/start-blueos-core
(opening as draft because I have issues with shellcheck on my machine)
fix #2218
> Core: update start_blueos_core to add memory limit and logging

- core/frontend/src/components/kraken/InstalledExtensionCard.vue
> core: kraken: Always show next version if all versions are below 1.0.0

- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
- core/services/ardupilot_manager/mavlink_proxy/Manager.py
- core/services/ardupilot_manager/mavlink_proxy/main.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
Should help with mavp2p hanging after a while.
fix #2247
> core: ardupilot mananger: asyncify router management, consume stderr/stdout

- core/Dockerfile
- core/libs/install-libs.sh
- core/services/beacon/setup.py
- core/services/bridget/setup.py
- core/services/commander/setup.py
- core/services/helper/setup.py
- core/services/install-services.sh
- core/services/kraken/setup.py
- core/services/ping/setup.py
- core/services/versionchooser/setup.py
- core/services/wifi/setup.py
- pyproject.toml
tested
[x] Move to use https://www.piwheels.org/project/aiohttp/
Fix #1175 
https://github.com/bluerobotics/blueos-docker-base/releases/tag/v0.1.0
> core: Dockerfile: Update to use new BlueOS base image

- install/install.sh
blueos-avahi.local is available over all networks
> install: install: Use blueos-avahi over blueos

- install/install.sh
The current user also works for sudo commands
> install: install: Use current user as default user

- bootstrap/bootstrap/bootstrap.py
- bootstrap/test_bootstrap.py
Cherry-pick #2265 to be available on next beta 
I'm waiting @vshie further comments about it before moving
> 1.1: bootstrap: Fix delta time calculation using monotonic clock

- core/frontend/package.json
> core: frontend: build in produtction mode

- bootstrap/Dockerfile
- bootstrap/bootstrap/bootstrap.py
- bootstrap/bootstrap/setup.py
- bootstrap/pip.conf
Cherry-pick some changes on master to 1.1
From: #2252 #2266 #2263
> 1.1: bootstrap: Add more changes from master

- core/frontend/src/components/vehiclesetup/PwmSetup.vue
- core/frontend/src/components/vehiclesetup/overview/LightsInfo.vue
- core/frontend/src/components/vehiclesetup/viewers/GenericViewer.vue
> 1.1: core: vehicle-setup: fix ArduSub lights mappings

- .github/workflows/test-and-deploy.yml
> 1.1: Fix self-hosted name and add timeout for pimod

- core/services/pardal/main.py
> 1.1: core: pardal: Use generators

- deploy/pimod/blueos.Pifile
> 1.1: CI: specify pi user on pimod

- core/tools/mavlink_camera_manager/bootstrap.sh
> core: tools: mavlink-camera-manager: Update to t3.12.4

- core/tools/mavlink2rest/bootstrap.sh
For more information: https://github.com/mavlink/mavlink2rest/releases/tag/t0.11.19
> core: tools: mavlink2rest: Update to t0.11.19

- core/frontend/src/components/wizard/Wizard.vue
Closes https://github.com/bluerobotics/BlueOS/issues/2009
> core: frontend: wizard: Fix Retry button showing red after success

- core/frontend/src/components/app/SettingsMenu.vue
> core: frontned: Change text from 'Enable Wizard' button

- core/services/helper/main.py
Avoid hitting or ram memory limit
> core: services: helper: main: Fix upload internet speed test

- core/services/ardupilot_manager/mavlink_proxy/AbstractRouter.py
- core/services/ardupilot_manager/mavlink_proxy/test_all.py
1 second appears to be not enough, with 3 seconds it improves the check for the router.
> ardupilot_manager: mavlink_proxy: Increase wait time for process to start and finish

- core/tools/nginx/cors.conf
> tools: nginx: Add CORS headers also for bad-responses

- core/frontend/src/components/wizard/Wizard.vue
> core: frontend: components: wizard: Add 'remind me later' when skipping wizard

- core/frontend/src/components/autopilot/FirmwareManager.vue
> core: frontend: components: autopilot: Avoid usage of form

- core/frontend/src/App.vue
https://github.com/bluerobotics/BlueOS/blob/master/core/frontend/src/types/helper.ts#L12
> core: frotend: fix typo

- core/libs/commonwealth/commonwealth/utils/decorators.py
- core/services/ardupilot_manager/ArduPilotManager.py
- core/services/ardupilot_manager/main.py
Fix https://github.com/bluerobotics/BlueOS/issues/1468
> core: services: ardupilot_manager: Avoid multiple instances of ardupilot running

- core/frontend/src/components/vehiclesetup/Configure.vue
> core: frontend: vehicle setup: allow filtering setup tabs

- core/frontend/src/components/logs/LogManager.vue
- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
Fix usage of log argument and enable tlog
> Enable tlog

- core/frontend/src/components/nmea-injector/NMEASocketCreationDialog.vue
> core: frontend: fix nmea-injector validations

- core/frontend/src/components/vehiclesetup/Configure.vue
- core/frontend/src/store/settings.ts
This allow us to have testing or development code while doing stable and official releases.
The use case is to show a current working UI while we work on new pages and changes for new pages while not stable for users. 
It also adds back the old setup page
> Add secret dev mode

- core/services/helper/main.py
This allows it to work with cockpit vite development server
Tested with #2401
> core: services: helper: main: Add some header properties

- core/frontend/src/components/wizard/DefaultParamLoader.vue
Removes the blocking behavior in the setup wizard encountered when `No parameters available for this setup' is displayed.
Fixes #2395
> core: frontend: Fixes unable to continue in wizard

- core/frontend/src/components/wizard/Wizard.vue
Add a return button to allow users to return before applying final configuration in wizard.
Closes #2414
> Allow users to return before applying configuration in wizard

- core/services/helper/main.py
F
sorry, I got confused while trying to debug and reconciiate two branches at the same time here, my bad
This reverts commit 84597bd039bc0a67539ddbc74cee7c8d916967ad.
> Revert "core: services: beacon: fix MCM signalling server port"

- core/tools/mavlink_camera_manager/bootstrap.sh
Changes:
* Fix mavlink communication unresponsiveness / lateness
* Fix RTSP streams recreation
Full test report:
Found issues/limitations:
* https://github.com/mavlink/mavlink-camera-manager/issues/363
* https://github.com/mavlink/mavlink-camera-manager/issues/364
* https://github.com/mavlink/mavlink-camera-manager/issues/365
[Full Changelog](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.12.10)
> core: tools: mavlink-camera-manager: Update to t3.12.10

- core/frontend/src/components/app/PowerMenu.vue
> Add check to avoid restart autopilot button to appears while rebooting or powering down

- core/services/ardupilot_manager/flight_controller_detector/board_identification.py
Add board_identification for Arduino based controllers
> core: Add support for Arduino based controllers

- core/services/ardupilot_manager/setup.py
> code: ardupilot manager: update default firmware to Sub 4.1.2

- core/tools/mavlink2rest/bootstrap.sh
Adds support to all necessary calibration messages
> core: tools: mavlink2rest: Update to t0.11.20

- core/configuration/motd
> [1.2] core: configuration: motd: Update version to 1.2

- core/frontend/src/components/kraken/ExtensionCard.vue
- core/frontend/src/views/ExtensionManagerView.vue
Create a more consistent UI
Now:
Before:
> Improve extension page UI

- core/tools/nginx/nginx.conf
~needs testing. I'm letting the CI build it for me~ :man_shrugging: 
helps #2469
> core: frontend: add cache headers for logviewer and assets folder

- core/frontend/src/components/kraken/ExtensionCard.vue
- core/frontend/src/views/ExtensionManagerView.vue
> [1.2] Improve extension page

- core/frontend/src/components/vehiclesetup/configuration/compass/CompassDisplay.vue
see https://github.com/bluerobotics/BlueOS/blob/master/core/frontend/src/components/vehiclesetup/configuration/compass/ArdupilotMavlinkCompassSetup.vue#L237
> core: frontend: fix prop type for compassDisplay

- core/frontend/src/components/kraken/ExtensionCard.vue
- core/frontend/src/components/kraken/ExtensionModal.vue
- core/frontend/src/types/kraken.ts
- core/frontend/src/views/ExtensionManagerView.vue
- core/services/kraken/kraken.py
- core/services/kraken/main.py
- core/services/kraken/manifest/__init__.py
- core/services/kraken/manifest/manifest.py
- core/services/kraken/manifest/models.py
- core/services/kraken/setup.py
Add check for compatibility and improves extension manager/modal UI to allow users to search/select/interact with incompatible and compatible versions
Closes #2109 
Depends on #2500
> Add check for compatibility of arch in extension store

- core/Dockerfile
> core: start-blueos-core: add python bin path to PATH

- core/frontend/src/App.vue
- core/services/versionchooser/utils/chooser.py
> [1.2]: Cherry-pick some stuff from master

- install/install.sh
This wasn't caught in my previous test as it is not quite as  "catchable" in tests
> install.sh: add step for creating dns link

- core/Dockerfile
- core/tools/ardupilot_tools/bootstrap.sh
> core: tools: logviewer: Create firmware logs folder beforehand

- core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
Enable the new tlog function in mavlink-router v4
> core: serivces: ardupilot_manager: MAVLinkRouter: Enable tlog

- core/frontend/src/components/vehiclesetup/Configure.vue
> Hide camera and gripper tabs from vehicle setup

- core/frontend/src/views/ExtensionManagerView.vue
Some users related timeouts in fetch manifest operations at Extension Page, this PR increases it to avoid these situations.
Related to #2573
> Increase timeout in fetch manifest operation at Extension Manager

- core/frontend/src/components/vehiclesetup/overview/OnboardSensors.vue
> core: frontend: onboardSensors: add celsius support

- core/frontend/src/components/kraken/ExtensionModal.vue
> Add sort on extension tags based on semantic versions in extension modal.

- .gitignore
- .hooks/pre-push
> Add prefixed cache folder for mypy and add it in gitignore

- core/frontend/src/components/vehiclesetup/configuration/compass/FullCompassCalibrator.vue
> core: frontend: compass calibration: do not cleanup on error

- core/tools/linux2rest/bootstrap.sh
This version fix some problems related to older libc in x86
> core: tools: linxu2rest: Update to 0.5.5

- core/services/ardupilot_manager/main.py
This should get rid of that huge stack trace everytime a heartbeat gets lost
> core: services: ardupilotmanager: reduce verbosity

- core/tools/blueos_startup_update/blueos_startup_update
~(needs testing of the built image)~
> core: blueos_startup_update: use loguru

- core/frontend/src/components/wifi/WifiManager.vue
~Not sure about the <br> in there, I haven't actually tested this.~
> core: frontend: make it clear we are still scanning for networks

- core/frontend/src/components/autopilot/AutopilotManagerUpdater.ts
- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/frontend/src/components/vehiclesetup/overview/VehicleInfo.vue
- core/frontend/src/components/wizard/DefaultParamLoader.vue
- core/frontend/src/components/wizard/ScriptLoader.vue
- core/frontend/src/views/Autopilot.vue
- core/frontend/src/views/VehicleSetupView.vue
- core/services/ardupilot_manager/firmware/FirmwareDownload.py
Fix some times firmwares not available in autopilot manager for 'copter' vehicles
> Increase timeout time in fetch firmware

- core/libs/commonwealth/commonwealth/utils/general.py
- core/services/helper/main.py
this is now done by cgroups and it is still causing issues in helper (MemoryError, unable to create new threads)
> Remove limit_ram_usage()

- core/services/ardupilot_manager/main.py
> ardupilot_manager: add missing async/await

- core/services/kraken/args.py
- core/services/kraken/main.py
> Kraken: Add command line args parser

- core/frontend/src/components/vehiclesetup/Configure.vue
- core/frontend/src/components/vehiclesetup/configuration/accelerometer/ArdupilotAccelerometerSetup.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/ArdupilotMavlinkCompassSetup.vue
- core/frontend/src/components/vehiclesetup/configuration/lights.vue
- core/frontend/src/components/vehiclesetup/overview/BaroCalib.vue
- core/frontend/src/components/vehiclesetup/overview/ParamSets.vue
> Improved CSS on Vehicle setup - IMU pages

- core/tools/linux2rest/bootstrap.sh
Add support to raspberry pi 5 platform endpoint
> core: tools: linux2rest: Update to 0.5.7

- core/tools/blueos_startup_update/blueos_startup_update.py
This reverts commit a2f1aca8f370fd7bbb44e2fc3cdb2bfc3a24909c.
should fix the current boot loop in master
> Revert "blueos_startup_update: add 'remove_console' step"

- core/libs/commonwealth/commonwealth/utils/commands.py
- core/tools/blueos_startup_update/blueos_startup_update.py
trying to make the blueos_startup_update logs more readable.
before:
after:
> Add run_command() logging

- core/tools/blueos_startup_update/blueos_startup_update.py
simple fix for #2639
It can be tested with williangalvani/blueos-core:fox_boot_loop_test
which includes this patch and the broken commit from #2649
fix #2639
> core: add boot-loop detection

- core/tools/linux2rest/bootstrap.sh
Add model endpoint for board/platform information
> core: tools: linux2rest: Update to 0.6.0

- install/boards/configure_board.sh
> install: boards: Add support to CM4

- core/tools/mavlink_camera_manager/bootstrap.sh
Updates:
https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.12.13
https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.13.0
https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.13.1
> core: tools: mavlink-camera-manager: Update to t3.13.1

- core/tools/mavlink2rest/bootstrap.sh
> mavlink2rest: Update and add aarch64

- core/services/kraken/api/app.py
- core/services/kraken/api/v2/routers/__init__.py
- core/services/kraken/api/v2/routers/jobs.py
- core/services/kraken/jobs/__init__.py
- core/services/kraken/jobs/exceptions.py
- core/services/kraken/jobs/jobs.py
- core/services/kraken/jobs/models.py
- core/services/kraken/main.py
Depends on #2676 
Add a jobs module to allow hit and close connection operations.
> Kraken: Add jobs for hit and close operation

- .hooks/pre-push
Fixed the error attached on my machine
[error.txt](https://github.com/bluerobotics/BlueOS/files/15265309/error.txt)
> pre-push: also install pip in pipenv

- core/tools/mavlink_camera_manager/bootstrap.sh
Relevant changes:
* Allow all CORS https://github.com/mavlink/mavlink-camera-manager/pull/409
* src: stream: webrtc: Do not panic when failing to close the websocket https://github.com/mavlink/mavlink-camera-manager/pull/411
> core: tools: mavlink-camera-manager: Update to t3.13.3

- .github/workflows/test-and-deploy.yml
> Avoid node16 updating all steps

- core/tools/ardupilot_tools/bootstrap.sh
- core/tools/bridges/bootstrap.sh
- core/tools/filebrowser/bootstrap.sh
- core/tools/linux2rest/bootstrap.sh
- core/tools/logviewer/bootstrap.sh
- core/tools/machineid/bootstrap.sh
- core/tools/mavlink2rest/bootstrap.sh
- core/tools/mavlink_camera_manager/bootstrap.sh
- core/tools/mavlink_router/bootstrap.sh
- core/tools/mavp2p/bootstrap.sh
- core/tools/ttyd/bootstrap.sh
~Merge after #2677~
Closes #2671 
Note about some versions upgrade:
- filebrowser: `v2.24.2` -> `v2.30.0`
- bridges: `0.10.1` -> `0.10.2`
- machineid: `0.2.1` -> `0.2.2`
> Refactor and add missing aarch64 binaries

- .github/workflows/test-and-deploy.yml
Each job has different CI context
> ci: test-and-deploy: Move free disk space step in docker build

- core/frontend/src/components/version-chooser/VersionCard.vue
- core/frontend/src/components/version-chooser/VersionChooser.vue
> Disable delete button if two images or less are available

- core/frontend/src/components/wizard/ActionStepper.vue
> core: components: wizard: ActionStepper: Remove check if action is done

- core/frontend/src/components/wizard/RequireInternet.vue
> core: frontend: componentes: wizard: RequireInternet: Decrease time check

- core/frontend/src/components/wizard/ActionStepper.vue
* Disable checkboxes after all apply is done in ActionStepper prior to navigationg to wizard complete.
> frontend: Wizard: ActionStepper: Disable checkboxes after all configuration is done

- core/frontend/src/App.vue
- core/frontend/src/components/health/GpsTrayMenu.vue
Fix https://github.com/bluerobotics/BlueOS/issues/1749
> core: components: GpsTrayMenu: First version

- core/frontend/src/components/version-chooser/VersionCard.vue
> core: frontend: components: version-chooser: Make bootstrap update less dangerous

- core/frontend/src/components/version-chooser/VersionChooser.vue
> frontend: VersionChooser: Add internet checking prior to fetch remote tags

- core/frontend/src/components/video-manager/VideoManager.vue
- core/frontend/src/store/video.ts
> frontend: Add fix for error in fetch available devices on VideoManager

- .gitmodules
- core/frontend/src/types/autopilot/parameter-table.ts
- core/frontend/vite.config.js
these should meaningfully update the metadata for versions higher than 4.1
> frontend: try to load apropriate metadata files for ardupilot

- core/frontend/src/components/health/GpsTrayMenu.vue
> core: components: GpsTrayMenu: Move to satellite icon

- core/services/helper/main.py
> helper: Deal with gzip files

- core/frontend/src/components/autopilot/EndpointCreationDialog.vue
> frontend: mavlink endpoints: improve validation

- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/frontend/src/types/autopilot/parameter-table.ts
> Reset params and metadata after firmware flashing

- core/frontend/src/components/vehiclesetup/configuration/compass/CompassDisplay.vue
> frontend: CompassDisplay: fix ekf arrow being black

- core/frontend/src/components/health/GpsTrayMenu.vue
> core: frontend: componentes: health: GpsTrayMenu: Add menu and more information

- deploy/pimod/blueos.Pifile
> deploy: pimod: Increase pump to 2200

- core/frontend/src/components/wizard/DefaultParamLoader.vue
> frontend: wizard: DefaultParamLoader: Fix Unknown

- core/frontend/src/components/kraken/BackAlleyTab.vue
- core/frontend/src/types/kraken.ts
- core/services/kraken/manifest/models.py
> Sort extensions by download number

- core/tools/blueos_startup_update/blueos_startup_update.py
> Improve exception handling in blueos_startup_update

- core/tools/logviewer/bootstrap.sh
- core/tools/nginx/nginx.conf
> tools: fix logviewer

- core/frontend/src/components/kraken/cards/InstalledExtensionCard.vue
- core/frontend/src/views/ExtensionManagerView.vue
- core/services/kraken/extension/extension.py
- core/services/kraken/harbor/container.py
* Add better treatment for enable/disable/restart extension
* Fix reactivity of loading property in installed extensions
* Add over spinning logo when performing operations on extensions
* Add alert popup when something goes wrong in pull/update pull extension
> Add better treatment for edge cases on extension UI page

- core/frontend/src/components/parameter-editor/InlineParameterEditor.vue
> frontend: inlineParameterEditor: prevent submitting form

- core/frontend/src/components/vehiclesetup/configuration/compass/ArdupilotMavlinkCompassSetup.vue
> frontend: compass calibration: add more calibration information and different calibration levels

- core/frontend/src/components/utils/ParameterLoadingSpinner.vue
- core/frontend/src/components/utils/RebootButton.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/FullCompassCalibrator.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/LargeVehicleCompassCalibrator.vue
- core/frontend/src/types/autopilot/parameter-fetcher.ts
bonus:
- block loading parameters while rebooting
- add "rebooting" text to spinningParanLoader
fix #2774
> Create reboot button component

- core/tools/mavlink_router/bootstrap.sh
image ready, needs testing (on amd64)
> tools: mavlink-router: use glibc for mavlink-router on amd64

- core/frontend/src/components/app/VehicleBanner.vue
- core/frontend/src/components/wizard/Wizard.vue
We should use absolute path and not relative
> Fix vehicle image

- core/services/ardupilot_manager/mavlink_proxy/MAVP2P.py
> AutopilotManager: don't request streamrates with mavp2p

- core/tools/mavlink_camera_manager/bootstrap.sh
Relevant changes:
* Adds the `turn-servers` CLI argument
* RTSP RAW/JPEG fix
[full list of changes here](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.16.0)
> core: tools: mavlink-camera-manager: Update to t3.16.0

- core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
> frontend: StreamCreatingDialog: Fix URI prefix

- core/frontend/src/components/vehiclesetup/Configure.vue
- core/frontend/src/router/index.ts
- core/frontend/src/views/VehicleSetupView.vue
this maps tabs and sub-tabs to urls, which means we can now link to /vehicle/setup/configure/compass and so on
> frontend: update urls in vehicle setup

- core/libs/commonwealth/commonwealth/mavlink_comm/typedefs.py
- core/tools/ardupilot_tools/bootstrap.sh
fix #2833 
to test, just try flashing the latest ardusub beta from the cloud, it should work now
> Add support for Numbered betas for ardupilot

- core/services/helper/main.py
> core: services: helper: Skip Iperf and Major Tom

- core/frontend/src/utils/streaming.ts
- core/frontend/src/views/ExtensionManagerView.vue
- core/libs/commonwealth/commonwealth/utils/streaming.py
- core/services/kraken/api/v1/routers/index.py
- core/services/kraken/api/v2/routers/container.py
* Add continuous logging in backend
* Add heartbeats in streamer to force data to frontend
* Add auto reconnect in frontend
> Frontend/Kraken: Add continuous logging for better Extensions debugging

- core/frontend/src/components/common/JsonEditor.vue
- core/frontend/src/components/kraken/modals/ExtensionDetailsModal.vue
- core/frontend/src/views/ExtensionManagerView.vue
> Frontend: Beautify extension details page to be responsive and add support fro permissions editing

- core/frontend/src/components/app/SettingsMenu.vue
- core/services/commander/main.py
> Add MAVLink logs size checking and removal in gear menu

- core/tools/linux2rest/bootstrap.sh
Fix ram / virtual memory report
> core: tools: linux2rest: Update to 0.6.1

- core/libs/commonwealth/commonwealth/utils/general.py
- core/tools/blueos_startup_update/blueos_startup_update.py
this will allow using these elsewhere
> blueos_startup_update, commonwealth: extract cpu/host detection to commonwealth

- install/boards/bcm_2712.sh
- install/boards/configure_board.sh
tested by running this script followed by 
`./install.sh --skip-board-config`
> install: add board setup file for pi5

- core/tools/linux2rest/bootstrap.sh
https://github.com/patrickelectric/linux2rest/releases/tag/v0.6.2
> core: tools: linux2rest: Update to 0.6.2

- core/services/ardupilot_manager/args.py
- core/services/ardupilot_manager/main.py
> Move args to module AutopilotManager - (Serial PX4 support part 2)

- bootstrap/startup.json.default
- core/services/cable_guy/api/manager.py
- core/services/cable_guy/networksetup.py
- core/services/cable_guy/setup.py
- core/services/cable_guy/typedefs.py
- core/tools/blueos_startup_update/blueos_startup_update.py
> Cable_guy: refactor for adding NetworkManager support

- core/Dockerfile
See the changes [here](https://github.com/bluerobotics/blueos-docker-base/pull/58)
> core: Update blueos-base, new GStreamer 1.24.8, libcamera 0.3.1

- install/install.sh
- install/kraken/set_default_extensions.sh
> install: install: Add curl retry and timeout

- core/services/versionchooser/setup.py
version chooser is broken in master
> version chooser: fix yarl version

- core/services/ardupilot_manager/ArduPilotManager.py
> ArdupilotManager: fix issue when sitl_frame is not set in the settings file

- core/services/ardupilot_manager/README.md
- core/services/ardupilot_manager/api/app.py
- core/services/ardupilot_manager/api/v1/routers/endpoints.py
- core/services/ardupilot_manager/api/v1/routers/index.py
- core/services/ardupilot_manager/api/v2/routers/index.py
- core/services/ardupilot_manager/autopilot_manager.py
- core/services/ardupilot_manager/exceptions.py
- core/services/ardupilot_manager/main.py
- core/services/ardupilot_manager/setup.py
Depends on #2940
Moves from ArduPilot occurrences to AutoPilot in cases where does not affect like paths
> Core: AutoPilot Manager: Move from Ardu to Auto names only (Serial PX4 support part 4) 

- core/frontend/src/components/bridges/BridgeCreationDialog.vue
> frontend: fix UI description in bridges

- core/frontend/src/components/vehiclesetup/configuration/compass/ArdupilotMavlinkCompassSetup.vue
- core/frontend/src/components/vehiclesetup/configuration/compass/CompassDisplay.vue
also changes it so the arrows no longer overlap
> VehiceSetup: CompassDisplay: display GpsYaw when it is available

- core/tools/mavlink_camera_manager/bootstrap.sh
[release notes](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.16.1)
> core: tools: mavlink-camera-manager: Update to t3.16.1

- core/tools/mavlink_server/bootstrap.sh
[Changelog](https://github.com/bluerobotics/mavlink-server/compare/0.2.1...0.2.2)
> core: tools: mavlink-server: Update to 0.2.2

- core/frontend/src/components/parameter-editor/ParameterLoader.vue
The users are not happy having a tooltip showing when not necessary
> frontend: components: parameter-editor: ParameterLoader: Add delay in tooltips

- core/frontend/src/components/parameter-editor/ParameterLoader.vue
> frontend: components: parameter-editor: ParameterLoader: Improve style

- core/frontend/src/components/wizard/DefaultParamLoader.vue
> [1.3] Cherry-pick some commits

- core/tools/mavlink_camera_manager/bootstrap.sh
changelog: https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.17.0
> core: tools: mavlink_camera_manager: Update to t3.17.0

- core/frontend/src/store/bag.ts
- core/frontend/src/types/frontend_services.ts
https://www.dndbeyond.com/sources/dnd/free-rules/magic-items-a-z#BagofHolding
> Correct name of "Bag of Holding"

- core/services/cable_guy/main.py
> core: services: cable_guy: Fix root path not working

- core/tools/mavlink_server/bootstrap.sh
[changelog](https://github.com/bluerobotics/mavlink-server/releases/tag/0.3.1)
> core: tools: mavlink-server: Update to 0.3.1

- core/services/helper/main.py
related to https://github.com/bluerobotics/ping-viewer-next/pull/46
and https://github.com/bluerobotics/cockpit/pull/1499
> Helper: add support for cockpit widgets

- core/start-blueos-core
> start-bluos-core: make sure BLUEOS_DISABLE_SERVICES is always set

- core/tools/blueos_startup_update/blueos_startup_update.py
> blueos_startup_update: add networkmanager setup

- core/frontend/src/components/parameter-editor/InlineParameterEditor.vue
> core: frontend: components: InlineParameterEditor: Add default label

- core/frontend/src/components/wifi/ConnectionDialog.vue
- core/frontend/src/components/wifi/DisconnectionDialog.vue
- core/frontend/src/components/wifi/WifiManager.vue
- core/frontend/src/store/wifi.ts
https://github.com/user-attachments/assets/4d3e1336-3ea8-4176-8a4d-3308b31f776a
> frontend: Add wifi animation when doing actions

- core/frontend/src/components/vehiclesetup/overview/ParamSets.vue
> core: frontend: components: ParamSets: Fix parameter file name comparison

- core/frontend/src/components/autopilot/FirmwareManager.vue
- core/frontend/src/components/wifi/WifiUpdater.vue
- core/frontend/src/components/wizard/RequireInternet.vue
- core/frontend/src/libs/notifier.ts
- core/frontend/src/store/bag.ts
- core/frontend/src/store/beacon.ts
- core/frontend/src/store/commander.ts
- core/frontend/src/store/helper.ts
- core/frontend/src/store/system-information.ts
- core/frontend/src/store/video.ts
- core/frontend/src/utils/api.ts
> Add isBackendOffline

- core/services/versionchooser/utils/dockerhub.py
No infinite update button:
fix #3036 
fix #2854
> core: version chooser: deal with 64bit kernel 32bit userland case

- core/frontend/src/views/Autopilot.vue
> core: frontend: Autopilot: Add wizard button

- core/frontend/src/components/ethernet/AddressCreationDialog.vue
> frontend: AddressCreationDialog: don't submit when pressing enter

- core/frontend/src/components/parameter-editor/ServoFunctionEditorDialog.vue
- core/frontend/src/components/vehiclesetup/PwmSetup.vue
I intend to add specific settings in here depending on the selected function, too, on another PR
> frontend: add ServoFunctionEditorDialog

- core/frontend/src/components/autopilot/EndpointCard.vue
- core/frontend/src/components/autopilot/EndpointCreationDialog.vue
> Frontend: Ednpoint(CreationDialog/Card): Fix modify endpoint object directly when editing it

- core/services/cable_guy/networksetup.py
This fix a halt when there is nothing connected via cable
> Minor fixes on network manager

- core/frontend/src/components/version-chooser/VersionChooser.vue
Not directly, but similar to #1033
Fix edge case when deleting:
> frontend: VersionChooser: Fix delete edge case

- core/frontend/src/components/parameter-editor/ServoFunctionEditorDialog.vue
> core: frontend: parameter-editor: ServoFunctionEditorDialog: Enable auto-set

- core/tools/mavlink_camera_manager/bootstrap.sh
Closes #3187
full changelog: https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.19.0
> core: tools: mavlink-camera-manager: Update to t3.19.0

- .gitmodules
Should fix our sync modules CI
> gitmodules: Update PX4-parameters to use https over ssh

- core/tools/mavlink_camera_manager/bootstrap.sh
- core/tools/mavlink_server/bootstrap.sh
> update mavlink-camera-manager and mavlink-server to latest version

- core/tools/mavlink_camera_manager/bootstrap.sh
[changelog](https://github.com/mavlink/mavlink-camera-manager/releases/tag/t3.22.1)
> core: tools: mavlink-camera-manager: Update to t3.22.1
